// zx0fixture emits the baked-bytes fixture for the i68 ZX0 boot
// self-tests (docs/specs/comment-storage-design.md §7.1).
//
// It extracts a fixed, deterministic raw block of comment text from the
// vendored release source (tests/release/release.s), compresses it with
// the Go authority (zx0greedy.Compress at the design operating point
// H=512, D=16 — the exact parameters baked into src/zx0_compress.asm),
// and writes a pyz80 include file defining:
//
//	ZX0T_RAW_LEN / ZX0T_COMP_LEN   equ lengths
//	zx0t_raw / zx0t_comp           defb blocks
//
// src/zx0_payload.asm includes the file under BUILD_TESTS; at boot the
// SAM (a) compresses zx0t_raw and byte-compares against zx0t_comp, and
// (b) decodes zx0t_comp and byte-compares against zx0t_raw.  Greedy is
// deterministic and the Z80 port is byte-identical to Go, so both are
// exact tests.
//
// Raw-block extraction rule (fixed so the fixture is reproducible from
// the vendored source alone): take every line whose first non-blank
// characters are "//" (the corpus's comment lines), join with '\n', and
// keep the first rawLen bytes.  Real comment prose exercises literals,
// rep matches, and multi-byte new-offset matches — the same shape as
// the editor's blocks.
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	zx0greedy "github.com/petemoore/sam-aarch64/tools/zx0-greedy"
)

// rawLen is the fixture block size.  1 KB keeps the boot-time compress
// cost trivial (~0.17 s at 6 MHz at the measured 972 T/byte) while
// spanning offsets past 128 so the new-offset MSB path (offset > one
// LSB byte) is exercised.
const rawLen = 1024

func main() {
	log.SetFlags(0)
	log.SetPrefix("zx0fixture: ")

	srcPath := flag.String("src", "", "path to the vendored release source (tests/release/release.s)")
	outPath := flag.String("out", "", "path of the pyz80 include file to write")
	flag.Parse()
	if *srcPath == "" || *outPath == "" {
		flag.Usage()
		os.Exit(2)
	}

	src, err := os.Open(*srcPath)
	if err != nil {
		log.Fatalf("open src: %v", err)
	}
	defer src.Close()

	var raw bytes.Buffer
	scanner := bufio.NewScanner(src)
	scanner.Buffer(make([]byte, 0, 1<<20), 1<<20)
	for scanner.Scan() && raw.Len() < rawLen {
		line := scanner.Text()
		if strings.HasPrefix(strings.TrimLeft(line, " \t"), "//") {
			raw.WriteString(line)
			raw.WriteByte('\n')
		}
	}
	if err := scanner.Err(); err != nil {
		log.Fatalf("scan src: %v", err)
	}
	if raw.Len() < rawLen {
		log.Fatalf("source has only %d bytes of comment-line text; need %d", raw.Len(), rawLen)
	}
	rawBlock := raw.Bytes()[:rawLen]

	comp := zx0greedy.Compress(rawBlock, zx0greedy.DefaultParams)

	var out bytes.Buffer
	fmt.Fprintf(&out, "; AUTO-GENERATED by tools/zx0-greedy/cmd/zx0fixture — do not edit.\n")
	fmt.Fprintf(&out, "; Raw block: first %d bytes of comment-line text from tests/release/release.s.\n", rawLen)
	fmt.Fprintf(&out, "; Compressed with zx0greedy.Compress (H=%d, D=%d) — the Go authority.\n",
		zx0greedy.DefaultParams.HashSize, zx0greedy.DefaultParams.ChainDepth)
	fmt.Fprintf(&out, "\nZX0T_RAW_LEN:   equ     %d\n", len(rawBlock))
	fmt.Fprintf(&out, "ZX0T_COMP_LEN:  equ     %d\n", len(comp))
	writeBlock(&out, "zx0t_raw", rawBlock)
	writeBlock(&out, "zx0t_comp", comp)

	if err := os.WriteFile(*outPath, out.Bytes(), 0o644); err != nil {
		log.Fatalf("write out: %v", err)
	}
	fmt.Printf("zx0fixture: raw %d B → compressed %d B (ratio %.4f) → %s\n",
		len(rawBlock), len(comp), float64(len(comp))/float64(len(rawBlock)), *outPath)
}

// writeBlock emits a label and its bytes as defb lines, 16 per line.
func writeBlock(out *bytes.Buffer, label string, data []byte) {
	fmt.Fprintf(out, "\n%s:\n", label)
	for i := 0; i < len(data); i += 16 {
		end := i + 16
		if end > len(data) {
			end = len(data)
		}
		parts := make([]string, 0, 16)
		for _, b := range data[i:end] {
			parts = append(parts, fmt.Sprintf("&%02X", b))
		}
		fmt.Fprintf(out, "        defb    %s\n", strings.Join(parts, ", "))
	}
}
