// Package emit writes the generated Go source and binary .enc
// outputs of enctab-gen.
package emit

import (
	"fmt"
	"io"
	"sort"

	enc "github.com/petemoore/sam-aarch64/tools/aarch64enc"
)

// RenderGoPackage writes a deterministic data.go to w, populating
// FormsForMnemonic from the generated form table.
func RenderGoPackage(w io.Writer, forms []enc.Form) error {
	fmt.Fprintln(w, "// Code generated by enctab-gen. DO NOT EDIT.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "package aarch64enc")
	fmt.Fprintln(w)

	sorted := make([]enc.Form, len(forms))
	copy(sorted, forms)
	sort.SliceStable(sorted, func(i, j int) bool {
		return sorted[i].MnemonicID < sorted[j].MnemonicID
	})

	fmt.Fprintln(w, "var generatedForms = []Form{")
	for _, f := range sorted {
		fmt.Fprintf(w, "\t{MnemonicID: %d, Pattern: 0x%08x, Mask: 0x%08x, Slots: []OperandSlot{",
			f.MnemonicID, f.Pattern, f.Mask)
		if len(f.Slots) == 0 {
			fmt.Fprintln(w, "}},")
			continue
		}
		fmt.Fprintln(w)
		for _, s := range f.Slots {
			fmt.Fprintf(w, "\t\t{SlotKind: %s, ExpectedKind: %d, BitPosition: %d, BitWidth: %d},\n",
				s.SlotKind.Name(), uint8(s.ExpectedKind), s.BitPosition, s.BitWidth)
		}
		fmt.Fprintln(w, "\t}},")
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "func init() {")
	fmt.Fprintln(w, "\tFormsForMnemonic = func(id uint16) []Form {")
	fmt.Fprintln(w, "\t\tvar out []Form")
	fmt.Fprintln(w, "\t\tfor _, f := range generatedForms {")
	fmt.Fprintln(w, "\t\t\tif f.MnemonicID == id {")
	fmt.Fprintln(w, "\t\t\t\tout = append(out, f)")
	fmt.Fprintln(w, "\t\t\t}")
	fmt.Fprintln(w, "\t\t}")
	fmt.Fprintln(w, "\t\treturn out")
	fmt.Fprintln(w, "\t}")
	fmt.Fprintln(w, "}")
	return nil
}
