; B-DOS 1.5a - byte-exact pyz80 reconstruction of the freeware bdos15a.bin
; Generated by reference/bdos/gen-bdos15a.py; proven by `make bdos15a-bytematch`.
; Edwin Blink 1997/1998 (freeware). See reference/bdos/README.md.
        org &8009
        ld a,&df
        out (&f5),a
l_800d:
        dec a
        jr nz,l_800d
        dec a
        out (&f5),a
        ld hl,l_8200
        jr l_8061
l_8018:
        ld a,&0a
l_801a:
        ex af,af'
        ld a,e
        out (&e2),a
        ld a,d
        out (&e3),a
        ld a,&13
        call l_8054
        di
        push hl
        ld a,&80
        out (&e0),a
        ld bc,&14e3
l_802f:
        djnz l_802f
        ld a,&ed
        and d
l_8034:
        in a,(&e0)
        bit 1,a
        jr nz,&8032
        rra
        jr c,l_8034
        ei
        and &0e
        jr z,l_8060
        pop hl
        ex af,af'
        cp &05
        jr nz,l_804f
        ex af,af'
        ld a,&0b
        call l_8054
        ex af,af'
l_804f:
        dec a
        jr nz,l_801a
        rst &08
        inc de
l_8054:
        out (&e0),a
        ld b,&14
l_8058:
        djnz l_8058
l_805a:
        in a,(&e0)
        rra
        jr c,l_805a
        ret
l_8060:
        pop de
l_8061:
        dec hl
        ld e,(hl)
        dec hl
        ld d,(hl)
        ld a,d
        or e
        jr nz,l_8018
        ld hl,&5ada
l_806c:
        ld (hl),a
        inc l
        jr nz,l_806c
        ld hl,&0049
        ld (&5b70),hl
        ld (l_80b9),a
        ld a,(&5cb4)
        ld (&811c),a
        dec a
        ld (&810a),a
        dec a
        ld (&5bc2),a
        ld h,&51
        ld l,a
        ld (hl),&60
        ld hl,l_80b7
        ld (&8000),hl
        ld hl,(l_80ba)
        ld (&5a06),hl
        ld a,&ef
        ld (&59aa),a
        ld hl,&1cb9
        ld de,&ed20
        ld a,(&000f)
        cp &14
        jr z,l_80ae
        ld e,&39
        ld l,&9e
l_80ae:
        ld (&5ae0),hl
        call &0033
        jp l_a773
l_80b7:
        rlca
        ret nc
l_80b9:
        nop
l_80ba:
        ld b,h
        ld bc,&0020
        dec b
        defb &00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00
        nop
        ld bc,&0000
        nop
        nop
        nop
        nop
        nop
        nop
        and b
        jp l_a777
l_80dd:
        ld bc,&0000
        nop
        nop
        nop
        nop
        nop
        nop
        rst &38
        ld b,h
        djnz &812b
        ld d,l
        ld d,h
        ld c,a
        ld hl,(&2020)
        jr nz,&8112
        jr nz,&8114
        jr nz,&8116
        jr nz,l_80f8
l_80f8:
        rst &38
        rst &38
        rst &38
        rst &38
        rst &38
        rst &38
        rst &38
        rst &38
        ld b,d
        ld c,a
        ld c,a
        call nc,&0000
        defb &00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00
        jr nz,l_8140
        jr nz,&8142
        jr nz,l_8144
        jr nz,l_8146
        jr nz,&8148
        jr nz,l_814a
        jr nz,l_814c
        jr nz,&814e
        nop
        nop
        nop
        nop
        nop
        ld b,d
        dec l
        ld b,h
        ld c,a
        ld d,e
        jr nz,&819c
        ld a,c
        jr nz,l_8182
        ld h,h
        ld (hl),a
        ld l,c
l_8140:
        ld l,(hl)
        jr nz,&8185
        ld l,h
l_8144:
        ld l,c
        ld l,(hl)
l_8146:
        ld l,e
        jr nz,l_817a
        add hl,sp
l_814a:
        add hl,sp
        scf
l_814c:
        cpl
        jr c,l_814f
l_814f:
        nop
        nop
        nop
        nop
        jr nz,l_8175
        jr nz,l_8177
        jr nz,l_8179
        jr nz,&817b
        jr nz,&817d
        jr nz,&817f
        jr nz,&8181
        defb &00,&00,&00,&00,&00,&00,&00,&00
        nop
        nop
        jr nz,l_818d
        jr nz,l_818f
        jr nz,l_8191
        jr nz,l_8193
        jr nz,l_8195
l_8175:
        jr nz,&8197
l_8177:
        jr nz,&8199
l_8179:
        nop
l_817a:
        jr nz,&819c
        jr nz,&819e
        jr nz,&81a0
        jr nz,&81a2
l_8182:
        jr nz,&81a4
        jr nz,&81a6
        jr nz,&81a8
        nop
        jr nz,&81ab
        jr nz,&81ad
l_818d:
        jr nz,&81af
l_818f:
        jr nz,&81b1
l_8191:
        jr nz,&81b3
l_8193:
        jr nz,l_8195
l_8195:
        defb &00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00
        jr nz,l_81c3
        jr nz,l_81c5
        jr nz,&81c7
        jr nz,&81c9
        nop
        jr nz,&81cc
        jr nz,&81ce
        jr nz,&81d0
        jr nz,&81d2
        jr nz,&81d4
        jr nz,&81d6
        jr nz,&81d8
        nop
        jr nz,l_81db
        jr nz,l_81dd
        jr nz,l_81df
        jr nz,l_81e1
        jr nz,l_81e3
l_81c3:
        jr nz,l_81c5
l_81c5:
        defb &00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00,&00
        jr nz,l_81f3
        jr nz,l_81f5
        jr nz,l_81f7
        jr nz,&81f9
        nop
        nop
l_81db:
        nop
        nop
l_81dd:
        nop
        nop
l_81df:
        nop
        ld d,e
l_81e1:
        ld c,(hl)
        ld b,c
l_81e3:
        ld d,b
        jr nz,l_8206
        jr nz,&8208
        jr nz,l_820a
        jr nz,l_820c
        jr nz,l_820e
        inc de
        nop
        ret nz
        nop
        add a,b
l_81f3:
        nop
        nop
l_81f5:
        rst &38
        rst &38
l_81f7:
        dec l
        ld a,&73
        call nz,&59aa
        inc l
        ret
        nop
l_8200:
        jp &431c
        jp &4212
l_8206:
        jp &4bb4
        nop
l_820a:
        nop
        nop
l_820c:
        nop
        nop
l_820e:
        nop
        nop
        ld d,&9b
        ld (&4106),sp
        cp &1d
        jp nz,&4263
        call &4375
        call &437f
        ld hl,&0000
        ld (&4104),hl
        xor a
        ld (&780c),a
        ld ix,&7800
        call &5c07
        sub a
        ld e,d
        ld (&425a),bc
        call &5c07
        ld a,e
        ld e,d
        call &5c2d
        sub a
        ld e,d
        call &4316
l_8245:
        ld c,&3a
        call &430d
        jr z,l_8245
        ld b,&10
        ld hl,&426f
l_8251:
        inc hl
        inc hl
        cp (hl)
        inc hl
        jr z,l_8266
        djnz l_8251
        ld bc,&0000
        call &5c2d
        sub a
        ld e,d
        ld a,&1d
        ld e,&00
        ret
l_8266:
        ld c,(hl)
        inc hl
        ld b,(hl)
        ld hl,&42c3
        push hl
        push bc
        jp &430f
        jp p,&51bc
        pop af
        or a
        ld d,c
        ret p
        call z,&ef61
        di
        ld e,a
        call po,&4b4b
        ex (sp),hl
        ccf
        ld d,c
        rst &08
        or &4e
        cp d
        xor (hl)
        ld h,c
        cp b
        inc sp
        ld e,(hl)
        sub a
        dec sp
        ld e,(hl)
        sub l
        jr z,&82e4
        sub d
        rst &18
        ld d,b
        sub c
        and a
        ld c,h
        sub b
        ld b,d
        ld d,h
        add a,(hl)
        dec hl
        ld e,(hl)
        ld l,&62
        ld e,a
        call &4316
        cp &0d
        ret z
        cp &3a
        ret
        ld (&42b7),a
        call &5c1e
        dec sp
        ld e,h
        rlca
        rlca
        bit 1,a
        ld a,&00
        ret
        call &42a1
        jp nz,&42e2
        call &42aa
        ret nz
        ld e,&00
        xor a
        call &5c44
        and h
        ld e,d
        call &5c44
        jp &ed5b
        ld a,e
        ld b,&41
        push af
        call &5c1e
        ld c,e
        ld e,h
        out (&fe),a
        pop af
        ret
        call &42e6
        ret z
l_82e2:
        call &5aaa
        dec e
        call &42fb
        jr z,l_830f
        cp &22
        ret
        call &42a1
        ret z
        cp &23
        ret z
        cp &3f
        ret z
        cp &8e
        ret z
        cp &2c
        ret z
        cp &3b
l_8300:
        ret
        ld c,&a6
        call &430d
        jp z,&5c66
        ret
        cp c
        jr nz,l_82e2
        cp c
        ret nz
l_830f:
        call &0103
        jr nz,l_8314
l_8314:
        cp a
        ret
        call &0103
        jr l_831b
l_831b:
        ret
        ld (&4106),sp
        ld (&410b),ix
        exx
        ex af,af'
        ld (&41d9),a
        ld (&41da),hl
        ld (&41dc),de
        ld (&41de),bc
        ex af,af'
        exx
        call &4375
        ld hl,&0000
        ld (&4104),hl
        add a,a
        cp &4e
        jr nc,l_835e
        ld l,a
        ld de,&43a2
        add hl,de
        ld e,(hl)
        inc hl
        ld d,(hl)
        xor a
        ld (&780c),a
        ld a,(&41d9)
        push ix
        pop hl
        ld ix,&7800
        call &0033
        ld d,a
l_835e:
        call &42d4
        call &436c
        xor a
        ld e,a
        call &5c44
        jp &c95b
        ld a,&d3
        ld (&42da),a
        ld (&4650),a
        ret
        push af
        ld a,&01
        call &5c44
        jp &f15b
        ret
        ld hl,&412e
        ld b,&4b
l_8384:
        ld (hl),&ff
        inc hl
        djnz l_8384
        call &5c1e
        ld b,&5a
        ld (&4135),a
        call &5c1e
        rlca
        ld e,d
        ld (&4132),a
        ld bc,(&40d0)
        ld (&40d3),bc
        ret
        jp pe,&2a5d
        ld e,l
        or (hl)
        ld b,(hl)
        or e
        ld b,(hl)
        add a,c
        ld e,l
        defb &dd
        ld b,d
        ld a,&5e
        ld (&ea64),hl
        ld e,l
        defb &dd
        ld b,d
        defb &dd
        ld b,d
        or l
        ld e,l
        defb &dd
        ld b,d
        defb &dd
        ld b,d
        defb &dd
        ld b,d
        defb &dd
        ld b,d
        defb &dd
        ld b,d
        defb &dd
        ld b,d
        defb &dd
        ld b,d
        sub b
        ld b,a
        xor c
        ld b,a
        ld b,e
        ld e,(hl)
        add a,l
        ld c,b
        defb &dd
        ld b,d
        cp (hl)
        ld c,c
        defb &dd
        ld b,d
        defb &dd
        ld b,d
        defb &dd
        ld b,d
        ret c
        ld e,a
        cp e
        ld b,(hl)
        ld d,&5e
        and c
        ld b,(hl)
        ld c,b
        ld e,(hl)
        pop bc
        ld b,(hl)
        ld (hl),&5e
        ld l,&5e
        push de
        ld b,l
        add a,a
        ld d,h
        ld l,&51
        xor a
        ld (&455b),a
l_83f4:
        call &45b3
        call &4680
        jp nz,&630f
        call &5caa
        call &4409
        ei
        call &454e
        jr l_83f4
        ld b,&ff
        di
        push bc
        ld a,&a0
        call &4624
        bit 2,c
        pop bc
        jr nz,l_8442
        jr l_8428
l_8419:
        ld a,(hl)
        out (&e3),a
        inc hl
        dec bc
        ld a,b
        or c
        jr nz,l_8428
        ex de,hl
        ld a,(&411c)
        out (&fb),a
l_8428:
        in a,(&e0)
        bit 1,a
        jr nz,l_8419
        rra
        jr c,l_8428
        jr l_844b
l_8433:
        ld a,(hl)
        out (&e7),a
        inc hl
        dec bc
        ld a,b
        or c
        jr nz,l_8442
        ex de,hl
        ld a,(&411c)
        out (&fb),a
l_8442:
        in a,(&e4)
        bit 1,a
        jr nz,l_8433
        rra
        jr c,l_8442
l_844b:
        bit 5,a
        ret z
        call &5aaa
        ld l,b
        xor a
        ld (&455b),a
l_8456:
        call &45b3
        call &4680
        jp nz,&6369
        call &5caa
        ld a,&80
        call &4488
        ei
        call &454e
        jr l_8456
        xor a
        ld (&455b),a
l_8471:
        call &45b3
        call &4680
        call &5caa
        jp nz,&63c4
        ld a,&80
        call &44c6
        ei
        call &454e
        jr l_8471
        ld b,&ff
        di
        push bc
        call &4624
        cp a
        ex af,af'
        bit 2,c
        pop bc
        jr nz,l_84b7
        jr l_84a2
l_8498:
        in a,(&e3)
        ld (hl),a
        inc hl
        dec bc
        ld a,b
        or c
        jr nz,l_84a2
l_84a1:
        ex de,hl
l_84a2:
        in a,(&e0)
        bit 1,a
        jr nz,l_8498
        rra
        jr c,l_84a2
        jr l_84c0
l_84ad:
        in a,(&e7)
        ld (hl),a
        inc hl
        dec bc
        ld a,b
        or c
        jr nz,l_84b7
l_84b6:
        ex de,hl
l_84b7:
        in a,(&e4)
        bit 1,a
        jr nz,l_84ad
        rra
        jr c,l_84b7
l_84c0:
        ex af,af'
        jp nz,&46d8
        ex af,af'
        ret
        ld b,&ff
        di
        push bc
        call &4624
        cp a
        ex af,af'
        bit 2,c
        pop bc
        jr nz,l_84f9
        jr l_84e2
l_84d6:
        in a,(&e3)
        cp (hl)
        jr z,l_84dc
        ex af,af'
l_84dc:
        inc hl
        dec bc
        ld a,b
        or c
        jr z,l_84a1
l_84e2:
        in a,(&e0)
        bit 1,a
        jr nz,l_84d6
        rra
        jr c,l_84e2
        jr l_84c0
l_84ed:
        in a,(&e7)
        cp (hl)
        jr z,l_84f3
        ex af,af'
l_84f3:
        inc hl
        dec bc
        ld a,b
        or c
        jr z,l_84b6
l_84f9:
        in a,(&e4)
        bit 1,a
        jr nz,l_84ed
        rra
        jr c,l_84f9
        jr l_84c0
        xor a
        ld (&455b),a
l_8508:
        call &45b3
        call &4680
        jp nz,&63f2
        ld a,&80
        call &4624
        call &5caa
        exx
        ld l,&ff
        ld d,&77
        exx
        push de
        call &452a
        ei
        pop de
        call &454e
        jr l_8508
        di
        ld b,&02
        jr l_8545
l_852f:
        ld h,d
        and a
        jr nz,l_8534
        ld h,a
l_8534:
        exx
        in a,(&e0)
        and b
        jr z,l_8545
l_853a:
        in a,(&e3)
        ld (hl),a
        inc hl
        exx
        inc l
        jr z,l_852f
        or (hl)
        ld (hl),a
        exx
l_8545:
        in a,(&e0)
        rra
        ret nc
        rra
        jr nc,l_8545
        jr l_853a
        and &0e
        jr nz,l_8559
        call &5ca1
        pop hl
        jp &5caa
l_8559:
        ld b,a
        ld a,&00
        inc a
        ld (&455b),a
        cp &0a
        bit 3,b
        jr c,l_8575
        jr nz,l_856c
        call &5aaa
        ld d,l
l_856c:
        bit 2,a
        jp z,&6279
        call &5aaa
        ld d,(hl)
l_8575:
        bit 1,b
        ret nz
        bit 2,b
        jr z,l_8589
        rra
        ret nc
        rra
        jr c,l_8586
        ld a,d
        add a,a
        jp nz,&461e
l_8586:
        jp &4622
l_8589:
        ld a,&c0
        ld hl,&45a6
        ld bc,&0001
        push de
        ld d,b
        ld e,b
        call &448a
        pop de
        ei
        and &0e
        jr z,l_85a5
        call &45ad
        ld a,&0b
        jp &4624
l_85a5:
        ld a,&00
        out (&00),a
        xor d
        and &7f
        ret nz
        ld a,&09
        ld (&455b),a
        ret
        ld a,d
        or e
        jr nz,l_85bb
        call &5aaa
        ld l,h
l_85bb:
        call &4680
        jp nz,&627d
        ld c,a
        inc c
        out (c),e
        ld a,d
        and &7f
        inc c
        out (c),a
        ld a,&13
        call &4624
        call &4630
        jr l_85ec
        ld de,&0001
        call &45f7
        ret nz
        inc c
        inc c
        out (c),e
        dec c
        dec c
        ld a,&0b
        call &4624
        call &45ec
        cp a
        ret
l_85ec:
        ld c,&00
        in a,(c)
        rra
        ret nc
        call &5bf9
        jr l_85ec
        call &4680
        ret nz
        dec a
        ld c,a
        ld a,&d0
        call &4629
        ld h,b
        ld l,b
        ld b,&02
        call &460a
        ld b,a
l_860a:
        in a,(c)
        xor b
        and &02
        ret z
        ld a,&03
l_8612:
        dec a
        jr nz,l_8612
        dec hl
        ld a,h
        or l
        jr nz,l_860a
        call &5aaa
        scf
        ld a,&7b
        jr l_8624
        ld a,&5b
l_8624:
        ex af,af'
        call &45ec
        ex af,af'
        out (c),a
        ld b,&14
l_862d:
        djnz l_862d
        ret
        ld hl,&780c
        bit 6,(hl)
        jr z,l_8649
        ld hl,&7806
        ld a,(hl)
        cp &c0
        jr c,l_8649
        res 6,(hl)
        in a,(&fb)
        inc a
        ld (&411b),a
        out (&fb),a
l_8649:
        ld a,(&40b7)
        and &07
        ret z
        and e
        out (&fe),a
        ret
        ld a,(&4135)
        cp &44
        jp nz,&5f5e
        ld a,(&4132)
        cp &01
        jr z,l_866f
        cp &02
        jr nz,l_867c
        call &4673
        call &610f
        ld a,&02
        and a
l_866f:
        ld (&780b),a
        ret
        push af
        ld a,(&40b9)
        and a
        jr z,l_867c
        pop af
        ret
l_867c:
        call &5aaa
        ld h,a
        ld a,(&780b)
        dec a
        ret nz
        ld a,&e0
        bit 7,d
        jr z,l_868d
        or &04
l_868d:
        ld (&45ed),a
        inc a
        ld (&45a8),a
        cp a
        ret
        call &5cb5
        ld a,c
        cp &fe
        ret nz
        ld a,b
        cp &01
l_86a0:
        ret
        push bc
        push de
        push hl
        call &4696
        jr nz,l_86af
        ld d,(hl)
        inc hl
        ld e,(hl)
        call &4452
l_86af:
        ld a,(hl)
        jp &47c1
        call &5c6d
        call &5d5b
        jr l_86c4
        call &487a
        call &5c6d
        call &487a
l_86c4:
        call &5c74
        jr l_86df
l_86c9:
        ld a,(hl)
        call &5cc0
        ld hl,(&7805)
        call &5c89
        jr z,l_86dc
        cp (hl)
        jr z,l_86dd
        call &5aaa
        ld e,l
l_86dc:
        ld (hl),a
l_86dd:
        inc hl
        dec de
l_86df:
        ld (&7805),hl
        call &4768
        ret z
        call &4696
        jr nz,l_86c9
        ld (&7802),de
        ld d,(hl)
        inc hl
        ld e,(hl)
        call &4746
        jp c,&473c
        inc hl
        ld (&7802),hl
        xor a
        ld (&455b),a
        call &5ccf
l_8703:
        call &45b3
        call &4680
        jp nz,&637b
        ld bc,&01fe
        call &5caa
        ex de,hl
        ld hl,(&7805)
        ld a,&80
        call &5c89
        jr z,l_8722
        call &44c8
        jr l_8725
l_8722:
        call &448a
l_8725:
        and &0e
        jr z,l_8731
        call &5cc8
        call &4559
        jr l_8703
l_8731:
        ld (&7805),de
        dec hl
        ld e,(hl)
        dec hl
        ld d,(hl)
        jp &46f2
        call &4452
        ld de,(&7802)
        jp &46e6
l_8746:
        ld hl,(&7802)
        ld bc,&01fe
        scf
        sbc hl,bc
        ret nc
        ld a,(&414c)
        and a
        jr nz,l_8758
        scf
        ret
l_8758:
        dec a
        ld (&414c),a
        ld hl,(&7802)
        ld bc,&4000
        add hl,bc
        ld (&7802),hl
        jr l_8746
l_8768:
        ld a,d
        or e
        ret nz
        ld a,(&414c)
        and a
        ret z
        dec a
        ld (&414c),a
        ld de,&4000
        jr l_8768
        in a,(&fb)
        ld (&411b),a
        ld a,(&411c)
        out (&fb),a
        ld hl,(&4119)
        ret
        ld (&4119),hl
        ld a,(&411b)
        out (&fb),a
        ret
        call &5ce0
        call &47c7
        ret c
        ld hl,&4145
        ld de,&78e6
        ld b,&09
l_879f:
        ld a,(hl)
        ld (de),a
        call &47a9
        inc hl
        inc de
        djnz l_879f
        ret
        push bc
        push de
        push hl
        push af
        call &4696
        jr nz,l_87bf
        call &494a
        ld (hl),d
        inc hl
        ld (hl),e
        ex de,hl
        call &5cd6
        call &43f0
l_87bf:
        pop af
        ld (hl),a
        pop hl
        pop de
        pop bc
        jp &5cc0
l_87c7:
        push ix
        ld hl,&770f
        ld b,&c3
l_87ce:
        ld (hl),&00
        inc hl
        djnz l_87ce
        ld a,&30
        call &55a6
        jr nz,l_880f
        push de
        call &5c1e
        cp c
        ld e,e
        and a
        jr z,l_8802
        push ix
        call &5981
        ld c,a
        ld d,(hl)
        ld b,l
        ld d,d
        ld d,a
        ld d,d
        ld c,c
        ld d,h
        ld b,l
        jr nz,&8795
        call &558c
        call &5a79
        pop ix
        jr z,l_8802
        pop de
        pop ix
        scf
        ret
l_8802:
        pop de
        call &5cb1
        ld (hl),&00
        call &43f0
        pop ix
        jr l_87c7
l_880f:
        pop ix
        push ix
        ld b,&00
l_8815:
        ld (ix+19),&00
        inc ix
        djnz l_8815
        pop ix
        push ix
        ld hl,&4136
        ld b,&0b
        call &4870
        pop ix
        push ix
        ld bc,&00dc
        add ix,bc
        call &66c9
        ld hl,&40dd
        bit 1,(hl)
        res 1,(hl)
        inc hl
        ld a,(hl)
        ld hl,&4188
        ld b,&21
        jr nz,l_885a
        and a
        jr z,l_885a
        ld b,&19
        call &4870
        ld hl,&40de
        ld b,&05
        call &4870
        ld b,&03
        ld hl,&41a6
l_885a:
        call &4870
        pop ix
        call &494a
        call &5ccf
        ld (ix+32),d
        ld (ix+33),e
        call &5ca1
        xor a
        ret
l_8870:
        ld a,(hl)
        ld (ix+19),a
        inc hl
        inc ix
        djnz l_8870
        ret
        ld (&414c),a
        ld hl,(&41da)
        ld de,(&41dc)
        ret
        call &487a
        call &5c74
        jr l_8897
l_888d:
        ld (hl),d
        call &5cc0
        ld hl,(&7805)
        inc hl
        pop de
        dec de
l_8897:
        call &4768
        ret z
        push de
        ld d,(hl)
        ld (&7805),hl
        call &4696
        jr nz,l_888d
        pop de
        ld (&7802),de
        call &494a
        ld (hl),d
        inc hl
        ld (hl),e
        ex de,hl
        call &5cd6
        call &43f0
        di
        call &4746
        jp c,&493d
        call &4779
        ld hl,&a280
        ld bc,&0000
        jr l_88e3
l_88c9:
        push hl
        call &4746
        push hl
        pop de
        pop hl
        jr c,l_88e9
        inc de
        ld (&7802),de
        call &494a
        ld (hl),d
        inc hl
        ld (hl),e
        inc hl
        ld bc,(&4117)
        inc bc
l_88e3:
        ld (&4117),bc
        jr l_88c9
l_88e9:
        ld hl,&a280
        call &4787
l_88ef:
        xor a
        ld (&455b),a
        call &5cc8
l_88f6:
        call &45b3
        call &4680
        jp nz,&6320
        ld de,(&4119)
        ld hl,(&7805)
        ld bc,&01fe
        call &440b
        and &0e
        jr z,l_891d
        ld a,(&411b)
        out (&fb),a
        call &5cc8
        call &4559
        jr l_88f6
l_891d:
        ld (&7805),de
        ld (&4119),hl
        dec hl
        ld e,(hl)
        dec hl
        ld d,(hl)
        ld a,(&411b)
        out (&fb),a
        call &5ccf
        ld bc,(&4117)
        dec bc
        ld (&4117),bc
        ld a,b
        or c
        jr nz,l_88ef
        call &5ca1
        ld de,(&7802)
        ld hl,(&7805)
        jp &4888
        push hl
        push bc
        ld hl,&770f
        ld de,&0401
        ld c,&00
l_8954:
        ld a,(hl)
        cp &ff
        jr nz,l_896b
        ld a,e
        add a,&08
        ld e,a
        sub &0a
        jr c,l_8967
        jr z,l_8967
        ld e,a
        call &49a0
l_8967:
        inc c
        inc hl
        jr l_8954
l_896b:
        ld b,&01
l_896d:
        ld a,(hl)
        and b
        jr z,l_897b
        call &4998
        call z,&49a0
        rlc b
        jr l_896d
l_897b:
        ld a,(hl)
        or b
        ld (hl),a
        ld a,b
        ld b,&00
        push ix
        add ix,bc
        or (ix+34)
        ld (ix+34),a
        pop ix
        inc (ix+31)
        jr nz,l_8995
        inc (ix+30)
l_8995:
        pop bc
        pop hl
        ret
        inc e
        ld a,e
        cp &0b
        ret nz
        ld e,&01
        ret
        inc d
        call &49b2
        cp d
        jr z,l_89ae
        ld a,&50
        cp d
        ret nz
        ld d,&80
        ret
l_89ae:
        call &5aaa
        ld l,c
        ld a,(&780b)
        dec a
        ld a,(&40b8)
        ret z
        ld a,(&40b9)
        ret
l_89be:
        call &5cb5
        ld a,c
        and a
        jr nz,l_89ca
        ld a,b
        cp &02
        jr z,l_89d1
l_89ca:
        ld (hl),&00
        call &5cc0
        jr l_89be
l_89d1:
        call &5cc8
        call &43f0
        push ix
        ld a,&40
        call &55a6
l_89de:
        jr nz,l_8a38
        call &5cb1
        ld (&7807),ix
        pop ix
        push ix
        ld a,e
        dec a
        or d
        or b
        ld b,&00
        jr nz,l_8a1e
        ld a,(ix+19)
        cp &10
        jr nc,l_8a10
        ld ix,(&7807)
        inc hl
        ld a,(hl)
        and a
        jr nz,l_8a0b
        ld (hl),&20
        ld (ix+14),&01
        jr l_89de
l_8a0b:
        call &5686
        jr l_89de
l_8a10:
        ld bc,&d20a
        call &4a2b
        ld bc,&0c04
        call &4a2b
        ld b,&0e
l_8a1e:
        call &4a2b
        ld ix,(&7807)
        call &43f0
        pop ix
        ret
l_8a2b:
        ld a,(ix+19)
        ld (hl),a
        inc ix
        inc hl
        djnz l_8a2b
        add hl,bc
        add ix,bc
        ret
l_8a38:
        call &5aaa
        ld l,d
        ld a,(&4133)
        inc a
        ld a,&10
        jr z,l_8a46
        ld a,&01
l_8a46:
        call &55a6
        jp nz,&512a
        call &5cb1
        ld a,(hl)
        and &1f
        cp &10
        jr nc,l_8a5c
        dec a
        or &10
        call &5c7b
l_8a5c:
        ld (hl),a
        ld a,(&4133)
        inc a
        jr z,l_8a96
        ld de,&4136
        ld bc,&000b
        ldir
        ld b,&04
        xor a
        call &4b46
        ld (ix+13),&d3
        call &5cb5
        ld bc,&0009
        ldir
        call &5cb1
        ld de,&4179
        ld bc,&000b
        push hl
        ldir
        pop hl
        ld b,&0f
        call &4b44
        ld b,&16
        ld a,&ff
        call &4b46
l_8a96:
        ld a,(&4136)
        cp &13
        jr nz,l_8aa5
        ld a,(hl)
        cp &14
        jr nz,l_8ab0
        dec a
        jr l_8aaf
l_8aa5:
        cp &14
        jr nz,l_8ab0
        ld a,(hl)
        cp &13
        jr nz,l_8ab0
        inc a
l_8aaf:
        ld (hl),a
l_8ab0:
        ld a,(&4136)
        cp (hl)
        jr nz,l_8b19
        ld de,&4161
        ld (ix+13),&d3
        call &5cb5
        ld bc,&0009
        ldir
        ld de,&7eea
        ld bc,&0016
        ldir
        call &5cb1
        ld de,&41a9
        ld bc,&000b
        ldir
        ld b,&04
        call &4b44
        call &5c90
        jr z,l_8b1d
        ld b,&0b
        call &4b44
        ld b,&16
        ld a,&ff
        call &4b46
        ld hl,(&4162)
        call &4b38
        ld (&41cb),a
        ld (&4168),a
        ld (&41cc),hl
        ld (&4162),hl
        ld hl,(&4164)
        call &4b38
        dec a
        and &1f
        ld (&41c8),a
        ld (&4169),a
        set 7,h
        ld (&41c9),hl
        ld (&4164),hl
        jr l_8b29
l_8b19:
        call &5aaa
        ld e,(hl)
l_8b1d:
        ld (ix+13),&dc
        call &5cb5
        ld bc,&0021
        ldir
l_8b29:
        ld (ix+13),&0d
        call &5cb5
        ld d,(hl)
        inc hl
        ld e,(hl)
        ld (&7802),de
        ret
        xor a
        rl h
        rla
        rl h
        rla
        rr h
        rr h
        ret
        ld a,&20
l_8b46:
        ld (de),a
        inc de
        djnz l_8b46
        ret
        ld c,&aa
        call &430a
        call &5339
        call &42b9
        ld a,c
        and a
        jr nz,l_8b66
        ld a,&03
        out (&fb),a
        ld a,&04
        out (&fc),a
        di
        jp &b914
l_8b66:
        dec a
        jp nz,&42e2
        ld a,&04
        out (&fc),a
        di
        ld a,&03
        out (&fb),a
        ld hl,&0000
        ld (&4104),hl
        ld sp,&7eea
        pop iy
        pop ix
        pop de
        pop bc
        pop hl
        pop af
        ex af,af'
        exx
        ld hl,&4bb4
        ld (&b8f6),hl
        ld a,(&4108)
        ld (&b8f8),a
        ld a,(&4109)
        ld (&b8f9),a
        ld a,(&410a)
        ld (&b8fa),a
        pop de
        pop bc
        pop hl
        pop af
        ld i,a
        and a
        jr z,l_8bad
        cp &3f
        jr z,l_8bad
        im 2
l_8bad:
        ld sp,(&7efe)
        jp &b900
        ld (&7efe),sp
        ld sp,&7efe
        ld a,i
        push af
        push hl
        push bc
        push de
        ex af,af'
        exx
        push af
        push hl
        push bc
        push de
        push ix
        push iy
        ld hl,&4b6e
        push hl
        ld (&4104),sp
        im 1
l_8bd5:
        ld bc,&f7fe
        in e,(c)
        bit 1,e
        ret z
        bit 2,e
        jr nz,l_8be8
        ld a,&13
        ld hl,&1b00
        jr l_8c16
l_8be8:
        bit 3,e
        jr z,l_8c11
        inc a
        and &07
        out (c),a
        ld b,c
        in e,(c)
        bit 2,e
        jr nz,l_8bd5
l_8bf8:
        in e,(c)
        bit 2,e
        jr z,l_8bf8
l_8bfe:
        dec bc
        ld a,b
        or c
        jr nz,l_8bfe
        ld a,(&4109)
        out (&fb),a
        ld a,(&410a)
        out (&fc),a
        ei
        jp &42c3
l_8c11:
        ld a,&05
        ld hl,&c000
l_8c16:
        ld (&4136),a
        ld (&41ef),hl
        ld b,c
        in a,(c)
        rra
        ld a,&01
        jr c,l_8c25
        inc a
l_8c25:
        call &465e
        ld a,&40
        call &55a6
        ret nz
        ld a,d
        and &07
        jr z,l_8c38
        add a,&30
        ld (&41e4),a
l_8c38:
        ld l,e
        sla l
        dec l
        ld a,(ix+14)
        add a,l
        add a,&40
        ld (&41e5),a
        ld hl,&41e0
        ld de,&4137
        ld bc,&0017
        ldir
        xor a
        ld (&780c),a
        ld (&414c),a
        call &47c7
        ld hl,&7eea
        ld bc,&0016
        ld a,(&4136)
        cp &05
        jr z,l_8c70
        call &4797
        ld hl,&4c86
        ld bc,&0021
l_8c70:
        ld de,&78ef
        ldir
        ld de,(&41ef)
        ld a,&04
        out (&fb),a
        ld hl,&8000
        call &4888
        jp &49be
        jr nz,&8ca8
        jr nz,l_8caa
        jr nz,&8cac
        jr nz,&8cae
        jr nz,l_8cb0
        jr nz,&8c91
        rst &38
        rst &38
        rst &38
        rst &38
        ld l,(hl)
        nop
        add a,b
        nop
        nop
        dec de
        rst &38
        rst &38
        rst &38
        rst &38
        rst &38
        rst &38
        rst &38
        rst &38
        rst &38
        rst &38
        rst &38
        call &4301
l_8caa:
        call &6012
        call z,&42e6
l_8cb0:
        jr z,l_8cc2
        call &42a1
        jr nz,l_8cc2
        ld de,&411e
        xor a
        ld b,&10
        call &4b46
        jr l_8cc5
l_8cc2:
        call &5324
l_8cc5:
        call &42b9
        call &4653
        call &5c97
        call &45d5
        jr z,l_8d09
        call &4452
        call &4e09
        call &4dc7
        call &5558
        call &5caa
        ld d,h
        ld e,l
        inc de
        ld bc,&01ff
        ld (hl),&00
        ldir
        ld de,&0001
l_8cef:
        call &43f0
        call &4998
        jr nz,l_8cef
        inc d
        call &49b2
        cp d
        jr z,l_8d07
        and &7f
        cp d
        jr nz,l_8cef
        ld d,&80
        jr l_8cef
l_8d07:
        jr l_8d63
l_8d09:
        call &5caa
        ld a,&80
        call &4488
        ei
        and &0e
        jr nz,l_8d24
        call &4e09
        ld d,&0a
l_8d1b:
        call &4622
        dec d
        jr nz,l_8d1b
        call &45d5
l_8d24:
        push de
        call &4dc7
        call &5984
        ld h,c
        ld (hl),h
        jr nz,&8da3
        ld (hl),d
        ld h,c
        ld h,e
        ld l,e
        ld a,(&d1a0)
l_8d36:
        push de
        ld a,&1a
        call &5c44
        ld l,(hl)
        ld e,d
        ld l,d
        ld h,&00
        ld a,&20
        call &5950
        pop de
l_8d47:
        call &4e21
        ld a,(&40b8)
        bit 7,d
        set 7,d
        jr z,l_8d47
        inc d
        cp d
        jr z,l_8d63
        res 7,d
        call &4622
        dec e
        jr nz,l_8d36
        ld e,&0a
        jr l_8d36
l_8d63:
        call &5a1d
        call &4ddf
        push de
        ex de,hl
        ld hl,&411e
        res 7,(hl)
        ld c,&0a
        ldir
        ld hl,&000c
        add hl,de
        ex de,hl
        ld hl,&4ddb
        ld c,&04
        ldir
        ld hl,&000e
        add hl,de
        ex de,hl
        ld hl,&4128
        ld c,&06
        ldir
        pop de
        call &43f0
        ld a,(&780b)
        dec a
        ret z
        ld hl,(&40d3)
        dec hl
        ld de,&0020
        call &616b
        push hl
        ex de,hl
        inc hl
        call &6136
        pop hl
        ld bc,&0010
        call &6156
        push hl
        call &62f7
        call &6369
        pop bc
        add hl,bc
        ex de,hl
        ld hl,&411e
        ld bc,&0010
        ldir
        call &62f7
        call &630f
        jp &610f
        call &5981
        ld b,(hl)
        ld l,a
        ld (hl),d
        ld l,l
        ld h,c
        ld (hl),h
        jr nz,&8df8
        jr nz,l_8e4a
        ld h,l
        ld (hl),d
        ld l,c
        ld h,(hl)
        ld a,c
        and b
        ret
        ld b,d
        ld b,h
        ld c,a
        ld d,e
        call &45d5
        call &5c97
        call &4452
        push de
        push hl
        ld bc,&00e8
        add hl,bc
        ld de,&4ddb
        ld b,&04
l_8df3:
        ld a,(de)
        cp (hl)
        inc de
        inc hl
        jr nz,l_8dfb
        djnz l_8df3
l_8dfb:
        pop hl
        pop de
        ex af,af'
        ld bc,&00d2
        add hl,bc
        ex af,af'
        scf
        ret nz
        ld a,(hl)
        and &80
        ret
        call &5c82
        ret nz
        call &5984
        ld b,(hl)
        ld l,a
        ld (hl),d
        ld l,l
        ld h,c
        ld (hl),h
        jr nz,&8dba
        call &556f
        call &5a79
        ret z
        pop bc
        ret
        di
        bit 7,d
        ld a,&e0
        jr z,l_8e2a
        ld a,&e4
l_8e2a:
        ld c,a
        ld (&45ed),a
        ld (&4eb2),a
        ld (&4ec1),a
        add a,&03
        ld (&4ebe),a
        ld (&4ee1),a
        ld a,&f0
        call &4624
        ld bc,&3c4e
        call &4ec0
        ld hl,&0a0a
l_8e4a:
        ld bc,&0c00
        call &4ec0
        ld bc,&03f5
        call &4ec0
        ld c,&fe
        call &4eb1
        ld c,d
        res 7,c
        call &4eb1
        xor d
        rlca
        ld c,a
        call &4eb1
        ld c,e
        inc e
        inc b
        call &4eb1
        cp h
        jr nz,l_8e71
        ld e,b
l_8e71:
        ld c,&02
        call &4eb1
        ld c,&f7
        call &4eb1
        ld bc,&164e
        call &4ec0
        ld bc,&0c00
        call &4ec0
        ld bc,&03f5
        call &4ec0
        ld c,&fb
        call &4eb1
        ld c,b
        call &4ec0
        call &4ec0
        ld c,&f7
        call &4eb1
        ld bc,&184e
        call &4ec0
        dec l
        jr nz,l_8e4a
        call &4ec0
        call &4ec0
        call &4ec0
        ret
l_8eb1:
        in a,(&e0)
        bit 1,a
        jr nz,l_8ebc
        rra
        jr c,l_8eb1
        jr l_8ec9
l_8ebc:
        ld a,c
        out (&e3),a
        ret
l_8ec0:
        in a,(&e0)
        bit 1,a
        jr nz,l_8edf
        rra
        jr c,l_8ec0
l_8ec9:
        pop bc
        call &444b
        and &0e
        jp nz,&4e21
        ld b,&0a
l_8ed4:
        push bc
        call &4452
        call &4998
        pop bc
        djnz l_8ed4
        ret
l_8edf:
        ld a,c
        out (&e3),a
        djnz l_8ec0
        ret
        call &6012
        jr nz,l_8ef3
        ld hl,&4137
        ld (hl),&2a
        call &42e6
        ret nz
l_8ef3:
        jp &5366
        call &4301
        call &4ee5
        ld c,&8e
        call &430a
        call &53aa
        call &4ee5
        call &53aa
        ld c,&3f
        call &430d
l_8f0f:
        call z,&5c7b
        call &42b9
        call &5c97
        call &5c82
        jr z,l_8f1e
        xor a
l_8f1e:
        call &5c44
        cp c
        ld e,e
        call &5f06
        call &53aa
        call &5f06
        ld hl,&4137
        ld de,&416b
        ld bc,&000e
        ldir
        call &50a2
        ldir
        call &5059
        ld (&4fc6),a
        ld a,c
        ld (&507d),a
        call &508f
l_8f49:
        call &53cd
        jp nc,&5123
        call &5cb1
        ld a,(hl)
        and &1f
        cp &15
        jr z,l_8f49
        call &5c90
        call nz,&5a48
        jr nz,l_8f49
        call &5981
        ld c,h
        ld l,a
        ld h,c
        ld h,h
        ld l,c
        ld l,(hl)
        ld h,a
        jr nz,l_8f0f
        call &558c
        call &59b2
        call &5cb1
        ld de,&4179
        ld bc,&000b
        ldir
        ld b,&04
        call &4b44
        ld c,&d1
        add hl,bc
        ld c,&21
        ldir
        ld bc,&ff10
        add hl,bc
        ld d,(hl)
        inc hl
        ld e,(hl)
        call &4452
        ld a,(&4179)
        cp &10
        ld de,&0009
        jr nc,l_8fb0
        cp &05
        inc hl
        ld a,(hl)
        inc hl
        ld h,(hl)
        ld l,a
        jr nz,l_8faa
        ld hl,&c000
l_8faa:
        add hl,de
        call &4b38
        jr l_8fbe
l_8fb0:
        ld hl,(&419c)
        add hl,de
        ld a,(&419b)
        bit 6,h
        jr z,l_8fbe
        res 6,h
        inc a
l_8fbe:
        ex de,hl
        ld hl,&780c
        res 5,(hl)
        ex de,hl
        ld c,&00
        cp c
        jr c,l_8fd8
        sub c
        ld (&5041),a
        ld (&5043),hl
        ex de,hl
        set 5,(hl)
        ld a,c
        ld hl,&0000
l_8fd8:
        ld (&5084),a
        ld (&5089),hl
        call &507c
        call &46c4
        call &508f
        call &59df
        ld hl,&780c
        bit 3,(hl)
        jr nz,l_902d
        res 6,(hl)
        set 3,(hl)
        call &50af
        ld hl,&40dd
        set 1,(hl)
        call &47c7
        jr c,l_904b
        ld a,(&4136)
        cp &10
        jr nc,l_9019
        call &507c
        ex de,hl
        push ix
        pop hl
        ld bc,&00e6
        add hl,bc
        ex de,hl
        ld c,&09
        ldir
l_9019:
        call &5981
        ld d,e
        ld h,c
        halt
        ld l,c
        ld l,(hl)
        ld h,a
        jr nz,&8fc6
        ld hl,&4137
        call &5593
        call &59b2
l_902d:
        call &507c
        call &4888
        ld hl,&780c
        bit 5,(hl)
        jr z,l_9048
        call &508f
        call &59b6
        ld a,&00
        ld hl,&0000
        jp &4fbe
l_9048:
        call &49be
l_904b:
        ld hl,&780c
        ld a,(hl)
        and &b6
        inc a
        ld (hl),a
        call &59b6
        jp &4f46
        xor a
        out (&fb),a
        ld hl,l_911e
        ld b,a
l_9060:
        xor a
l_9061:
        dec l
        jr z,l_9076
        cp (hl)
        jr nz,l_9061
        ld e,a
l_9068:
        dec l
        inc e
        cp (hl)
        jr z,l_9068
        inc l
        ld a,b
        cp e
        jr nc,l_9060
        ld b,e
        ld c,l
        jr l_9060
l_9076:
        or b
        ret nz
        call &5aaa
        ld bc,&033e
        out (&fb),a
        ld (&411b),a
        ld a,&00
        ld (&414c),a
        ld de,&0000
        ld hl,&8000
        ret
        call &53aa
        call &465b
        call &50a2
        ld a,(de)
        ldi
        dec hl
        ld (hl),a
        inc hl
        jp pe,&5098
        ret
        call &4779
        ld hl,&780d
        ld de,&bc00
        ld bc,&0306
        ret
        ld hl,&4179
        ld de,&4136
        ld bc,&000f
        ldir
        ld hl,&416b
        ld de,&4137
        ld b,&0a
l_90c2:
        ld a,(hl)
        cp &2a
        jr z,l_90d1
        cp &3f
        jr z,l_90cc
        ld (de),a
l_90cc:
        inc hl
        inc de
        djnz l_90c2
        ret
l_90d1:
        inc hl
        ld a,(hl)
        cp &2e
        ret nz
l_90d6:
        ld a,(de)
        cp &2e
        jr z,l_90cc
        inc de
        djnz l_90d6
        ret
        call &4301
        call &5366
        ld c,&3f
        call &430d
        call z,&5c7b
        call &42b9
        call &5f03
l_90f3:
        call &53e1
        jr nc,l_9123
        call &5c90
        call nz,&5a3c
        jr nz,l_90f3
        call &5c82
        jr nz,l_9112
        call &5cb1
        ld a,(hl)
        bit 6,a
        jr z,l_9112
        call &5a89
        jr l_90f3
l_9112:
        call &5cb1
        ld (hl),&00
        ld de,(&4113)
        call &43f0
l_911e:
        call &5c5f
        jr l_90f3
l_9123:
        call &5c59
        bit 0,(hl)
        pop hl
        ret nz
        call &5aaa
        ld l,e
        call &5ce0
        call &465b
        call &51af
        jp nz,&512a
        ld (hl),&00
        jp &43f0
        call &6012
        call z,&42e6
        jr z,l_915a
        ld c,&8e
        call &430d
        jr nz,l_915a
        call &5324
        call &42b9
        call &4653
        jp &4d66
l_915a:
        call &5366
        ld c,&8e
        call &430a
        call &53aa
        call &5361
        call &42b9
        ld hl,&414e
        ld de,&4132
        ld bc,&0004
        ldir
        call &4399
        call &4653
        call &51af
        jr nz,l_9193
        ld hl,&4137
        ld de,&4153
        ld b,&0e
l_9189:
        ld a,(de)
        xor (hl)
        and &df
        jr nz,l_91ab
        inc hl
        inc de
        djnz l_9189
l_9193:
        call &53aa
        call &51af
        jp nz,&512a
        inc hl
        push de
        ld de,&4153
        ex de,hl
        ld bc,&000a
        ldir
        pop de
        jp &43f0
l_91ab:
        call &5aaa
        ld l,l
        ld a,&10
        call &55a6
        jp &5cb1
        ex af,af'
        ld a,&40
        jr l_91bf
        ex af,af'
        ld a,&c0
l_91bf:
        ld (&4131),a
        ex af,af'
        ld c,&89
        call &430d
        call z,&5c66
        call &6012
        jr z,l_91fd
        call &5366
        call &42b9
        call &5f03
l_91d9:
        call &53e1
        jp nc,&5123
        ld (ix+13),&00
        call &5cb5
        ld a,(&4131)
        ld c,a
        cpl
        ld b,a
        ld a,(hl)
        and b
        call &5c82
        jr nz,l_91f4
        or c
l_91f4:
        ld (hl),a
        call &43f0
        call &5c5f
        jr l_91d9
l_91fd:
        ld hl,&4131
        bit 7,(hl)
        jp nz,&42e2
        call &42b9
        call &4653
        ret z
        call &4ddf
        call &5c82
        res 7,(hl)
        jr nz,l_9218
        set 7,(hl)
l_9218:
        push af
        xor a
        ld (&40d2),a
        call &43f0
        pop af
        ret nz
        ld a,&01
        ld (&40d2),a
        ret
        push hl
        call &5c97
        call &42aa
        pop hl
        jr nz,l_9245
l_9232:
        ld a,(hl)
        cp &0e
        jr nz,&923f
        ld bc,&0006
        call &0103
        ld h,e
        ld bc,&237e
        cp &0d
        jr nz,l_9232
l_9245:
        call &5339
        push af
        ld a,c
        ld (&4133),a
        pop af
        call &42b9
        call &4653
        call &4a3c
        ld a,(&41a9)
        cp &14
        jr nz,l_9293
        call &5c90
        jr z,l_9293
        ld de,(&7802)
        call &4452
        in a,(&fa)
        ld (&4108),a
        in a,(&fb)
        ld (&4109),a
        in a,(&fc)
        ld (&410a),a
        ld a,&04
        out (&fb),a
        out (&fc),a
        ld sp,&7eea
        ld hl,&8000
        ld de,&4000
        ld a,&02
        ld (&414c),a
        call &46c4
        jp &4b6e
l_9293:
        cp &10
        jr nz,l_92ee
        call &5c90
        jp nz,&4b19
        call &5c07
        and b
        ld e,d
        push bc
        pop hl
        call &5c1e
        sbc a,a
        ld e,d
        ld (&4198),a
        ld (&4199),hl
        ex de,hl
        ld c,a
        push bc
        call &5c07
        sub h
        ld e,d
        push bc
        pop hl
        call &5c1e
        sub e
        ld e,d
        pop bc
        dec hl
        bit 7,h
        jr nz,l_92c5
        dec a
l_92c5:
        push bc
        push de
        call &52f9
        push af
        ex de,hl
        ld a,c
        call &52f9
        ex de,hl
        ld c,a
        pop af
        and a
        sbc hl,de
        sbc a,c
        pop de
        pop bc
        rl h
        rla
        rl h
        rla
        rr h
        scf
        rr h
        ld (&419b),a
        ld (&419c),hl
        xor a
        ld (&4188),a
l_92ee:
        call &5d54
        call &5d40
        ld e,&01
        jp &42c5
        rlc h
        rlc h
        rra
        rr h
        rra
        rr h
        and &07
        ret
        call &0103
        ld e,&01
        call &42aa
        ret z
        jr c,l_933d
l_9311:
        push af
        ld hl,&ffef
        call &5391
        ld de,&411e
        push de
        ld b,&11
        call &4b44
        pop de
        jr l_9383
        call &0103
        dec de
        ld bc,&aacd
        ld b,d
        jr nz,l_9311
        ret
        call &5339
        push af
        ld a,c
        ld (&4132),a
        pop af
        ret
        call &5345
        ret z
l_933d:
        push af
        call &0103
        ld hl,&f101
        ret
        call &0103
        jr &934b
        jp &42aa
        call &5345
        ret z
        push af
        call &0103
        adc a,h
        ccf
        set 7,h
        and a
        jp z,&5eb6
        dec a
        ld c,a
        pop af
        ret
        ld hl,&fff5
        jr l_9369
        ld hl,&fff1
l_9369:
        push hl
        call &0103
        dec de
        ld bc,&aacd
        ld b,d
        pop hl
        ret z
        push af
        call &5391
        ld de,&4136
        ld b,&0f
        call &4b44
        ld de,&4137
l_9383:
        in a,(&fb)
        ex af,af'
        and &1f
        out (&fb),a
        ldir
        ex af,af'
        out (&fb),a
        pop af
        ret
        push hl
        call &0103
        inc h
        ld bc,&7908
        or b
        jr z,l_93a0
        pop hl
        add hl,bc
        ex de,hl
        ret nc
l_93a0:
        call &5aaa
        ld (de),a
        call &53aa
        call &5366
        push af
        push bc
        push de
        push hl
        ld de,&4132
        ld hl,&414e
        ld bc,&001c
        call &5098
        ld hl,(&40d3)
        ld de,(&40d5)
        ld (&40d3),de
        ld (&40d5),hl
        pop hl
        pop de
        pop bc
        pop af
        ret
        ld hl,&780c
        bit 2,(hl)
        jr z,l_93e8
        ld de,(&4113)
        ld a,(&4112)
        and a
        call z,&4452
        jr l_9413
        ld hl,&780c
        bit 2,(hl)
        jr nz,l_9413
l_93e8:
        set 2,(hl)
        ld ix,&7800
        xor a
        ld (ix+4),a
        call &45d5
l_93f5:
        call &4452
        ld (&4113),de
l_93fc:
        call &5cb1
        ld a,(ix+14)
        ld (&4112),a
        ld a,(hl)
        and a
        jr z,l_9410
        call &56d3
        jr nz,l_9413
        scf
        ret
l_9410:
        inc hl
        or (hl)
        ret z
l_9413:
        ld a,(&4112)
        ld (ix+14),a
        dec a
        jr z,l_9424
        call &5ca1
        inc (ix+14)
        jr l_93fc
l_9424:
        ld de,(&4113)
        call &4998
        jr nz,l_93f5
        inc d
        ld a,d
        cp &04
        ret nc
        jr l_93f5
        call &5c97
        ld a,&2a
        ld (&4137),a
        ld a,&02
        ld (&4134),a
        ret
        call &5434
        call &42a1
        jr z,l_9463
        call &5471
        call z,&42de
        call &6012
        call nz,&532f
        call &42e6
        call z,&5361
        ld c,&21
        call &430d
        jr nz,l_948d
l_9463:
        call &42b9
        call &465b
        ld a,&02
        jr l_9495
l_946d:
        call &5aaa
        dec d
        ld c,&23
        call &430d
        ret nz
        call &5339
        ret z
        push af
        ld a,c
        cp &10
        jr nc,l_946d
        ld (&4134),a
        pop af
        cp a
        ret
        push af
        call &5434
        jr l_9496
l_948d:
        call &42b9
        call &465b
        ld a,&04
l_9495:
        push af
l_9496:
        call &5a27
        call &5802
        call &5558
        call &5984
        ld a,(&afa0)
        ld h,a
        ld l,a
        ld (&4110),a
        ld (&410d),hl
        pop af
        call &55a6
        bit 1,(ix+4)
        jr z,l_94be
        ld a,(&4111)
        and a
        call nz,&57cc
l_94be:
        call &57cc
        ld hl,(&4110)
        xor a
        ld h,a
        push hl
        call &5950
        call &5984
        jr nz,l_9515
        ld l,c
        ld l,h
        push hl
        pop hl
        call &41f7
        call &59a3
        ex de,hl
        xor a
        ld h,a
        ld l,&50
        sbc hl,de
        push hl
        call &5950
        call &5984
        jr nz,&954f
        ld (hl),d
        ld h,l
        ld h,l
        jr nz,l_9561
        ld l,h
        ld l,a
        call p,&cde1
        rst &30
        ld b,c
        call &5537
        call nz,&57cc
        call z,&59a3
        ld hl,(&410d)
        push hl
        call &5547
        call &5984
        jr nz,l_9555
        ld h,d
        jr nz,l_9582
        ld (hl),e
        ld h,l
        ld h,h
        inc l
        and b
        call &49b2
l_9515:
        sub &04
        ld d,a
        ld e,&01
        call &6197
        pop de
        xor a
        sbc hl,de
        ld a,&3f
        call c,&59aa
        call nc,&5547
        call &5984
        jr nz,&9579
        ld h,d
        jr nz,&9597
        ld (hl),d
        ld h,l
        ld h,l
        ld l,&8d
        ret
        ld a,(&4134)
        cp &02
        jr z,l_9540
        xor a
        ret
l_9540:
        in a,(&fc)
        and &60
        cp &40
        ret
        srl h
        rr l
        push af
        xor a
        call &5944
        pop af
        ret nc
        call &5984
l_9555:
        ld l,&b5
        ret
        call &5984
        ld d,d
        ld h,l
        ld h,e
        ld l,a
        ld (hl),d
        ld h,h
l_9561:
        and b
        ld hl,(&780b)
        dec l
        ld h,l
        jr z,l_956c
        ld hl,(&40d3)
l_956c:
        jp &5939
        call &5caa
        call &4de8
        ld a,(hl)
        jr c,l_9584
        call &5587
        and a
        ret z
        ld c,&1e
        add hl,bc
        ld b,&06
l_9582:
        jr l_9595
l_9584:
        cp &2a
        ret z
        and &7f
        ret z
        jr l_9593
        ld (ix+13),&01
        call &5cb5
l_9593:
        ld b,&0a
l_9595:
        ld a,(hl)
        and &7f
        cp &21
        jr nc,l_959f
        ld a,(&40bc)
l_959f:
        call &59aa
        inc hl
        djnz l_9595
        ret
        ld ix,&7800
        ld (ix+4),a
        xor a
        ld (&4111),a
        call &45d5
        call &4504
        ld a,e
        dec a
        or d
        jr nz,l_95c9
        ld a,(ix+4)
        and &06
        jr z,l_95c9
        call &556f
        call &5849
l_95c9:
        call &5cb1
        ld a,(hl)
        and a
        jp z,&56a5
        bit 0,(ix+4)
        jr z,l_95e3
        call &56b3
        ld b,a
        ld a,(&4133)
        cp b
        ret z
        jp &5686
l_95e3:
        bit 1,(ix+4)
        jr nz,l_95f0
        bit 2,(ix+4)
        jp z,&5676
l_95f0:
        ld (ix+13),&0b
        call &5cb5
        ld b,(hl)
        inc hl
        ld c,(hl)
        ld (&7800),bc
        ld hl,(&410d)
        add hl,bc
        ld (&410d),hl
        ld hl,&4110
        inc (hl)
        bit 7,a
        jp nz,&5686
        call &56d3
        jp nz,&5686
        bit 1,(ix+4)
        jr nz,l_963a
        call &5cb1
        ld a,(hl)
        bit 6,a
        jr z,l_9627
        call &5984
        inc d
        add a,c
l_9627:
        call &56b3
        push de
        ld h,&00
        ld l,a
        ld a,&20
        call &5950
        pop de
        call &5984
        inc d
        nop
        and b
l_963a:
        call &558c
        bit 1,(ix+4)
        jr z,l_9660
        ld b,&03
        call &5537
        jr nz,l_964d
        sla b
        dec b
l_964d:
        ld a,(&4111)
        inc a
        cp b
        jr nz,l_9655
        xor a
l_9655:
        ld (&4111),a
        call nz,&59a8
        call z,&57cc
        jr l_9686
l_9660:
        push de
        ld hl,(&7800)
        ld a,&20
        call &594a
        call &59a8
        call &5cb1
        ld a,(hl)
        call &5715
        pop de
        jr l_9686
        bit 3,(ix+4)
        jr nz,l_9682
        bit 4,(ix+4)
        jr z,l_9686
l_9682:
        call &56d3
        ret z
l_9686:
        ld a,(ix+14)
        cp &01
        jr z,l_9696
        call &5ca1
        inc (ix+14)
        jp &55c9
l_9696:
        call &4998
        jp nz,&55b4
        inc d
        ld a,d
        cp &04
        jp nz,&55b4
        and a
        ret
        ld a,(ix+4)
        cpl
        bit 6,a
        ret z
        inc hl
        ld a,(hl)
        and a
        jr nz,l_9686
        inc a
        ret
        push de
        pop bc
        xor a
        dec b
        jp m,&56c0
        add a,&0a
        dec b
        jp p,&56ba
        ld b,a
        sla b
        sla c
        dec c
        ld a,(ix+14)
        add a,c
        add a,b
        ret
        push ix
        push de
        pop ix
        jr l_96e4
        push ix
        call &5cb1
        ld b,&0b
        bit 3,(ix+4)
        ld ix,&4136
        jr z,l_96f4
l_96e4:
        ld a,(ix+0)
        cp &2a
        jr z,l_96fd
        cp &3f
        jr z,l_96f4
        xor (hl)
        and &df
        jr nz,l_96fa
l_96f4:
        inc ix
        inc hl
        djnz l_96e4
l_96f9:
        xor a
l_96fa:
        pop ix
        ret
l_96fd:
        inc ix
        inc hl
        djnz l_9704
        jr l_96f9
l_9704:
        ld a,(ix+0)
        cp &2e
        jr nz,l_96f9
l_970b:
        ld a,(hl)
        cp &2e
        jr z,l_96f4
        inc hl
        djnz l_970b
        jr l_96fa
        and &1f
        push af
        ld hl,&586f
        ld bc,&00a3
        cpir
l_9720:
        ld a,(hl)
        cp &20
        jr c,l_972b
        call &59aa
        inc hl
        jr l_9720
l_972b:
        pop af
        cp &01
        jr nz,l_9736
        ld (ix+13),&d9
        jr l_973e
l_9736:
        cp &10
        jr nz,l_9750
        ld (ix+13),&f2
l_973e:
        call &5cb5
        ld a,(hl)
        and &c0
        jr nz,l_97ae
        inc hl
        ld e,(hl)
        inc hl
        ld d,(hl)
        ex de,hl
        call &5939
        jr l_97ae
l_9750:
        cp &13
        jr nz,l_978d
        ld (ix+13),&ec
        call &5cb5
        call &5863
        inc c
        res 5,c
        ex de,hl
        push de
        xor a
        call &5918
        ld a,&2c
        call &59aa
        pop hl
        call &5863
        ex de,hl
        push de
        xor a
        call &5918
        pop hl
        ld a,(hl)
        inc a
        jr z,l_97ae
        call &5537
        jr nz,l_97ae
        ld a,&2c
        call &59aa
        call &5863
        ex de,hl
        xor a
        call &5918
l_978d:
        cp &04
        jr nz,l_97ae
        ld (ix+13),&d7
        call &5cb5
        ld d,(hl)
        dec hl
        ld e,(hl)
        ex de,hl
        push de
        call &5939
        ld a,&2c
        call &59aa
        pop hl
        dec hl
        ld d,(hl)
        dec hl
        ld e,(hl)
        ex de,hl
        call &5939
l_97ae:
        call &5537
        jr nz,l_97cc
        call &5984
        rla
        jr z,&9739
        ld (ix+13),&f5
        call &5cb5
        ld a,(&40dd)
        rra
        jr nc,l_97cc
        call &584f
        call c,&57d1
l_97cc:
        ld a,&0d
        jp &59aa
        call &57f6
        ld a,&2f
        call &59aa
        call &57f6
        push hl
        ld l,(hl)
        ld h,&00
        ld bc,&076c
        add hl,bc
        ld a,&2f
        call &593a
        call &59a8
        pop hl
        inc hl
        call &57f6
        ld a,&3a
        call &59aa
        push hl
        ld l,(hl)
        ld h,&00
        ld a,&30
        call &5950
        pop hl
        inc hl
        ret
        call &66c9
        ld a,(&4132)
        dec a
        jr nz,l_9816
        call &5984
        ld b,(hl)
        ld l,h
        ld l,a
        ld (hl),b
        ld (hl),b
        ld sp,hl
        jr l_9830
l_9816:
        ld hl,&40d9
        bit 4,(hl)
        jr nz,l_9828
        call &5984
        ld c,l
        ld h,c
        ld (hl),e
        ld (hl),h
        ld h,l
        jp p,&0818
l_9828:
        call &5984
        ld d,e
        ld l,h
        ld h,c
        halt
        push hl
l_9830:
        call &5984
        jr nz,&9879
        ld l,c
        ld (hl),d
        ld l,&17
        dec c
        adc a,l
        ld hl,&40de
        call &584f
        jr nc,l_9849
        call &57d1
        call &57f1
l_9849:
        call &5984
        dec c
        adc a,l
        ret
        ld a,(hl)
        dec a
        cp &1f
        ret nc
        inc hl
        ld a,(hl)
        dec a
        cp &0c
        ret nc
        inc hl
        ld a,(hl)
        dec hl
        dec hl
        inc a
        cp &51
        ccf
        ret
        ld a,(hl)
        and &1f
        ld c,a
        inc hl
        ld e,(hl)
        inc hl
        ld d,(hl)
        res 7,d
        inc hl
        ret
        ld bc,&585a
        jr nz,l_98b6
        ld b,c
        ld d,e
        ld c,c
        ld b,e
        jr nz,l_988a
        ld b,d
        ld b,c
        ld d,e
        ld c,c
        ld b,e
        jr nz,l_9883
        ld e,d
        ld e,b
l_9883:
        jr nz,l_98c9
        ld l,&41
        ld d,d
        ld d,d
        ld b,c
l_988a:
        ld e,c
        ld de,&2e44
        ld b,c
        ld d,d
        ld d,d
        ld b,c
        ld e,c
        inc bc
        ld e,d
        ld e,b
        jr nz,&98bc
        ld l,&41
        ld d,d
        ld d,d
        ld b,c
        ld e,c
        ld (de),a
        inc h
        ld l,&41
        ld d,d
        ld d,d
        ld b,c
        ld e,c
        inc b
        ld e,d
        ld e,b
        jr nz,l_98be
        ld b,e
        jr nz,l_98b3
        ld e,d
        ld e,b
        jr nz,l_9905
        ld c,(hl)
l_98b3:
        ld d,b
        jr nz,l_98ea
l_98b6:
        jr c,l_9923
        ld b,&4d
        ld b,h
        ld l,&46
        ld c,c
l_98be:
        ld c,h
        ld b,l
        rlca
        ld e,d
        ld e,b
        jr nz,l_9918
        ld b,e
        ld d,d
        ld b,l
        ld b,l
l_98c9:
        ld c,(hl)
        inc h
        inc d
        ld d,e
        ld b,e
        ld d,d
        ld b,l
        ld b,l
        ld c,(hl)
        inc h
        ex af,af'
        ld d,e
        ld d,b
        ld b,l
        ld b,e
        ld c,c
        ld b,c
        ld c,h
        add hl,bc
        ld e,d
        ld e,b
        jr nz,&9933
        ld c,(hl)
        ld d,b
        jr nz,l_9915
        ld (&6b38),a
        ld a,(bc)
        ld c,a
        ld d,b
l_98ea:
        ld b,l
        ld c,(hl)
        ld d,h
        ld e,c
        ld d,b
        ld b,l
        dec bc
        ld c,(hl)
        cpl
        ld b,c
        jr nz,&993b
        ld e,b
        ld b,l
        ld b,e
        ld d,l
        ld d,h
        ld b,l
        dec d
        ld c,l
        ld b,h
        ld c,a
        ld d,e
        jr nz,l_9947
        ld c,c
        ld d,d
l_9905:
        ld d,&44
        ld b,l
        ld b,(hl)
        ld b,l
        ld b,e
        ld d,h
        jr nz,&995a
        ld c,c
        ld d,e
        ld d,h
        inc c
        ld d,a
        ld c,b
        ld b,c
l_9915:
        ld d,h
        ccf
        nop
l_9918:
        ex af,af'
        xor a
        ld de,&0000
        rr c
        rr d
        rr c
l_9923:
        rr d
        ld a,d
        add a,h
        ld h,a
        ld a,c
        adc a,e
        ld b,a
        ld de,l_86a0
        ld c,&01
        ex af,af'
        call &595e
        jr l_993c
        ld a,&20
        cp &af
        ld b,&00
l_993c:
        ld c,&00
        ld de,&2710
        call &595e
        ld de,&03e8
l_9947:
        call &595b
        ld de,&0064
        call &595b
        ld de,&000a
        call &595b
        ld a,l
        add a,&30
        jr l_99aa
        ld bc,&0000
        push af
        ld a,b
        ld b,&00
        and a
l_9963:
        sbc hl,de
        sbc a,c
        jr c,l_996b
        inc b
        jr l_9963
l_996b:
        add hl,de
        adc a,c
        ld c,a
        ld a,b
        ld b,c
        and a
        jr nz,l_9978
        pop de
        add a,d
        ret z
        jr l_99aa
l_9978:
        add a,&30
        call &59aa
        pop de
        ld a,&30
        ret
        call &5a1d
l_9984:
        pop hl
l_9985:
        ld a,(hl)
        inc hl
        rlca
        srl a
        call &59aa
        jr nc,l_9985
        jp (hl)
        call &599e
        jr nc,l_9984
        pop hl
l_9996:
        ld a,(hl)
        inc hl
        rlca
        srl a
        jr nc,l_9996
        jp (hl)
        ld a,(&40dd)
        add a,a
        ret
        ld a,&2c
        call &59aa
        ld a,&20
l_99aa:
        push af
        call &0103
        djnz l_99b0
l_99b0:
        pop af
        ret
        ld a,&22
        jr l_99aa
        call &5a9f
        ret nz
        call &5981
        dec c
        ld b,l
        ld l,(hl)
        ld (hl),h
        ld h,l
        ld (hl),d
        jr nz,&9a38
        ld l,a
        ld (hl),l
        ld (hl),d
        ld h,e
        ld h,l
        jr nz,&9a30
        ld l,c
        ld (hl),e
        ld l,e
        jr nz,l_9a41
        ld (hl),d
        ld h,l
        ld (hl),e
        ld (hl),e
        jr nz,&9a38
        ld l,(hl)
        ld a,c
        jr nz,l_9a46
        ld h,l
        ld sp,hl
        jr l_9a05
        call &5a9f
        ret nz
        call &5981
        ld b,l
        ld l,(hl)
l_99e8:
        ld (hl),h
        ld h,l
        ld (hl),d
        jr nz,l_9a61
        ld h,c
        ld (hl),d
        ld h,a
        ld h,l
        ld (hl),h
        jr nz,&9a58
        ld l,c
        ld (hl),e
        ld l,e
        jr nz,&9a69
        ld (hl),d
        ld h,l
        ld (hl),e
        ld (hl),e
        jr nz,l_9a60
        ld l,(hl)
        ld a,c
        jr nz,l_9a6e
        ld h,l
        ld sp,hl
l_9a05:
        call &0103
        ld l,c
        ld bc,&f930
        push af
        call &0103
        ld l,c
        ld bc,&f938
        call &5a1d
        pop af
        and &df
        cp &59
        ret
        push ix
        call &0103
        ld d,c
l_9a23:
        ld bc,&e1dd
        ret
        ld a,(&4134)
        cp &02
        jr nz,l_9a36
        xor a
        call &0103
        ld c,(hl)
        ld bc,&023e
l_9a36:
        call &0103
        ld (de),a
        ld bc,&cdc9
        add a,c
        ld e,c
        ld b,l
        ld (hl),d
l_9a41:
        ld h,c
        ld (hl),e
        ld h,l
        jr nz,l_99e8
l_9a46:
        jr l_9a51
        call &5981
        ld b,e
        ld l,a
        ld (hl),b
        ld a,c
        jr nz,&99f3
l_9a51:
        call &558c
        call &5984
        ld (&2820),hl
        ld e,c
        cpl
        ld c,(hl)
        cpl
        ld b,e
        cpl
l_9a60:
        ld b,l
l_9a61:
        add hl,hl
        jr nz,l_9a23
        call &5a05
        ret z
        cp &43
        jr z,l_9a73
        cp &45
l_9a6e:
        ret nz
        pop bc
        jp &5123
l_9a73:
        ld hl,&780c
        res 7,(hl)
        ret
        call &5984
        ld (&2820),hl
        ld e,c
        cpl
        ld c,(hl)
        xor c
        call &5a89
        jp &5a05
        push hl
        push de
        push bc
        push ix
        ld hl,&036a
        ld de,&0085
        call &0103
        ld l,a
        ld bc,&e1dd
        pop bc
        pop de
        pop hl
        ret
        ld a,(&4132)
        ld b,a
        ld a,(&414e)
        cp b
        ret nz
        dec a
        ret
        call &436c
        call &42d4
        ld hl,(&4104)
        ld a,h
        or l
        jr z,l_9ab9
        ld sp,hl
        ret
l_9ab9:
        ld hl,&5b2d
        push hl
        ld a,d
        call &5af0
        ld hl,&5b35
        ld a,e
        call &5af0
        pop hl
        push hl
        ld de,&5b53
        ld bc,&000b
        ldir
        pop hl
        ld de,&5b64
        ld c,&0b
        ldir
        call &5c07
        sub a
        ld e,d
        call &5c2d
        and e
        ld e,d
        xor a
        ld (&780c),a
        ld e,a
        pop hl
        ld a,(hl)
        ld sp,(&4106)
        ret
        ex af,af'
        scf
        ld bc,&0064
        call &5b02
        ld bc,&000a
        call &5b02
        ex af,af'
        ld b,a
        jr l_9b10
        ex af,af'
l_9b03:
        inc b
        sub c
        jr nc,l_9b03
        add a,c
        ex af,af'
        dec b
        jr nz,l_9b10
        ld a,&20
        jr c,l_9b13
l_9b10:
        ld a,&30
        add a,b
l_9b13:
        ld (hl),a
        inc hl
        ret
        nop
        ld (hl),d
        ld h,l
        ld h,e
        ld l,a
        ld (hl),d
        call po,&6552
        ld h,e
        ld l,a
        ld (hl),d
        ld h,h
        ld de,&6f66
        ld (hl),l
        ld l,(hl)
        call po,&7254
        ld l,e
        ld l,&2a
        ld hl,(&2c2a)
        ld (hl),e
        ld h,e
        ld (hl),h
        ld l,&2a
        ld hl,(&2c2a)
        ld de,&6f66
        ld (hl),l
        ld l,(hl)
        call po,&7345
        ld h,e
        ld h,c
        ld (hl),b
        ld h,l
        jr nz,l_9bb9
        ld h,l
        ld (hl),c
        ld (hl),l
        ld h,l
        ld (hl),e
        ld (hl),h
        ld h,l
        call po,&7254
        ld l,e
        ld l,&2a
        ld hl,(&2c2a)
        ld (hl),e
        ld h,e
        ld (hl),h
        ld l,&2a
        ld hl,(&2c2a)
        add a,a
        ld d,h
        ld (hl),d
        ld l,e
        ld l,&2a
        ld hl,(&2c2a)
        ld (hl),e
        ld h,e
        ld (hl),h
        ld l,&2a
        ld hl,(&2c2a)
        jr nz,l_9bde
        ld l,a
        ld (hl),e
        call p,&bfbf
        cp a
        cp a
        cp a
        cp a
        ld d,(hl)
        ld h,l
        ld (hl),d
        ld l,c
        ld h,(hl)
        ld a,c
        add a,a
        ld d,a
        ld (hl),d
        ld l,a
        ld l,(hl)
        ld h,a
        jr nz,l_9ba0
        jr nz,l_9bff
        ld a,c
        ld (hl),b
        push hl
        cp a
        cp a
        cp a
        cp a
        cp a
        cp a
        ld c,(hl)
        ld l,a
        jr nz,l_9bd9
        ld d,l
        ld d,h
        ld c,a
        ld hl,(l_9720)
        cp a
        dec bc
l_9ba0:
        ld (hl),e
        ld (hl),l
        ld h,e
        ld l,b
        jr nz,&9c0a
        ld (hl),d
        ld l,c
        halt
        push hl
        ld b,h
        ld l,c
        ld (hl),e
        ld l,e
        jr nz,l_9c19
        ld (hl),e
        jr nz,l_9c23
        ld (hl),d
        ld l,a
        ld (hl),h
        ld h,l
        ld h,e
        ld (hl),h
l_9bb9:
        ld h,l
        call po,&6f4e
        ld (hl),h
        jr nz,&9c25
        ld l,(hl)
        ld l,a
        ld (hl),l
        ld h,a
        ld l,b
        jr nz,l_9c3a
        ld (hl),b
        ld h,c
        ld h,e
        ld h,l
        jr nz,&9c3c
        ld l,(hl)
        jr nz,l_9c34
        ld l,c
        ld (hl),e
        ex de,hl
        ld b,h
        ld l,c
        ld (hl),d
        ld h,l
        ld h,e
        inc e
l_9bd9:
        ld (hl),d
        ld a,c
        jr nz,l_9c43
        ld (hl),l
l_9bde:
        ld l,h
        call pe,&6946
        ld l,h
        ld h,l
        ld de,&6f66
        ld (hl),l
        ld l,(hl)
        call po,&6e45
        ld h,h
        ld b,&97
        ld b,(hl)
        ld l,c
        ld l,h
        ld h,l
        ld (de),a
        jr nz,l_9c6b
        ld (hl),e
        ld h,l
        call po,&f73e
        in a,(&f9)
        and &20
l_9bff:
        ret nz
        dec a
        out (&f5),a
        call &5aaa
        ld d,h
        ex (sp),hl
        push de
        call &5c53
        push de
        call &0103
        xor h
        nop
        ld c,a
        inc hl
        call &0103
        xor h
        nop
l_9c19:
        ld b,a
        pop hl
        pop de
        ex (sp),hl
        ret
        ex (sp),hl
        push de
        call &5c53
l_9c23:
        push de
        call &0103
        xor h
        nop
        pop hl
        pop de
        ex (sp),hl
        ret
        ex (sp),hl
        push de
        call &5c53
        push de
        ld a,c
l_9c34:
        call &0103
        dec c
        nop
        inc hl
l_9c3a:
        ld a,b
        call &0103
        dec c
        nop
        pop hl
        pop de
        ex (sp),hl
l_9c43:
        ret
        ex (sp),hl
        push de
        call &5c53
        push de
        call &0103
        dec c
        nop
        pop hl
        pop de
        ex (sp),hl
        ret
        ld e,(hl)
        inc hl
        ld d,(hl)
        inc hl
        ex de,hl
        ret
        ex (sp),hl
        push hl
        ld hl,&780c
        ret
        call &5c59
        set 0,(hl)
        pop hl
        ret
        call &5c59
        set 1,(hl)
l_9c6b:
        pop hl
        ret
        call &5c59
        set 4,(hl)
        pop hl
        ret
        call &5c59
        set 6,(hl)
        pop hl
        ret
        call &5c59
        set 7,(hl)
        pop hl
        ret
        call &5c59
        bit 1,(hl)
        pop hl
        ret
        call &5c59
        bit 4,(hl)
        pop hl
        ret
        call &5c59
        bit 7,(hl)
        pop hl
        ret
        ld ix,&7800
        ld hl,&7913
        ld (&780f),hl
        ld (ix+13),&00
        ld (ix+14),&00
        ret
        ld l,(ix+15)
        ld h,(ix+16)
        ret
        ld (ix+13),&00
        call &5caa
        ld b,(ix+14)
        ld c,(ix+13)
        add hl,bc
        ret
        inc (ix+13)
        ret nz
        inc (ix+14)
        ret
        ld d,(ix+18)
        ld e,(ix+17)
        ret
        ld (ix+18),d
        ld (ix+17),e
        ret
        call &5cc8
        ld (ix+18),h
        ld (ix+17),l
        ret
        push bc
        push de
        push hl
        ld hl,(&410b)
        ld b,&30
        ld de,&4179
l_9ceb:
        call &0103
        xor h
        nop
        ld (de),a
        inc hl
        inc de
        djnz l_9ceb
        pop hl
        pop de
        pop bc
        call &437f
        ld hl,&417a
        call &5f0f
        ld a,(&4179)
        ld (&4136),a
        ld (&4145),a
        ld a,(&4198)
        ld (&414d),a
        ld hl,(&4199)
        ld (&4148),hl
        ld a,(&419b)
        and &1f
        ld (&414c),a
        ld hl,(&419c)
        res 7,h
        ld (&419c),hl
        ld (&4146),hl
        ret
        call &5ce0
        call &465b
        call &5c97
        call &4a3c
        ld de,(&41cc)
        set 7,d
        ld (&41cc),de
        ld l,&50
        ld de,&41a9
l_9d45:
        ld h,&4b
        ld b,&30
l_9d49:
        ld a,(de)
        call &0103
        dec c
        nop
        inc hl
        inc de
        djnz l_9d49
        ret
        ld l,&00
        ld de,&4179
        jr l_9d45
        call &5c97
        ld de,(&7802)
        call &4452
        call &5e23
        ld hl,(&41da)
        ld (&4148),hl
        ld bc,(&41de)
        ld a,c
        ld (&414c),a
        ld de,(&41dc)
        res 7,d
        ld (&4146),de
        ret
        call &5ce0
        call &465b
        in a,(&fb)
        ld (&411d),a
        and &e0
        ld b,a
        ld a,(&4198)
        and &1f
        or b
        out (&fb),a
        call &5c97
        call &47c7
        jr c,l_9daf
        call &4797
        ld hl,(&4148)
        ld de,(&4146)
        call &4888
        call &49be
l_9daf:
        ld a,(&411d)
        out (&fb),a
        ret
        push hl
        pop ix
        call &0103
        ld hl,&2101
        or a
        ld b,b
        add hl,bc
        push hl
        ld bc,&40de
        sbc hl,bc
        call z,&66c9
        pop hl
        call &5c1e
        jp nz,&3c5b
        add hl,hl
        add hl,hl
        ld b,&96
l_9dd5:
        dec b
        add hl,hl
        rla
        bit 7,a
        jr z,l_9dd5
        res 7,a
        ld e,a
        ld a,b
        ld d,h
        ld c,l
        ld b,&00
        call &0103
        daa
        ld bc,&3ec9
        sub l
        call &5c44
        ld (hl),h
        ld e,e
        ld hl,&40e5
        ld de,&4133
        ld bc,&001b
        ldir
        call &4389
        call &465b
        call &5c97
        ld a,&10
        call &55a6
        jr nz,l_9e12
        call &4a4c
        jp &5257
l_9e12:
        call &5aaa
        ld h,l
        call &5ce0
        call &4a3c
        ld de,(&7802)
        call &4452
        ld b,&09
l_9e25:
        call &46a1
        djnz l_9e25
        ret
        call &5eba
        ld hl,&43f0
        jr l_9e68
        call &5eba
        ld hl,&4452
        jr l_9e68
        call &5eba
        ld hl,&446d
        jr l_9e68
        ld hl,&43f0
        jr l_9e4b
        ld hl,&4452
l_9e4b:
        push hl
        ld hl,(&41da)
        ld a,h
        and &c0
        jr z,l_9eb6
        sub &40
        rlca
        rlca
        ld (&41de),a
        ld a,h
        and &3f
        ld (&41db),a
        ld hl,&0001
        ld (&410b),hl
        pop hl
l_9e68:
        push hl
        ld a,(&41d9)
        call &465e
        call &5c97
        in a,(&fb)
        ld (&411b),a
        ld bc,(&410b)
        ld a,b
        or c
        jr z,l_9eb6
        ld de,(&41dc)
        ld hl,(&41da)
        set 7,h
        ld a,(&41de)
        out (&fb),a
l_9e8d:
        ld (&780f),hl
        pop hl
        push hl
        push bc
        call &0005
        inc h
        inc h
        call &4998
        jr nz,l_9ea9
        inc d
        bit 6,h
        jr z,l_9ea9
        res 6,h
        in a,(&fb)
        inc a
        out (&fb),a
l_9ea9:
        pop bc
        dec bc
        ld a,b
        or c
        jr nz,l_9e8d
        pop bc
        ld a,(&411b)
        out (&fb),a
        ret
l_9eb6:
        call &5aaa
        ld e,&cd
        sub a
        ld e,h
        ld c,&87
        call &430a
        call &532f
        call &42de
        call &5339
        push hl
        call &42de
        call &5339
        pop bc
        ld h,c
        push hl
        call &42de
        call &534d
        push bc
        push hl
        call &42e6
        ld hl,&0001
        jr nz,l_9ee8
        call &5339
l_9ee8:
        push hl
        call &42b9
        pop hl
        ld (&410b),hl
        pop hl
        ld (&41da),hl
        pop hl
        ld (&41de),hl
        pop hl
        ld (&41dc),hl
        ld a,(&4132)
        ld (&41d9),a
        ret
        call &4389
        ld hl,&4137
        call &5f0f
        jp &4653
        ld (&7805),hl
        ld a,(hl)
        and &df
        ld c,a
        inc hl
        ld a,(hl)
        cp &3a
        jr z,l_9f41
        sub &30
        cp &0a
        jr nc,l_9f48
        ld d,a
        inc hl
        ld a,(hl)
        cp &3a
        jr z,l_9f3d
        sub &30
        cp &0a
        jr nc,l_9f48
        ld e,a
        ld a,d
        add a,a
        add a,a
        add a,d
        add a,a
        add a,e
        ld d,a
        inc hl
        ld a,(hl)
        cp &3a
        jr nz,l_9f48
l_9f3d:
        ld a,d
        ld (&4132),a
l_9f41:
        ld a,c
        ld (&4135),a
        inc hl
        jr l_9f4b
l_9f48:
        ld hl,(&7805)
l_9f4b:
        ld bc,&000a
        ld de,&4137
        ldir
        ld b,&04
        call &4b44
        ld a,(&4135)
        cp &44
        ret z
        call &5aaa
        inc d
        ld b,&0b
        ld de,&4137
l_9f67:
        call &42a1
        jr z,l_9f76
        ld (de),a
        inc de
        call &430f
        djnz l_9f67
        jp &42e2
l_9f76:
        call &42b9
        inc b
        inc b
        inc b
        call &4b44
        ld hl,(&40d7)
        ld (&40d3),hl
        scf
        call &6030
        call &5c97
        call &51af
        jp nz,&512a
        ld a,(hl)
        and &1f
        cp &13
        jp nz,&4b19
        ld (hl),a
        push hl
        ld bc,&00ec
        add hl,bc
        call &5fc7
        ld c,&06
        add hl,bc
        dec (hl)
        call &5fc7
        inc (hl)
        pop hl
        call &4a63
        ld a,&db
        call &436e
        ld a,&80
        out (&fe),a
        ld a,&95
        call &5c44
        ld (hl),h
        ld e,e
        ld hl,&7fff
        set 6,(hl)
        jp &52ee
        ld a,(hl)
        and &1f
        dec a
        cp &02
        jp nc,&4b19
        ld c,a
        in a,(&fc)
        and &1f
        add a,c
        ld (hl),a
        ret
        ld hl,(&41da)
        cp &01
        jr c,l_9fee
        ld b,&10
        ld de,&411e
l_9fe4:
        call &0103
        xor h
        nop
        ld (de),a
        inc hl
        inc de
        djnz l_9fe4
l_9fee:
        call &6030
        jr l_9fff
        call &42ee
        jp z,&6067
        call &602c
        call &42b9
l_9fff:
        ld a,(&4132)
        cp &02
        jr nz,l_a00c
        ld hl,(&40d3)
        ld (&40d0),hl
l_a00c:
        call &5c44
        rlca
        ld e,d
        ret
        push af
        call &4389
        pop af
        ld c,&ef
        call &430d
        ret nz
        call &42ee
        jr nz,l_a02c
        ld hl,&4132
        ld (hl),&02
        ret
l_a028:
        call &5aaa
        ld d,d
l_a02c:
        call &5306
        ret z
        push af
        call nc,&6098
        jr nc,l_a028
        ld a,h
        or l
        jr nz,l_a043
        inc a
        ld (&4132),a
        call &4653
        jr l_a060
l_a043:
        call &4673
        ex de,hl
        ld hl,(&40ce)
        sbc hl,de
        ex de,hl
        jr c,l_a063
        ld (&40d3),hl
        call &6022
        call &4653
        call &4ddf
        jr c,l_a063
        ld (&40d2),a
l_a060:
        pop af
        cp a
        ret
l_a063:
        call &5aaa
        ld d,c
        ld hl,&411e
        ld (hl),&2a
        ld hl,&4134
        ld (hl),&02
        call &5471
        call &42e6
        call z,&5324
        call &42b9
        call &4673
        call &5a27
        call &5984
        ld d,d
        ld h,l
        ld h,e
        ld l,a
        ld (hl),d
        ld h,h
        jr nz,l_a0fc
        ld h,c
        ld l,l
        ld h,l
        ld (hl),e
        ld a,(&8d0d)
        ld a,&14
        cp &af
        call &4673
        ld (&60bf),a
        call &5c97
        ld hl,&0001
        ld de,(&40ce)
l_a0a9:
        xor a
        push hl
        push de
        call &6136
        call &62f7
        call &6369
        pop de
        ld c,&20
l_a0b8:
        push de
        ld de,&411e
        ld b,&10
        jr l_a0c0
l_a0c0:
        ld a,(de)
        xor (hl)
        and &5f
        jr nz,l_a0fa
        inc de
        inc hl
        djnz l_a0c0
        pop de
        pop hl
        ld hl,(&40ce)
        sbc hl,de
        inc hl
        scf
        ret
        ld a,(hl)
        and &7f
        jr z,l_a0fa
        push hl
        call &56cc
        pop hl
        ld b,&10
        jr nz,l_a0fa
        pop de
        push de
        push bc
        push hl
        call &60cc
        call &5936
        call &5984
        jr nz,l_a12b
        and b
        pop hl
        pop bc
        call &5595
        call &57cc
l_a0fa:
        pop de
        ld a,l
l_a0fc:
        add a,b
        ld l,a
        jr nc,l_a101
        inc h
l_a101:
        dec de
        ld a,d
        or e
        jr z,l_a10d
        dec c
        jr nz,l_a0b8
        pop hl
        inc hl
        jr l_a0a9
l_a10d:
        pop hl
        ret
        ld de,(&40d3)
        ld hl,(&40ce)
        scf
        dec de
        sbc hl,de
        jp c,&6063
        ld a,&d0
        jr nz,l_a124
        ld a,(&40bd)
l_a124:
        ld (&40b9),a
        ex de,hl
        ld bc,&0640
l_a12b:
        call &6156
        ld a,c
        ld bc,(&40cc)
        add hl,bc
        adc a,&00
        ld c,&00
        ld de,(&40c7)
        call &616d
        ld (&40c3),de
        ld de,(&40c0)
        ld d,c
        dec e
        call &616d
        ld a,e
        ld (&40c1),a
        ld a,l
        inc a
        ld (&40bf),a
        ret
        ex de,hl
        ld a,b
        ld b,&10
        ld hl,&0000
l_a15d:
        add hl,hl
        rl c
        rla
        jr nc,l_a167
        add hl,de
        jr nc,l_a167
        inc c
l_a167:
        djnz l_a15d
        ld b,a
        ret
        xor a
        ld c,a
        push hl
        ld hl,&0000
        exx
        pop hl
        ld c,a
        xor a
        ld b,&18
l_a177:
        adc hl,hl
        rl c
        exx
        adc hl,hl
        adc a,a
        sbc hl,de
        sbc a,c
        jr nc,l_a186
        add hl,de
        adc a,c
l_a186:
        ccf
        exx
        djnz l_a177
        adc hl,hl
        rl c
        ex de,hl
        exx
        push hl
        exx
        pop hl
        ret
        ld d,a
        ld e,&01
        ld a,d
        add a,a
        jr nc,l_a19d
        add a,&a0
l_a19d:
        ld l,a
        rla
        and &01
        ld h,a
        ld a,e
        dec a
        add a,l
        ld c,a
        ld a,h
        adc a,&00
        ld b,a
        add hl,hl
        add hl,hl
        add hl,bc
        ret
        ld c,&f0
        call &430a
        call &42b9
        ld hl,(&40ce)
        ld a,h
        or l
        jp z,&467c
        ld a,&02
        call &600c
        call &4399
        call &610f
        jp &6237
        ld c,&89
        call &430d
        jr nz,l_a1f7
        call &42a1
        jr z,l_a1f0
        ld b,&e2
l_a1da:
        push bc
        call &5339
        push hl
        call &42b9
        pop hl
        call &624d
        ld a,&f2
        out (&f5),a
        ld a,l
        out (&f7),a
        pop af
        jr l_a221
l_a1f0:
        call &42b9
        ld a,&e0
        jr l_a221
l_a1f7:
        ld c,&de
        call &430d
        jr nz,l_a20c
        call &42a1
        ld b,&e3
        jr nz,l_a1da
        call &42b9
        ld a,&e1
        jr l_a221
l_a20c:
        ld c,&b1
        call &430a
        call &42b9
        call &621f
        xor a
        ld (&40b9),a
        inc a
        jp &600c
        ld a,&e6
l_a221:
        call &4673
        ex af,af'
        call &624d
        ld a,&f7
        out (&f5),a
        ex af,af'
        out (&f7),a
        call &624d
l_a232:
        ld a,&ff
        out (&f5),a
        ret
        ld a,&ee
        out (&f5),a
        out (&f7),a
        ld a,&fa
        out (&f7),a
        jr l_a232
l_a243:
        call &624d
        or &16
        cp &b6
        ret z
        jr l_a243
        ld a,&f7
        out (&f5),a
l_a251:
        call &5bf9
        in a,(&f6)
        in a,(&f7)
        add a,a
        jr c,l_a251
        ret
        ld a,&f7
        out (&f5),a
l_a260:
        in a,(&f6)
        in a,(&f7)
        and &09
        jr z,l_a260
        rra
        jr c,l_a273
        ld a,&f0
        out (&f5),a
        ld bc,&fef7
        ret
l_a273:
        call &6237
        jp &4568
l_a279:
        call &5aaa
        ld d,e
        ld a,d
        add a,a
        cp &9f
        jr nc,l_a279
        ld a,e
        and a
        jr z,l_a279
        cp &0b
        jr nc,l_a279
        push de
        push hl
        call &6197
        ld bc,(&40c7)
        xor a
l_a295:
        inc a
        sbc hl,bc
        jr nc,l_a295
        add hl,bc
        dec a
        ld d,a
        ld bc,(&40c0)
        dec c
        xor a
        ld b,a
l_a2a4:
        inc a
        sbc hl,bc
        jr nc,l_a2a4
        add hl,bc
        dec a
        ld e,a
        ld a,l
        ld hl,(&40bf)
        add a,l
        cp h
        jr c,l_a2b7
        dec h
        sub h
        inc e
l_a2b7:
        ex af,af'
        ld a,e
        ld hl,(&40c1)
        add a,l
        cp h
        jr c,l_a2c2
        sub h
        inc d
l_a2c2:
        call &6308
        ld b,&00
        ld c,d
        ld hl,(&40c3)
        add hl,bc
l_a2cc:
        call &624d
        ld bc,&01f7
        ld a,&f2
        out (&f5),a
        out (c),b
        inc a
        out (&f5),a
        ex af,af'
        out (c),a
        ex af,af'
        inc a
        out (&f5),a
        out (c),l
        inc a
        out (&f5),a
        out (c),h
        inc a
        out (&f5),a
        out (c),e
        ld a,&ff
        out (&f5),a
        pop hl
        pop de
        jp &4630
        push de
        push hl
        ld hl,(&40c3)
        ld a,(&40c1)
        call &6308
        ld a,(&40bf)
        ex af,af'
        jr l_a2cc
        ld e,a
        ld a,(&40d9)
        or e
        ld e,a
        ret
        call &5caa
        call &6345
        dec c
        outi
        inc c
        outi
        call &624d
        jr l_a375
        ld hl,(&7805)
        call &6345
        ld a,(&411c)
        out (&fb),a
        ex de,hl
        ld hl,(&4119)
        dec c
        outi
        inc c
        outi
        ld a,(&411b)
        out (&fb),a
        call &624d
        ld a,(&411c)
        out (&fb),a
        jp &491d
        ld a,(&40d2)
        and a
        jp nz,&444e
        ld a,&30
        call &6224
        call &625c
l_a354:
        dec c
        outi
        inc c
        outi
        dec c
        outi
        inc c
        outi
        dec c
        outi
        inc c
        outi
        jr nz,l_a354
        ret
        call &5caa
        call &6393
        dec c
        ini
        inc c
        ini
l_a375:
        call &5ca1
        jp &5caa
        call &5c89
        ld hl,(&7805)
        jr nz,l_a3b0
        call &6393
        ex de,hl
        call &5caa
        dec c
        ini
        inc c
        ini
        jp &4731
        ld a,&20
        call &6224
        call &625c
l_a39b:
        dec c
        ini
        inc c
        ini
        dec c
        ini
        inc c
        ini
        dec c
        ini
        inc c
        ini
        jr nz,l_a39b
        ret
l_a3b0:
        call &63d2
        ex de,hl
        call &5caa
        ld c,&f6
        ini
        inc c
        ini
        call &44c0
        jp &4731
        call &63d2
        ld c,&02
        call &63df
        call &6375
        jp &44c0
        ld a,&20
        call &6224
        call &625c
        ld bc,&01fe
        xor a
        ex af,af'
l_a3df:
        in a,(&f6)
        cpi
        jr z,l_a3e6
        ex af,af'
l_a3e6:
        in a,(&f7)
        cpi
        jr z,l_a3ed
        ex af,af'
l_a3ed:
        ld a,b
        or c
        jr nz,l_a3df
        ret
        call &5caa
        ld a,&20
        call &6224
        call &625c
        exx
        ld l,&ff
        exx
        ld b,&00
l_a403:
        in a,(&f6)
        ld (hl),a
        inc hl
        exx
        inc l
        jr nz,l_a411
        ld h,&77
        and a
        jr nz,l_a411
        ld h,a
l_a411:
        or (hl)
        ld (hl),a
        exx
        in a,(&f7)
        ld (hl),a
        inc hl
        exx
        inc l
        or (hl)
        ld (hl),a
        exx
        djnz l_a403
        jp &6375
        in a,(&fb)
        push af
        call &599e
        jr c,l_a476
        call &5a34
        call &5984
        ld d,&01
        dec bc
        ld b,d
        dec l
        ld b,h
        ld c,a
        ld d,e
        jr nz,&a490
        ld h,l
        ld (hl),d
        ld (hl),e
        ld l,c
        ld l,a
        ld l,(hl)
        jr nz,l_a473
        ld l,&35
        ld h,c
        jr nz,&a478
        add hl,sp
        add hl,sp
        scf
        cpl
        ld sp,&3939
        jr c,l_a470
        ld h,d
        ld a,c
        jr nz,l_a499
        ld h,h
        ld (hl),a
        ld l,c
        ld l,(hl)
        jr nz,l_a49c
        ld l,h
        ld l,c
        ld l,(hl)
        ld l,e
        ld d,&03
        sub d
        in a,(&fc)
        and &1f
        out (&fb),a
        ld hl,l_8300
        ld b,&80
        call &66b9
        ld b,l
l_a470:
        ld hl,&8900
l_a473:
        call &66b9
l_a476:
        ld bc,&b0ef
        ld d,&0f
        in e,(c)
l_a47d:
        out (c),d
        in a,(c)
        and &0f
        cp d
        jr nz,l_a489
        dec d
        jr l_a47d
l_a489:
        out (c),e
        inc d
        jr z,l_a4a7
        ld de,&003f
        call &6708
        ex af,af'
l_a495:
        ld a,d
        call &66ff
l_a499:
        call &6708
l_a49c:
        cp d
        jr nz,l_a4a2
        dec d
        jr nz,l_a495
l_a4a2:
        ex af,af'
        call &66ff
        ex af,af'
l_a4a7:
        ld hl,&66cd
        jr z,l_a4b5
        ld (hl),&4e
        call &5990
        ld c,(hl)
        rst &28
        jr &a4d0
l_a4b5:
        dec a
        jr z,l_a4c5
        ld (hl),&4f
        call &5990
        ld d,e
        ld b,c
        ld c,l
        ld b,d
        ld d,l
        out (&18),a
        dec bc
l_a4c5:
        ld (hl),&00
        call &5990
        ld b,h
        ld b,c
        ld c,h
        ld c,h
        ld b,c
        out (&cd),a
        sub b
        ld e,c
        jr nz,l_a538
        ld l,h
        ld l,a
        ld h,e
        ld l,e
        jr nz,l_a53f
        ld h,l
        ld (hl),h
        ld h,l
        ld h,e
        ld (hl),h
        ld h,l
        ld h,h
        ld d,&05
        sub d
        ld a,&f6
        out (&f5),a
        ld a,(&40d9)
        out (&f7),a
        ld a,&ef
        out (&f5),a
        ld b,&00
l_a4f4:
        ld c,&ff
l_a4f6:
        in a,(&f6)
        in a,(&f7)
        cpl
        and &03
        jr nz,l_a51d
        djnz l_a4f4
        call &5990
        ld c,(hl)
        ld l,a
        jr nz,&a570
        ld h,c
        ld (hl),d
        ld h,h
        jr nz,&a571
        ld l,c
        ld (hl),e
        ld l,e
        jr nz,&a576
        ld h,l
        ld (hl),h
        ld h,l
        ld h,e
        ld (hl),h
        ld h,l
        call po,&d3f1
        ei
        ret
l_a51d:
        dec c
        jr nz,l_a4f6
        call &5990
        ld d,a
        ld h,c
        ld l,c
        ld (hl),h
        ld l,c
        ld l,(hl)
        ld h,a
        jr nz,l_a592
        ld l,a
        ld (hl),d
        jr nz,l_a598
        ld h,c
        ld (hl),d
        ld h,h
        jr nz,l_a599
        ld l,c
        ld (hl),e
        ld l,e
l_a538:
        jr nz,&a568
        ld l,&ae
l_a53c:
        call &6243
l_a53f:
        ld a,&ec
        out (&f7),a
        call &624d
        bit 1,a
        jr nz,l_a53c
        bit 4,a
        jr z,l_a53c
        call &625c
        ld hl,&780f
        ld b,&00
l_a556:
        dec c
        ini
        inc c
        ini
        jr nz,l_a556
        call &599e
        jr c,l_a5af
        ld hl,&a311
        ld bc,&5e14
        call &66a7
        ld hl,&b52f
        ld bc,&221d
        call &66a7
        ld hl,&cba9
        ld bc,&300b
        call &66a7
        call &5984
        ld d,&08
        add hl,bc
        ld c,l
        ld l,a
        ld h,h
        ld h,l
        ld l,h
        and b
        ld hl,&7845
        ld b,&28
        call &5595
l_a592:
        call &5984
        ld d,&09
        add hl,bc
l_a598:
        ld d,d
l_a599:
        ld h,l
        halt
        ld l,c
        ld (hl),e
        ld l,c
        ld l,a
        ld l,(hl)
        and b
        ld hl,&783d
        ld b,&08
        call &5595
        call &5984
        ld d,&0c
        sbc a,b
l_a5af:
        ld hl,(&7811)
        ld a,h
        ld h,l
        ld l,a
        ld (&40c5),hl
        push hl
        call &599e
        jr c,l_a5d1
        call &5936
        call &5984
        jr nz,l_a609
        ld a,c
        ld l,h
        ld l,c
        ld l,(hl)
        ld h,h
        ld h,l
        ld (hl),d
        ld (hl),e
        ld d,&0d
        sbc a,b
l_a5d1:
        ld a,(&7816)
        ld (&40c2),a
        ld h,&00
        ld l,a
        push hl
        call &599e
        jr c,l_a5ef
        call &5936
        call &5984
        jr nz,l_a630
        ld h,l
        ld h,c
        ld h,h
        ld (hl),e
        ld d,&0e
        sbc a,b
l_a5ef:
        ld a,(&781c)
        ld h,&00
        ld l,a
        inc a
        ld (&40c0),a
        push hl
        call &599e
        jr c,l_a610
        call &5936
        call &5984
        jr nz,&a65a
        ld h,l
        ld h,e
l_a609:
        ld (hl),h
        ld l,a
        ld (hl),d
        ld (hl),e
        ld d,&11
        sub l
l_a610:
        pop bc
        pop hl
        call &6156
        ld (&40c7),hl
        pop bc
        call &6156
        ld a,c
        ld (&40cb),a
        ld (&40c9),hl
        push af
        push hl
        ld c,b
        ld de,&0640
        call &616d
        ex de,hl
        ld de,&0020
l_a630:
        add hl,de
        call &616d
        inc de
        ld (&40cc),de
        pop hl
        pop af
        and a
        sbc hl,de
        sbc a,c
        ld de,&0640
        call &616d
        push de
        ld de,&000a
        call &616d
        ld a,e
        pop de
        cp &05
        jr c,l_a65b
        inc de
        cp &50
        jr c,l_a65d
        add a,&30
        jr l_a65d
l_a65b:
        ld a,&d0
l_a65d:
        ld (&40bd),a
        ld (&40ce),de
        call &599e
        jr c,l_a682
        ex de,hl
        call &5939
        call &5984
        jr nz,l_a6c4
        ld h,l
        ld h,e
        ld l,a
        ld (hl),d
        ld h,h
        ld (hl),e
        jr nz,l_a6db
        halt
        ld h,c
        ld l,c
        ld l,h
        ld h,c
        ld h,d
        ld l,h
        push hl
l_a682:
        pop af
        out (&fb),a
        call &4399
        call &4669
        ld hl,&668b
        push hl
        ld (&4104),sp
        call &4ddf
        pop hl
        ld hl,&0000
        ld (&4104),hl
        jr nc,l_a6a3
        ld (&40d0),hl
        ret
l_a6a3:
        ld (&40d2),a
        ret
        push bc
        push hl
        call &66b9
        dec hl
        ld a,&05
        call &66c0
        pop hl
        ld a,&50
        call &66c0
        pop bc
        ld a,&55
l_a6bb:
        ld (hl),a
        inc hl
        djnz l_a6bb
        ret
        ld b,c
        ld de,&0080
l_a6c4:
        add hl,de
        ld (hl),a
        djnz l_a6c4
        ret
l_a6c9:
        ld hl,&40de
        jr l_a71d
        call &66f8
        ld e,&07
l_a6d3:
        call &6708
        call &6711
        inc e
        ld a,e
l_a6db:
        cp &0a
        jr nz,l_a6d3
        call &6768
        ld e,&04
        call &6708
        call &6711
        dec e
        dec e
        jp p,&66e4
        ld e,&0b
        call &6708
        res 7,a
        jr l_a6ff
        ld e,&0b
        call &6708
        set 7,a
l_a6ff:
        ld bc,&feef
        out (c),e
        inc b
        out (c),a
        ret
        ld bc,&feef
        out (c),e
        inc b
        in a,(c)
        ret
        ld d,a
        and &f0
        rra
        ld b,a
        rra
        rra
        sub b
        add a,d
        ld (hl),a
        inc hl
        ret
l_a71d:
        call &6733
        push hl
        ld hl,&4002
        call &6733
        pop de
        ld b,&06
l_a72a:
        dec hl
        dec de
        ld a,(de)
        cp (hl)
        jr nz,l_a6c9
        djnz l_a72a
        ret
        ld bc,&70ef
        call &6752
        ld b,&90
        call &6752
        ld b,&b0
        call &6752
        call &6768
        ld b,&50
l_a748:
        call &6752
        ld a,b
        sub &10
        ld b,a
        jr nc,l_a748
        ret
        in a,(c)
        and &0f
        add a,a
        ld e,a
        add a,a
        add a,a
        add a,e
        ld e,a
        ld a,b
        sub &10
        ld b,a
        in a,(c)
        and &0f
        add a,e
        ld (hl),a
        inc hl
        ret
        dec hl
        ld a,(hl)
        cp &50
        jr nc,l_a770
        add a,&64
l_a770:
        ld (hl),a
        inc hl
        ret
l_a773:
        xor a
        ld (&5b41),a
l_a777:
        ld a,(l_80dd)
        add a,a
        ld a,&02
        ld (&5a35),a
        call nc,l_a7a8
        rst &08
        add a,a
        xor a
        ld (&5a35),a
        ld a,(l_80dd)
        add a,a
        jr c,l_a7a6
        ld b,&96
l_a791:
        halt
        ld a,&7f
        in a,(&fe)
        and &02
        jr z,l_a79e
        djnz l_a791
        jr l_a7a6
l_a79e:
        ld a,&7f
        in a,(&fe)
        and &02
        jr z,l_a79e
l_a7a6:
        ld a,&03
l_a7a8:
        ld (&a7c6),sp
        ld bc,&c941
        push bc
        ld bc,&edc1
        push bc
        ld hl,&0000
        add hl,sp
        ld bc,l_a7c5
        push bc
        ld c,&fb
        in b,(c)
        push bc
        push hl
        jp &015a
l_a7c5:
        ld sp,&0000
        ret
        ld a,b
        ld (&f89e),a
        ld (&f89f),hl
        ret
        ld a,(&f89e)
        call &ea21
        defb &CD
