#!/usr/bin/env python3
"""Regenerate the byte-exact pyz80 source for B-DOS 1.5a from the freeware binary.

Provenance/bootstrap tool (NOT run by CI): disassembles reference/bdos/bdos15a.bin
(the freeware B-DOS 1.5a CODE file, base &8009), corrects objdump's unsigned
backward-jr/djnz rendering, fills objdump's collapsed-run ('...') gaps and
un-encodable data from the binary as DEFB, and symbolicates in-range targets.
The emitted reference/bdos/bdos15a.asm reassembles (pyz80) byte-identically to
the input -- which the `make bdos15a-bytematch` gate proves.

Usage: gen-bdos15a.py <bdos15a.bin> <out.asm>
"""
import re, subprocess, sys
BASE=0x8009
BIN, OUT = sys.argv[1], sys.argv[2]
oracle=open(BIN,'rb').read(); END=BASE+len(oracle)

# objdump + backward-jr fix
dis=subprocess.run(['z80-unknown-elf-objdump','-D','-b','binary','-m','z80',
                    '-M','zilog','--adjust-vma=0x%x'%BASE,BIN],
                   capture_output=True,text=True).stdout
jrpat=re.compile(r'^( +([0-9a-f]+):\t(?:18|10|20|28|30|38) ([0-9a-f]{2})\s+\t(?:jr|djnz)\s+(?:nz,|z,|nc,|c,)?)0x[0-9a-f]+(.*)$')
fixed=[]
for line in dis.splitlines():
    m=jrpat.match(line)
    if m:
        a=int(m.group(2),16); d=int(m.group(3),16); d-=0x100 if d>=0x80 else 0
        line=f"{m.group(1)}0x{a+2+d:04x}{m.group(4)}"
    fixed.append(line)

raw=[]
for ln in fixed:
    m=re.match(r'\s*([0-9a-f]+):\t([0-9a-f ]+?)\t(.*)',ln)
    if not m: continue
    a=int(m.group(1),16); bs=[int(x,16) for x in m.group(2).split()]
    mn=re.sub(r';.*$','',m.group(3)).strip(); mn=re.sub(r'0x([0-9a-fA-F]+)',r'&\1',mn)
    raw.append([a,bs,mn])

rows=[]; cur=BASE
defb=lambda a,n:[a,list(oracle[a-BASE:a-BASE+n]),None,True]
for a,bs,mn in raw:
    if a>cur: rows.append(defb(cur,a-cur))
    if a<cur: continue
    rows.append([a,bs,mn,False]); cur=a+len(bs)
if cur<END: rows.append(defb(cur,END-cur))
def oor(a,mn):
    m=re.match(r'(jr|djnz)\b.*?&([0-9a-fA-F]+)$',mn or '')
    return bool(m) and not(-128<=int(m.group(2),16)-(a+2)<=127)
for r in rows:
    if r[2] and oor(r[0],r[2]): r[3]=True

# convergence loop: DEFB any row that fails to assemble or mis-encodes
def build():
    starts={r[0] for r in rows}
    targets=set()
    for a,bs,mn,fd in rows:
        if fd or not mn: continue
        for h in re.findall(r'&([0-9a-fA-F]{3,4})\b',mn):
            v=int(h,16)
            if BASE<=v<END and v in starts: targets.add(v)
    labels={a:'l_%04x'%a for a in targets}
    out=['; B-DOS 1.5a - byte-exact pyz80 reconstruction of the freeware bdos15a.bin',
         '; Generated by reference/bdos/gen-bdos15a.py; proven by `make bdos15a-bytematch`.',
         '; Edwin Blink 1997/1998 (freeware). See reference/bdos/README.md.',
         '        org &%04X'%BASE]
    for a,bs,mn,fd in rows:
        if a in labels: out.append(labels[a]+':')
        if fd or not mn:
            out.append('        defb '+','.join('&%02X'%b for b in bs)); continue
        line=re.sub(r'&([0-9a-fA-F]{3,4})\b',lambda m:labels.get(int(m.group(1),16),'&'+m.group(1)),mn)
        out.append('        '+line)
    open(OUT,'w').write('\n'.join(out)+'\n')

for _ in range(600):
    build()
    p=subprocess.run(['pyz80','--obj='+OUT+'.bin','--nozip',OUT],capture_output=True,text=True)
    if p.returncode!=0:
        # Should not happen: we start from a valid objdump and only ever convert
        # rows to DEFB (which can't introduce a syntax error). Surface it if it does.
        raise SystemExit("asm error:\n"+(p.stdout+p.stderr)[-500:])
    if open(OUT+'.bin','rb').read()==oracle:
        print("BYTE-EXACT; rows=%d defb=%d"%(len(rows),sum(r[3] for r in rows))); break
    data=open(OUT+'.bin','rb').read()
    mi=next((i for i in range(min(len(data),len(oracle))) if data[i]!=oracle[i]),None)
    a=BASE+mi
    ri=next((i for i,r in enumerate(rows) if r[0]<=a<r[0]+len(r[1])),None)
    if ri is None or rows[ri][3]: raise SystemExit("stuck at %04x"%a)
    rows[ri][3]=True
else: raise SystemExit("no converge")
