package format

// Go↔Z80 mnemonic-ID sync guard (i7 phase C2).
//
// src/mnemonic_ids.inc carries a MNEM_<NAME> equate for every entry in this
// package's MnemonicTable (the slice index is the on-disk / dispatch mnemonic
// ID). It is GENERATED by tools/tables-gen (make tables); `make
// tables-sync-check` fails on any drift between the committed copy and a fresh
// regeneration. This test is the complementary EMITTER-FAITHFULNESS guard: it
// decodes the committed equates and asserts FULL parity with MnemonicTable —
// every entry present at its index, no extras, and the name-sanitisation
// (b.eq → MNEM_B_EQ) round-trips.
//
// Why both guards: the Z80 intercepts (src/intercepts.asm) dispatch on these
// IDs. A Go-side renumber that someone "fixed" by hand-editing the .inc would
// be caught by the regen diff; a generator that emitted a wrong ID would be
// caught here.

import (
	"strconv"
	"strings"
	"testing"
)

func TestMnemonicIDsZ80Sync(t *testing.T) {
	// parseEquates is shared with the constants sync test (same package).
	// Filter to the MNEM_ namespace.
	all := parseEquatesFrom(t, "mnemonic_ids.inc")
	got := map[string]int{}
	for name, v := range all {
		if strings.HasPrefix(name, "MNEM_") {
			got[name] = v
		}
	}

	// Every MnemonicTable entry must appear at its index under the sanitised
	// name; the names must be unique.
	want := map[string]int{}
	for id, mn := range MnemonicTable {
		sym := "MNEM_" + strings.ToUpper(strings.ReplaceAll(mn, ".", "_"))
		if prev, dup := want[sym]; dup {
			t.Fatalf("MnemonicTable: %q and (id %d) %q both sanitise to %s", "id "+strconv.Itoa(prev), id, mn, sym)
		}
		want[sym] = id
		v, ok := got[sym]
		if !ok {
			t.Errorf("%s (mnemonic %q, id %d): missing from mnemonic_ids.inc", sym, mn, id)
			continue
		}
		if v != id {
			t.Errorf("%s = %d; MnemonicTable index for %q = %d", sym, v, mn, id)
		}
	}

	// No extra MNEM_ equates beyond the table.
	for name := range got {
		if _, ok := want[name]; !ok {
			t.Errorf("%s: present in mnemonic_ids.inc but absent from MnemonicTable", name)
		}
	}
}
