; render_disk_probe.asm — the trinload-pushable probe that exercises the i365d-b1
; render-to-disk write path (render_disk_sink.asm) on real B-DOS 1.5t and proves
; the written file reads back through the REAL RST 8 hooks.
;
; THE JOB (Wall 1, docs/specs/i365-demo-architecture.md): stream a deterministic
; > free-RAM byte sequence into a Trinity SD record as a named MGT CODE file via
; raw CMD24 (render_disk_sink), then read it back through B-DOS HGTHD/HLOAD — the
; hardware proof that render_disk_sink produces a real, findable, loadable file.
;
;   come-up: CLS + banner, EEPROM "Trinity Network " -> MAC/IP, ENC init, CSD read
;            (csd_set_bd_records -> csd_base/csd_blocks — the raw-CMD24 LBA math).
;   '1' stream:  render_disk_sink_reset + N generated bytes + render_disk_sink_finish
;                (raw CMD24 body + directory writes into RDP_CFG_RECORD; the i295
;                band guard keeps every write inside that record).
;   '2' HRECORD (156): select the record (validates the "BDOS" +232 stamp that
;                render_disk_sink re-wrote).
;   '3' HGTHD (129): find "RELEASESRC", decode the DIFA size; assert == N.
;   '4' HLOAD (130): only when RDP_CFG_HLOAD is set AND N <= DST_MAX (HLOAD loads
;                the whole file resident; release.src's 417 KB cannot fit — that
;                size is proven by the HGTHD length check + the Go test's physical-
;                sector reconstruction). Regenerate the pattern, byte-compare.
;   '5' verdict: 'P' / 'F' + detail; serve '?'/'R'/'Q' (+ ARP/ICMP) like sd_push.
;
; The deterministic generator is byte[i] = (i * 0x9D) mod 256 (an 8-bit accumulator
; += 0x9D; 0x9D is odd, coprime to 256), regenerated identically by the Go test —
; a dropped/duplicated/swapped sector shifts the phase, detectable at that offset.
;
; VERIFICATION (CLAUDE.md rule 7): render_disk_write_faithful_test.go boots Colin's
; real ROM + B-DOS 1.5t + SPI SD, seeds a scratch record, patches RDP_CONFIG, runs
; this probe, and asserts verdict 'P' plus the pattern physically landed in the
; record band (Go reconstructs the file from the SD model). NOT the BDOSStore mock
; (i356). One build, flag-free of any NETBOOT_HOSTTEST carve-out (i231).

                org     &8000

                ; trinload's X packet does `out (HMPR),P; jp &8000`, landing here.
                jp      render_disk_probe_main

; ===========================================================================
; Composed includes — the wire driver, EEPROM reader, B-DOS seam (RST 8 hook
; bodies), the raw-CMD24 SD path, and the render disk sink. They come first so
; every symbol they define is resolved before the code below references it.
; ===========================================================================
                include "encdrv.asm"           ; drv_init / drv_read / drv_write
                include "eeprom.asm"           ; find_index / read_chunk + value/chunk/name/part/total
                include "bdos_seam.asm"        ; bdos_name_to_uifa / bdos_lookup_hook / bdos_difa_to_size / bdos_load_hook / bdos_id_str
                include "sd_csd.asm"           ; csd_set_bd_records / bd_record_write_hw / csd_base
                include "render_disk_sink.asm" ; render_disk_sink_reset / _byte / _finish

sam_mac:        equ chunk+0                    ; SAM MAC, from the loaded flash chunk
sam_ip:         equ chunk+6                    ; SAM IP

                include "netglue.asm"          ; ack_len / return_* / checksums

DST_MAX:        equ 2048                       ; HLOAD read-back buffer cap (small round-trip)

; ===========================================================================
; render_disk_probe_main — the bootable / trinload entry.
; ===========================================================================
render_disk_probe_main:
                di
                call    &06b5                  ; CLSLOWER: reset scroll count (i319a)
                ld      hl, rdp_str_banner     ; CR + "RDISK " — announce the tool
                call    rdp_print_str

                ; --- EEPROM "Trinity Network " chunk -> MAC/IP --------------------
                ld      a, 1
                ld      (part), a
                ld      (total), a
                ld      hl, rdp_chunk_name
                ld      de, name
                ld      bc, 16
                ldir
                call    find_index
                ld      a, (value)
                and     a
                jp      z, rdp_fail_cfg
                call    read_chunk
                ld      a, (value)
                and     a
                jp      z, rdp_fail_cfg
                ld      a, (sam_mac+0)
                ld      b, a
                ld      a, (sam_ip+0)
                or      b
                jp      z, rdp_fail_cfg

                ; --- ENC28J60 init (before any SD work, i242) ---------------------
                ld      hl, sam_mac
                call    drv_init
                ld      a, b
                or      c
                jp      z, rdp_fail_init

                ; --- read the CSD -> csd_base / csd_blocks / BD_RECORDS ------------
                call    csd_set_bd_records
                ld      hl, (BD_RECORDS)
                ld      a, h
                or      l
                jp      z, rdp_fail_init       ; CSD read failed -> no safe LBA math

                ; --- '1' stream the pattern into the record as "RELEASESRC" -------
                ; config: name, load address, target record.
                ld      hl, rdp_name
                ld      de, RDS_NAME
                ld      bc, 10
                ldir
                ld      hl, &8000
                ld      (RDS_LOAD), hl
                ld      hl, (RDP_CFG_RECORD)
                ld      (RDS_RECORD), hl
                call    render_disk_sink_reset

                ; stream_rem := N (32-bit); gen_acc := 0.
                ld      hl, (RDP_CFG_LEN)
                ld      (rdp_stream_rem), hl
                ld      hl, (RDP_CFG_LEN + 2)
                ld      (rdp_stream_rem + 2), hl
                xor     a
                ld      (rdp_gen_acc), a
rdp_stream_loop:
                ld      hl, (rdp_stream_rem)
                ld      a, h
                or      l
                jr      nz, rdp_stream_go
                ld      hl, (rdp_stream_rem + 2)
                ld      a, h
                or      l
                jr      z, rdp_stream_done     ; all 32 bits zero: stream complete
rdp_stream_go:
                ld      a, (rdp_gen_acc)
                call    render_disk_sink_byte  ; clobbers A,BC,DE,HL — state is in memory
                ld      a, (rdp_gen_acc)
                add     a, &9D
                ld      (rdp_gen_acc), a
                ; stream_rem -= 1 (32-bit)
                ld      hl, (rdp_stream_rem)
                ld      a, h
                or      l
                jr      nz, rdp_stream_declow
                ld      hl, (rdp_stream_rem + 2)
                dec     hl
                ld      (rdp_stream_rem + 2), hl
rdp_stream_declow:
                ld      hl, (rdp_stream_rem)
                dec     hl
                ld      (rdp_stream_rem), hl
                jr      rdp_stream_loop
rdp_stream_done:
                call    render_disk_sink_finish
                ld      a, "1"
                call    rdp_stage
                ; a write/guard failure during the stream -> verdict F, detail &FEED.
                ld      a, (RDS_ERR)
                or      a
                jp      nz, rdp_fail_write

                ; --- '2' HRECORD: select the record we just wrote -----------------
                ld      hl, (RDP_CFG_RECORD)
                xor     a
                rst     8
                defb    BD_HOOK_HRECORD
                ld      a, "2"
                call    rdp_stage

                ; --- '3' HGTHD: find "RELEASESRC" + verify the recorded size ------
                ld      hl, rdp_name
                ld      (BD_NAME_PTR), hl
                call    bdos_name_to_uifa
                call    bdos_lookup_hook       ; HGTHD; DIFA -> BD_DIFA
                call    bdos_difa_to_size      ; -> BD_SIZE (32-bit LE)
                ld      a, "3"
                call    rdp_stage
                ; BD_SIZE == N ?
                ld      hl, (BD_SIZE)
                ld      de, (RDP_CFG_LEN)
                or      a
                sbc     hl, de
                jp      nz, rdp_fail_size
                ld      hl, (BD_SIZE + 2)
                ld      de, (RDP_CFG_LEN + 2)
                or      a
                sbc     hl, de
                jp      nz, rdp_fail_size

                ; --- '4' HLOAD read-back (small round-trip only) ------------------
                ld      a, (RDP_CFG_HLOAD)
                or      a
                jp      z, rdp_pass            ; HGTHD-only proof (large file)

                ; wipe DST_BUF so a vacuous compare cannot pass.
                ld      hl, DST_BUF
                ld      bc, (RDP_CFG_LEN)
                ld      a, &AA
rdp_wipe:
                ld      (hl), a
                cpi
                jp      pe, rdp_wipe

                ; load contract from the deposited DIFA (bdos_load_hook): C = pages
                ; (+34), DE = lengthMod16K (+35..36, bit-7 marker cleared); dest is
                ; the section-C page already mapped (this tool's own page).
                ld      hl, (BD_DIFA + BD_OFF_LENGTH)
                ld      a, h
                and     BD_DIFA_MARKER
                ld      d, a
                ld      e, l
                ld      a, (BD_DIFA + BD_OFF_PAGES)
                ld      c, a
                ld      hl, DST_BUF
                call    bdos_load_hook
                ld      a, "4"
                call    rdp_stage

                ; --- '5' verdict: regenerate the pattern, byte-compare ------------
                ld      hl, DST_BUF
                ld      bc, (RDP_CFG_LEN)      ; N (<= DST_MAX, fits 16-bit)
                xor     a                      ; gen accumulator (byte 0 = 0)
rdp_cmp:
                cp      (hl)                   ; expected == loaded?
                jr      nz, rdp_fail_cmp
                add     a, &9D                 ; next expected byte
                inc     hl
                dec     bc
                push    af
                ld      a, b
                or      c
                jr      z, rdp_cmp_done_pop
                pop     af
                jr      rdp_cmp
rdp_cmp_done_pop:
                pop     af
rdp_pass:
                ld      hl, 0
                ld      (rdp_detail), hl
                ld      a, "P"
                jr      rdp_verdict_set

rdp_fail_write:
                ld      hl, &FEED
                ld      (rdp_detail), hl
                ld      a, "F"
                jr      rdp_verdict_set
rdp_fail_size:
                ld      hl, &FFFF
                ld      (rdp_detail), hl
                ld      a, "F"
                jr      rdp_verdict_set
rdp_fail_cmp:
                ; first mismatch offset = N - BC (BC = bytes still to compare, the
                ; mismatching byte included since we have not yet decremented it).
                ld      hl, (RDP_CFG_LEN)
                or      a
                sbc     hl, bc
                ld      (rdp_detail), hl
                ld      a, "F"

rdp_verdict_set:
                ld      (rdp_verdict), a
                ld      a, "5"
                call    rdp_stage
                ld      a, (rdp_verdict)
                call    dbg_char

; ===========================================================================
; rdp_serve_loop — serve '?' / 'R' / 'Q' (+ ARP/ICMP). The sd_push/hook_roundtrip
; framing, UDP port 0xEDB0, discovery tag "!RD".
; ===========================================================================
rdp_serve_loop:
                ld      a, &f7
                in      a, (&f9)
                bit     5, a                   ; Esc?
                ret     z                      ; -> trinload's start

                ld      hl, packet
                call    drv_read
                ld      a, b
                or      c
                jr      z, rdp_serve_loop

                ld      a, (packet+12)
                cp      &08
                jr      nz, rdp_serve_loop
                ld      a, (packet+13)
                cp      &06                    ; ARP?
                jr      nz, rdp_try_ipv4
                ld      a, (packet+21)
                cp      &01
                jr      nz, rdp_serve_loop
                inc     a
                ld      (packet+21), a
                ld      hl, (packet+38)
                ld      de, (sam_ip)
                and     a
                sbc     hl, de
                jr      nz, rdp_serve_loop
                ld      hl, (packet+40)
                ld      de, (sam_ip+2)
                and     a
                sbc     hl, de
                jr      nz, rdp_serve_loop
                call    return_eth
                call    return_arp
                ld      hl, packet
                ld      bc, 42
                call    drv_write
                jr      rdp_serve_loop

rdp_try_ipv4:
                and     a                      ; IPv4?
                jr      nz, rdp_serve_loop
                ld      a, (packet+20)
                and     %00100000
                jr      nz, rdp_serve_loop
                ld      a, (packet+23)
                cp      &01                    ; ICMP?
                jr      nz, rdp_try_udp
                ld      a, (packet+34)
                cp      &08
                jr      nz, rdp_serve_loop
                xor     a
                ld      (packet+34), a
                call    return_eth
                call    return_ip
                call    checksum_ip
                call    checksum_icmp
                ld      hl, packet
                call    ip_to_eth_len
                call    drv_write
                jp      rdp_serve_loop

rdp_try_udp:
                cp      &11                    ; UDP?
                jp      nz, rdp_serve_loop
                ld      de, (packet+36)
                ld      hl, &b0ed              ; port 0xEDB0
                and     a
                sbc     hl, de
                jp      nz, rdp_serve_loop
                ld      hl, (packet+30)
                ld      de, (sam_ip)
                and     a
                sbc     hl, de
                jp      nz, rdp_serve_loop
                ld      hl, (packet+32)
                ld      de, (sam_ip+2)
                and     a
                sbc     hl, de
                jp      nz, rdp_serve_loop

                ld      a, (packet+42)
                cp      "?"                    ; discovery?
                jr      nz, rdp_not_disc
                ld      a, "!"
                ld      (packet+42), a
                ld      a, "R"
                ld      (packet+43), a
                ld      a, "D"
                ld      (packet+44), a
                ld      bc, 3
                call    ack_len
                jp      rdp_serve_loop
rdp_not_disc:
                cp      "R"                    ; report?
                jr      nz, rdp_not_report
                ld      a, (rdp_verdict)
                ld      (packet+42), a
                ld      a, (rdp_phase)
                ld      (packet+43), a
                ld      hl, (rdp_detail)
                ld      (packet+44), hl
                ld      bc, 4
                call    ack_len
                jp      rdp_serve_loop
rdp_not_report:
                cp      "Q"                    ; quit?
                jp      nz, rdp_serve_loop
                ld      a, "q"
                ld      (packet+42), a
                ld      bc, 1
                call    ack_len
                ld      hl, rdp_str_bye
                call    rdp_print_str
                ei
                ret                            ; -> trinload's start

; ---------------------------------------------------------------------------
; rdp_stage / dbg_char / rdp_print_str — the RST &10 print idiom (trinload).
; ---------------------------------------------------------------------------
rdp_stage:
                ld      (rdp_phase), a
                jp      dbg_char
dbg_char:
                push    af
                push    bc
                push    de
                push    hl
                push    ix
                push    iy
                rst     &10
                pop     iy
                pop     ix
                pop     hl
                pop     de
                pop     bc
                pop     af
                ret
rdp_print_str:
                ld      a, (hl)
                or      a
                ret     z
                call    dbg_char
                inc     hl
                jr      rdp_print_str

; ---------------------------------------------------------------------------
; Failure paths — no-network cases only (a DOS-hook failure longjmps away).
; ---------------------------------------------------------------------------
rdp_fail_cfg:
                ld      hl, rdp_str_fail_cfg
                ld      a, 2                   ; red: no/bad network settings
                jr      rdp_fail_show
rdp_fail_init:
                ld      hl, rdp_str_fail_enc
                ld      a, 1                   ; blue: ENC/CSD init failed
rdp_fail_show:
                out     (&fe), a
                call    rdp_print_str
rdp_fail_wait:
                ld      a, &f7
                in      a, (&f9)
                bit     5, a
                jr      nz, rdp_fail_wait
                ret

; ===========================================================================
; Data.
; ===========================================================================
rdp_chunk_name: defm "Trinity Network "
rdp_name:       defm "RELEASESRC"           ; 10-char on-record name (exact fill)
                defb 0                          ; NUL terminator for bdos_name_to_uifa

rdp_gen_acc:    defb 0                          ; 8-bit stream generator accumulator
rdp_stream_rem: defs 4                          ; 32-bit bytes-left-to-stream counter

rdp_phase:      defb "0"
rdp_verdict:    defb "-"
rdp_detail:     defw 0

rdp_str_banner: defb 13
                defm "RDISK "
                defb 0
rdp_str_bye:    defb 13
                defm "DONE"
                defb 13, 0
rdp_str_fail_cfg:
                defb 13
                defm "NO NET CONFIG"
                defb 13, 0
rdp_str_fail_enc:
                defb 13
                defm "ENC/CSD FAIL"
                defb 13, 0

DST_BUF:        defs DST_MAX                    ; HLOAD read-back destination (small N)
packet:         defs 1518                       ; RX/TX frame buffer

; ===========================================================================
; RDP_CONFIG — host/test-patchable config block (boot_record idiom), patched by
; file offset from RDP_CONFIG (= RDP_CONFIG - &8000). Keep the layout STABLE.
;   +0  RDP_CONFIG       1 byte   magic = &5A (patch anchor; never written)
;   +1  RDP_CFG_RECORD   2 bytes  target record number (LE16, >= 1)
;   +3  RDP_CFG_LEN      4 bytes  stream length N in DATA bytes (LE32)
;   +7  RDP_CFG_HLOAD    1 byte   nonzero = also HLOAD + byte-compare (needs N <= DST_MAX)
; ===========================================================================
RDP_CFG_MAGIC_VAL:    equ &5A
RDP_CONFIG:           defb RDP_CFG_MAGIC_VAL    ; +0 magic (patch anchor)
RDP_CFG_RECORD:       defw 1                    ; +1 record (patched)
RDP_CFG_LEN:          defb 0, 0, 0, 0           ; +3 N (patched)
RDP_CFG_HLOAD:        defb 0                     ; +7 HLOAD flag (patched)

length:               equ $ - render_disk_probe_main
