package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedBannerItems = `<!--
  GENERATED by ` + "`registry gen`" + ` (tools/registry) — DO NOT EDIT BY HAND.
  Source of truth: registry/items.yaml
  Regenerate:      make registry
  Validated in CI by the ` + "`registry-sync`" + ` job. Hand edits FAIL CI.
-->
`

const generatedBannerQuestions = `<!--
  GENERATED by ` + "`registry gen`" + ` (tools/registry) — DO NOT EDIT BY HAND.
  Source of truth: registry/questions.yaml
  Regenerate:      make registry
  Validated in CI by the ` + "`registry-sync`" + ` job. Hand edits FAIL CI.
-->
`

// defaultTemplatesDir is the path to the header templates relative to the
// repo root.  It is used when no explicit templates directory is given.
const defaultTemplatesDir = "registry/templates"

// escapeCell applies the escaping rules for a markdown table cell:
// pipe characters become \|, and newlines become <br>.
func escapeCell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", "<br>")
	return strings.TrimSpace(s)
}

// renderItemStatus renders the status cell value from structured fields.
func renderItemStatus(it Item) string {
	switch it.Status {
	case StatusDone:
		for _, pr := range it.PRs {
			if pr.Role == RoleCompleting {
				return fmt.Sprintf("DONE — PR #%d", pr.Num)
			}
		}
		return "DONE"
	case StatusWontfix:
		return "WONTFIX"
	case StatusBlocked:
		return fmt.Sprintf("BLOCKED:%s", it.Blocker)
	default:
		return string(it.Status)
	}
}

// renderQuestionStatus renders the status cell value for a question.
func renderQuestionStatus(q Question) string {
	switch q.Status {
	case StatusDone:
		for _, pr := range q.PRs {
			if pr.Role == RoleCompleting {
				return fmt.Sprintf("DONE — PR #%d", pr.Num)
			}
		}
		return "DONE"
	case StatusWontfix:
		return "WONTFIX"
	case StatusBlocked:
		return fmt.Sprintf("BLOCKED:%s", q.Blocker)
	default:
		return string(q.Status)
	}
}

// renderItemRefs renders a refs list as a comma-separated string.
func renderItemRefs(refs []string) string {
	return strings.Join(refs, ", ")
}

// sortedItems returns items in canonical typed sort order.
func sortedItems(items []Item) []Item {
	out := make([]Item, len(items))
	copy(out, items)
	sort.SliceStable(out, func(i, j int) bool {
		ki := parseItemSortKey(out[i].ID)
		kj := parseItemSortKey(out[j].ID)
		return ki.less(kj)
	})
	return out
}

// sortedQuestions returns questions in canonical typed sort order (q<N>[letter]).
func sortedQuestions(qs []Question) []Question {
	out := make([]Question, len(qs))
	copy(out, qs)
	sort.SliceStable(out, func(i, j int) bool {
		ki := parseQSortKey(out[i].ID)
		kj := parseQSortKey(out[j].ID)
		return ki.less(kj)
	})
	return out
}

func parseQSortKey(id string) sortKey {
	rest := id[1:] // strip 'q'
	k := strings.IndexFunc(rest, func(r rune) bool { return r < '0' || r > '9' })
	if k == -1 {
		n, _ := parseInt(rest)
		return sortKey{n: n, brickN: -1}
	}
	n, _ := parseInt(rest[:k])
	return sortKey{n: n, letter: rest[k:], brickN: -1}
}

func parseInt(s string) (int, error) {
	n := 0
	for _, c := range s {
		if c < '0' || c > '9' {
			return 0, fmt.Errorf("not an integer: %q", s)
		}
		n = n*10 + int(c-'0')
	}
	return n, nil
}

// loadTemplate reads a header template file by name from the templates
// directory.  The name is one of the four canonical base names (without
// the ".head.md" suffix), e.g. "item-registry-open".  An error is returned
// only if the file cannot be read; the caller decides how to handle absence.
func loadTemplate(templatesDir, name string) (string, error) {
	path := filepath.Join(templatesDir, name+".head.md")
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("load template %s: %w", path, err)
	}
	return string(data), nil
}

// genItemsOpenClosed writes the open and closed item registry tables to their
// respective writers.  The banner is written first, then the header template
// (if a templatesDir is provided and the template exists), then the table.
func genItemsOpenClosed(reg *Registry, openW, closedW io.Writer) error {
	return genItemsOpenClosedWithTemplates(reg, openW, closedW, "")
}

// genItemsOpenClosedWithTemplates is the implementation behind
// genItemsOpenClosed; callers that want templates pass a non-empty
// templatesDir.  An empty string skips template loading (Phase-1 behaviour,
// keeps existing tests passing).
func genItemsOpenClosedWithTemplates(reg *Registry, openW, closedW io.Writer, templatesDir string) error {
	items := sortedItems(reg.Items)

	header := "| **id** | title | status | refs |\n|---|---|---|---|\n"

	// Open items.
	fmt.Fprint(openW, generatedBannerItems)
	if templatesDir != "" {
		tmpl, err := loadTemplate(templatesDir, "item-registry-open")
		if err != nil {
			return err
		}
		fmt.Fprint(openW, tmpl)
	}
	fmt.Fprint(openW, "\n")
	fmt.Fprint(openW, header)
	for _, it := range items {
		if isOpen(it.Status) {
			fmt.Fprintf(openW, "| **%s** | %s | %s | %s |\n",
				escapeCell(it.ID),
				escapeCell(it.Title),
				escapeCell(renderItemStatus(it)),
				escapeCell(renderItemRefs(it.Refs)),
			)
		}
	}

	// Closed items.
	fmt.Fprint(closedW, generatedBannerItems)
	if templatesDir != "" {
		tmpl, err := loadTemplate(templatesDir, "item-registry-closed")
		if err != nil {
			return err
		}
		fmt.Fprint(closedW, tmpl)
	}
	fmt.Fprint(closedW, "\n")
	fmt.Fprint(closedW, header)
	for _, it := range items {
		if !isOpen(it.Status) {
			fmt.Fprintf(closedW, "| **%s** | %s | %s | %s |\n",
				escapeCell(it.ID),
				escapeCell(it.Title),
				escapeCell(renderItemStatus(it)),
				escapeCell(renderItemRefs(it.Refs)),
			)
		}
	}
	return nil
}

// genQuestionsOpenClosed writes the open and closed question registry tables.
func genQuestionsOpenClosed(reg *Registry, openW, closedW io.Writer) error {
	return genQuestionsOpenClosedWithTemplates(reg, openW, closedW, "")
}

// genQuestionsOpenClosedWithTemplates is the implementation behind
// genQuestionsOpenClosed; callers that want templates pass a non-empty
// templatesDir.
func genQuestionsOpenClosedWithTemplates(reg *Registry, openW, closedW io.Writer, templatesDir string) error {
	questions := sortedQuestions(reg.Questions)

	header := "| **id** | title | status | refs |\n|---|---|---|---|\n"

	fmt.Fprint(openW, generatedBannerQuestions)
	if templatesDir != "" {
		tmpl, err := loadTemplate(templatesDir, "question-registry-open")
		if err != nil {
			return err
		}
		fmt.Fprint(openW, tmpl)
	}
	fmt.Fprint(openW, "\n")
	fmt.Fprint(openW, header)
	for _, q := range questions {
		if isOpen(q.Status) {
			fmt.Fprintf(openW, "| **%s** | %s | %s | %s |\n",
				escapeCell(q.ID),
				escapeCell(q.Title),
				escapeCell(renderQuestionStatus(q)),
				escapeCell(renderItemRefs(q.Refs)),
			)
		}
	}

	fmt.Fprint(closedW, generatedBannerQuestions)
	if templatesDir != "" {
		tmpl, err := loadTemplate(templatesDir, "question-registry-closed")
		if err != nil {
			return err
		}
		fmt.Fprint(closedW, tmpl)
	}
	fmt.Fprint(closedW, "\n")
	fmt.Fprint(closedW, header)
	for _, q := range questions {
		if !isOpen(q.Status) {
			fmt.Fprintf(closedW, "| **%s** | %s | %s | %s |\n",
				escapeCell(q.ID),
				escapeCell(q.Title),
				escapeCell(renderQuestionStatus(q)),
				escapeCell(renderItemRefs(q.Refs)),
			)
		}
	}
	return nil
}
