package main

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// Generated-file banners (spec §"Generator" — mirroring the tables-gen .inc convention).
const generatedBannerItems = `<!--
  GENERATED by ` + "`registry gen`" + ` (tools/registry) — DO NOT EDIT BY HAND.
  Source of truth: registry/items.yaml
  Regenerate:      make registry
  Validated in CI by the ` + "`registry-sync`" + ` job. Hand edits FAIL CI.
-->
`

const generatedBannerQuestions = `<!--
  GENERATED by ` + "`registry gen`" + ` (tools/registry) — DO NOT EDIT BY HAND.
  Source of truth: registry/questions.yaml
  Regenerate:      make registry
  Validated in CI by the ` + "`registry-sync`" + ` job. Hand edits FAIL CI.
-->
`

// escapeCell applies the escaping rules for a markdown table cell:
// pipe characters become \|, and newlines become <br>.
// Escaping happens in one place (spec §"Generator").
func escapeCell(s string) string {
	// Trim first, so a block scalar's trailing newline doesn't become a spurious
	// trailing <br>; internal newlines (real line breaks) still render as <br>.
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", "<br>")
	return s
}

// renderItemStatus renders the status cell value from structured fields.
// Spec §"Generator": OPEN / IN_PROGRESS / DONE — PR #N / WONTFIX — <reason>.
// No BLOCKED rendering — blocked-ness is derived from depends_on edges, not stored.
func renderItemStatus(it Item) string {
	switch it.Status {
	case StatusDone:
		for _, pr := range it.PRs {
			if pr.Role == RoleCompleting {
				return fmt.Sprintf("DONE — PR #%d", pr.Num)
			}
		}
		return "DONE"
	case StatusWontfix:
		// Reason lives in description; render a short excerpt as suffix.
		reason := strings.TrimSpace(it.Description)
		if idx := strings.IndexRune(reason, '\n'); idx >= 0 {
			reason = reason[:idx]
		}
		if len(reason) > 80 {
			reason = reason[:80] + "…"
		}
		return fmt.Sprintf("WONTFIX — %s", reason)
	default:
		return string(it.Status)
	}
}

// renderItemRefs renders the refs list plus any depends_on edges.
// Gated items show their depends_on edges in the refs/links cell
// (spec §"Generator": "A gated item renders OPEN with its depends_on edges
// shown in the refs/links cell").
func renderItemRefs(it Item) string {
	parts := make([]string, 0, len(it.Refs)+len(it.DependsOn))
	for _, dep := range it.DependsOn {
		parts = append(parts, fmt.Sprintf("gated-on:%s", dep))
	}
	parts = append(parts, it.Refs...)
	return strings.Join(parts, ", ")
}

// sortedItems returns items in canonical typed sort order.
func sortedItems(items []Item) []Item {
	out := make([]Item, len(items))
	copy(out, items)
	sort.SliceStable(out, func(i, j int) bool {
		ki := parseItemSortKey(out[i].ID)
		kj := parseItemSortKey(out[j].ID)
		return ki.less(kj)
	})
	return out
}

// sortedQuestions returns questions in canonical typed sort order (q<N>[letter]).
func sortedQuestions(qs []Question) []Question {
	out := make([]Question, len(qs))
	copy(out, qs)
	sort.SliceStable(out, func(i, j int) bool {
		ki := parseQSortKey(out[i].ID)
		kj := parseQSortKey(out[j].ID)
		return ki.less(kj)
	})
	return out
}

func parseQSortKey(id string) sortKey {
	rest := id[1:] // strip 'q'
	k := strings.IndexFunc(rest, func(r rune) bool { return r < '0' || r > '9' })
	if k == -1 {
		n, _ := parseInt(rest)
		return sortKey{n: n, brickN: -1}
	}
	n, _ := parseInt(rest[:k])
	return sortKey{n: n, letter: rest[k:], brickN: -1}
}

func parseInt(s string) (int, error) {
	n := 0
	for _, c := range s {
		if c < '0' || c > '9' {
			return 0, fmt.Errorf("not an integer: %q", s)
		}
		n = n*10 + int(c-'0')
	}
	return n, nil
}

// renderItemCell renders the item's display cell: the bold title followed by the
// description, so the generated table carries the item's actual content (not just
// the short title) — mirroring how questions render their full body. The old
// hand-edited registry's "item" column was exactly this: a bold lead-in + detail.
func renderItemCell(it Item) string {
	title := escapeCell(it.Title)
	desc := escapeCell(it.Description)
	if desc == "" {
		return "**" + title + "**"
	}
	return "**" + title + "** — " + desc
}

// genItemsOpenClosed writes the open and closed item registry tables to their
// respective writers. Spec §"Generator" — three views total (two item + one question).
func genItemsOpenClosed(reg *Registry, openW, closedW io.Writer) error {
	items := sortedItems(reg.Items)

	header := "| **id** | item | status | refs/links |\n|---|---|---|---|\n"

	// Open items (OPEN or IN_PROGRESS).
	fmt.Fprint(openW, generatedBannerItems)
	fmt.Fprint(openW, "\n")
	fmt.Fprint(openW, header)
	for _, it := range items {
		if isOpen(it.Status) {
			fmt.Fprintf(openW, "| **%s** | %s | %s | %s |\n",
				escapeCell(it.ID),
				renderItemCell(it),
				escapeCell(renderItemStatus(it)),
				escapeCell(renderItemRefs(it)),
			)
		}
	}

	// Closed items (DONE or WONTFIX).
	fmt.Fprint(closedW, generatedBannerItems)
	fmt.Fprint(closedW, "\n")
	fmt.Fprint(closedW, header)
	for _, it := range items {
		if !isOpen(it.Status) {
			fmt.Fprintf(closedW, "| **%s** | %s | %s | %s |\n",
				escapeCell(it.ID),
				renderItemCell(it),
				escapeCell(renderItemStatus(it)),
				escapeCell(renderItemRefs(it)),
			)
		}
	}
	return nil
}

// genQuestionsOpen writes the open question registry table to the given writer.
// Questions are transient (spec §"Questions — transient by design"):
// there is ONE generated view — open only; no closed view.
func genQuestionsOpen(reg *Registry, openW io.Writer) error {
	questions := sortedQuestions(reg.Questions)

	header := "| **id** | body | owner |\n|---|---|---|\n"

	fmt.Fprint(openW, generatedBannerQuestions)
	fmt.Fprint(openW, "\n")
	fmt.Fprint(openW, header)
	for _, q := range questions {
		fmt.Fprintf(openW, "| **%s** | %s | %s |\n",
			escapeCell(q.ID),
			escapeCell(q.Body),
			escapeCell(q.Owner),
		)
	}
	return nil
}
