package main

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// Generated-file banners (spec §"Generator" — mirroring the tables-gen .inc convention).
const generatedBannerItems = `<!--
  GENERATED by ` + "`registry gen`" + ` (tools/registry) — DO NOT EDIT BY HAND.
  Source of truth: registry/items.yaml
  Regenerate:      make registry
  Validated in CI by the ` + "`registry-sync`" + ` job. Hand edits FAIL CI.
-->
`

const generatedBannerQuestions = `<!--
  GENERATED by ` + "`registry gen`" + ` (tools/registry) — DO NOT EDIT BY HAND.
  Source of truth: registry/questions.yaml
  Regenerate:      make registry
  Validated in CI by the ` + "`registry-sync`" + ` job. Hand edits FAIL CI.
-->
`

// escapeCell applies the escaping rules for a markdown table cell:
// pipe characters become \|, and newlines become <br>.
// Escaping happens in one place (spec §"Generator").
func escapeCell(s string) string {
	// Trim first, so a block scalar's trailing newline doesn't become a spurious
	// trailing <br>; internal newlines (real line breaks) still render as <br>.
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", "<br>")
	return s
}

// repoPullURL is the base URL for pull requests in this repository.
const repoPullURL = "https://github.com/petemoore/sam-aarch64/pull/"

// renderItemStatus renders the status cell — just the status token.
// PR information is rendered separately in the PR column.
// No BLOCKED rendering — blocked-ness is derived from depends_on edges, not stored.
func renderItemStatus(it Item) string {
	return string(it.Status)
}

// renderItemPRs renders the PR column as comma-separated clickable markdown links,
// e.g. "[#124](https://github.com/petemoore/sam-aarch64/pull/124)".
// Returns an empty string when the item carries no PRs.
// The returned string is already safe markdown — do NOT run escapeCell over it.
func renderItemPRs(it Item) string {
	if len(it.PRs) == 0 {
		return ""
	}
	parts := make([]string, 0, len(it.PRs))
	for _, pr := range it.PRs {
		parts = append(parts, fmt.Sprintf("[#%d](%s%d)", pr.Num, repoPullURL, pr.Num))
	}
	return strings.Join(parts, ", ")
}

// renderItemDependents renders the reverse-dependency column: ids of all items
// whose depends_on includes this item's id, in canonical sort order.
// Returns an empty string when no items depend on this item.
func renderItemDependents(it Item, reverseEdges map[string][]string) string {
	dependents := reverseEdges[it.ID]
	if len(dependents) == 0 {
		return ""
	}
	// Return a copy in sorted order (reverseEdges is pre-sorted at build time).
	return strings.Join(dependents, ", ")
}

// buildReverseEdges returns a map from item id to the sorted list of ids of all
// items that declare depends_on including that id.
func buildReverseEdges(items []Item) map[string][]string {
	rev := map[string][]string{}
	for _, it := range items {
		for _, dep := range it.DependsOn {
			rev[dep] = append(rev[dep], it.ID)
		}
	}
	// Sort each list for deterministic output.
	for k := range rev {
		sortStrings(rev[k])
	}
	return rev
}

// renderItemDeps renders the depends_on edges — the gating item/question ids
// that make up the dependency DAG. It is its own first-class column so the DAG
// is readable from the generated view, not buried among cross-links. Empty when
// the item is not gated on anything.
func renderItemDeps(it Item) string {
	return strings.Join(it.DependsOn, ", ")
}

// renderItemRefs renders the cross-links / pointers (file paths, §sections, URLs,
// related ids). It EXCLUDES any ref id that is also a depends_on target — those
// belong to the deps column, so an id is never shown twice.
func renderItemRefs(it Item) string {
	dep := make(map[string]bool, len(it.DependsOn))
	for _, d := range it.DependsOn {
		dep[d] = true
	}
	parts := make([]string, 0, len(it.Refs))
	for _, r := range it.Refs {
		if !dep[r] {
			parts = append(parts, r)
		}
	}
	return strings.Join(parts, ", ")
}

// sortedItems returns items in canonical typed sort order.
func sortedItems(items []Item) []Item {
	out := make([]Item, len(items))
	copy(out, items)
	sort.SliceStable(out, func(i, j int) bool {
		ki := parseItemSortKey(out[i].ID)
		kj := parseItemSortKey(out[j].ID)
		return ki.less(kj)
	})
	return out
}

// sortedQuestions returns questions in canonical typed sort order (q<N>[letter]).
func sortedQuestions(qs []Question) []Question {
	out := make([]Question, len(qs))
	copy(out, qs)
	sort.SliceStable(out, func(i, j int) bool {
		ki := parseQSortKey(out[i].ID)
		kj := parseQSortKey(out[j].ID)
		return ki.less(kj)
	})
	return out
}

func parseQSortKey(id string) sortKey {
	rest := id[1:] // strip 'q'
	k := strings.IndexFunc(rest, func(r rune) bool { return r < '0' || r > '9' })
	if k == -1 {
		n, _ := parseInt(rest)
		return sortKey{n: n, brickN: -1}
	}
	n, _ := parseInt(rest[:k])
	return sortKey{n: n, letter: rest[k:], brickN: -1}
}

func parseInt(s string) (int, error) {
	n := 0
	for _, c := range s {
		if c < '0' || c > '9' {
			return 0, fmt.Errorf("not an integer: %q", s)
		}
		n = n*10 + int(c-'0')
	}
	return n, nil
}

// renderItemCell renders the item's display cell: the bold title followed by the
// description, so the generated table carries the item's actual content (not just
// the short title) — mirroring how questions render their full body. The old
// hand-edited registry's "item" column was exactly this: a bold lead-in + detail.
func renderItemCell(it Item) string {
	title := escapeCell(it.Title)
	desc := escapeCell(it.Description)
	if desc == "" {
		return "**" + title + "**"
	}
	return "**" + title + "** — " + desc
}

// genItemsOpenClosed writes the open and closed item registry tables to their
// respective writers. Spec §"Generator" — three views total (two item + one question).
// Column order: id | item | status | PR | deps | dependents | refs/links
func genItemsOpenClosed(reg *Registry, openW, closedW io.Writer) error {
	items := sortedItems(reg.Items)
	reverseEdges := buildReverseEdges(items)

	header := "| **id** | item | status | PR | deps | dependents | refs/links |\n|---|---|---|---|---|---|---|\n"

	// Open items (OPEN or IN_PROGRESS).
	fmt.Fprint(openW, generatedBannerItems)
	fmt.Fprint(openW, "\n")
	fmt.Fprint(openW, header)
	for _, it := range items {
		if isOpen(it.Status) {
			fmt.Fprintf(openW, "| **%s** | %s | %s | %s | %s | %s | %s |\n",
				escapeCell(it.ID),
				renderItemCell(it),
				escapeCell(renderItemStatus(it)),
				renderItemPRs(it),
				escapeCell(renderItemDeps(it)),
				escapeCell(renderItemDependents(it, reverseEdges)),
				escapeCell(renderItemRefs(it)),
			)
		}
	}

	// Closed items (DONE or WONTFIX).
	fmt.Fprint(closedW, generatedBannerItems)
	fmt.Fprint(closedW, "\n")
	fmt.Fprint(closedW, header)
	for _, it := range items {
		if !isOpen(it.Status) {
			fmt.Fprintf(closedW, "| **%s** | %s | %s | %s | %s | %s | %s |\n",
				escapeCell(it.ID),
				renderItemCell(it),
				escapeCell(renderItemStatus(it)),
				renderItemPRs(it),
				escapeCell(renderItemDeps(it)),
				escapeCell(renderItemDependents(it, reverseEdges)),
				escapeCell(renderItemRefs(it)),
			)
		}
	}
	return nil
}

// genQuestionsOpen writes the open question registry table to the given writer.
// Questions are transient (spec §"Questions — transient by design"):
// there is ONE generated view — open only; no closed view.
func genQuestionsOpen(reg *Registry, openW io.Writer) error {
	questions := sortedQuestions(reg.Questions)

	header := "| **id** | body | owner |\n|---|---|---|\n"

	fmt.Fprint(openW, generatedBannerQuestions)
	fmt.Fprint(openW, "\n")
	fmt.Fprint(openW, header)
	for _, q := range questions {
		fmt.Fprintf(openW, "| **%s** | %s | %s |\n",
			escapeCell(q.ID),
			escapeCell(q.Body),
			escapeCell(q.Owner),
		)
	}
	return nil
}

// generatedBannerBacklog is the DO-NOT-EDIT banner for backlog.md.
const generatedBannerBacklog = `<!--
  GENERATED by ` + "`registry gen`" + ` (tools/registry) — DO NOT EDIT BY HAND.
  Source of truth: registry/priority.yaml + registry/items.yaml
  Regenerate:      make registry
  Validated in CI by the ` + "`registry-sync`" + ` job. Hand edits FAIL CI.
-->
`

// genBacklog writes the priority-ordered backlog view to w. The table lists all
// pullable items in priority order with a 1-based rank column. When priority is
// empty the table is written with zero data rows (header only).
func genBacklog(reg *Registry, priority []string, w io.Writer) error {
	// Build a map from item id to item for fast lookup.
	byID := map[string]Item{}
	for _, it := range reg.Items {
		byID[it.ID] = it
	}

	reverseEdges := buildReverseEdges(reg.Items)

	header := "| rank | **id** | item | status | deps | dependents |\n|---|---|---|---|---|---|\n"

	fmt.Fprint(w, generatedBannerBacklog)
	fmt.Fprint(w, "\n")
	fmt.Fprint(w, header)
	for rank, id := range priority {
		it, ok := byID[id]
		if !ok {
			// Omit unknown ids from the view (validate would have caught them).
			continue
		}
		fmt.Fprintf(w, "| %d | **%s** | %s | %s | %s | %s |\n",
			rank+1,
			escapeCell(it.ID),
			renderItemCell(it),
			escapeCell(renderItemStatus(it)),
			escapeCell(renderItemDeps(it)),
			escapeCell(renderItemDependents(it, reverseEdges)),
		)
	}
	return nil
}
