package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// atomicWriteFile writes data to path atomically: it writes a temp file in the
// same directory, fsyncs it, then renames it over path (rename is atomic within
// a filesystem on POSIX). A crash or a concurrent reader therefore never sees a
// half-written registry file — readers see either the old or the new content,
// never a truncated one. Paired with the registry lock (lock.go), this makes a
// mutation safe against another process reading or writing concurrently.
func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return fmt.Errorf("atomic write %s: create temp: %w", path, err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op once renamed; cleans up on any error path
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return fmt.Errorf("atomic write %s: %w", path, err)
	}
	if err := tmp.Chmod(perm); err != nil {
		tmp.Close()
		return fmt.Errorf("atomic write %s: chmod: %w", path, err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return fmt.Errorf("atomic write %s: sync: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("atomic write %s: close: %w", path, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("atomic write %s: rename: %w", path, err)
	}
	return nil
}

// writeItems serializes items to path in canonical YAML order.
// The output uses fixed key order and two-space indent as the canonical serializer
// (spec §"Source format — YAML"): "stored canonically sorted (true-numeric order,
// fixed key order, two-space indent); the CLI's writer is the single canonical
// serializer".
func writeItems(path string, items []Item) error {
	sorted := sortedItems(items)
	var sb strings.Builder
	sb.WriteString("# Registry items — generated by `registry` CLI; source of truth.\n")
	sb.WriteString("# Spec: docs/specs/registry-source-of-truth-design.md\n")
	for _, it := range sorted {
		sb.WriteString("\n")
		writeItemRecord(&sb, it)
	}
	return atomicWriteFile(path, []byte(sb.String()), 0o644)
}

// writeQuestions serializes questions to path in canonical YAML order.
func writeQuestions(path string, questions []Question) error {
	sorted := sortedQuestions(questions)
	var sb strings.Builder
	sb.WriteString("# Registry questions — generated by `registry` CLI; source of truth.\n")
	sb.WriteString("# Spec §\"Questions — transient by design\".\n")
	for _, q := range sorted {
		sb.WriteString("\n")
		writeQuestionRecord(&sb, q)
	}
	return atomicWriteFile(path, []byte(sb.String()), 0o644)
}

// writeItemRecord writes a single item record in canonical YAML form to sb.
// Key order follows the spec schema: id, title, description, status, depends_on,
// kind, owner, prs, parent, refs.
func writeItemRecord(sb *strings.Builder, it Item) {
	sb.WriteString(fmt.Sprintf("- id: %s\n", it.ID))
	sb.WriteString(fmt.Sprintf("  title: %s\n", yamlQuoteString(it.Title)))
	if it.Description != "" {
		// Use block scalar for description (spec §"Source format").
		sb.WriteString("  description: |\n")
		for _, line := range strings.Split(strings.TrimRight(it.Description, "\n"), "\n") {
			sb.WriteString(fmt.Sprintf("    %s\n", line))
		}
	} else {
		sb.WriteString("  description: \"\"\n")
	}
	sb.WriteString(fmt.Sprintf("  status: %s\n", string(it.Status)))
	if len(it.DependsOn) > 0 {
		sb.WriteString(fmt.Sprintf("  depends_on: [%s]\n", joinQuoted(it.DependsOn)))
	}
	if it.Kind != "" {
		sb.WriteString(fmt.Sprintf("  kind: %s\n", it.Kind))
	}
	sb.WriteString(fmt.Sprintf("  owner: %s\n", it.Owner))
	if len(it.PRs) > 0 {
		sb.WriteString("  prs:\n")
		for _, pr := range it.PRs {
			sb.WriteString(fmt.Sprintf("    - {num: %d, role: %s}\n", pr.Num, string(pr.Role)))
		}
	}
	if it.Parent != "" {
		sb.WriteString(fmt.Sprintf("  parent: %s\n", it.Parent))
	}
	if len(it.Refs) > 0 {
		sb.WriteString(fmt.Sprintf("  refs: [%s]\n", joinQuoted(it.Refs)))
	}
}

// writeQuestionRecord writes a single question record in canonical YAML form.
func writeQuestionRecord(sb *strings.Builder, q Question) {
	sb.WriteString(fmt.Sprintf("- id: %s\n", q.ID))
	// Use block scalar for body (may be multi-line question).
	sb.WriteString("  body: |\n")
	for _, line := range strings.Split(strings.TrimRight(q.Body, "\n"), "\n") {
		sb.WriteString(fmt.Sprintf("    %s\n", line))
	}
	sb.WriteString(fmt.Sprintf("  owner: %s\n", q.Owner))
}

// yamlQuoteString returns a YAML-safe double-quoted string if necessary,
// or the bare value if it can stand as a plain scalar.
func yamlQuoteString(s string) string {
	// Characters that require quoting anywhere in a plain scalar.
	needsQuote := strings.ContainsAny(s, "\":#{}[]|>&*!,?")
	// Indicator characters that cannot START a YAML plain scalar (they would be
	// parsed as a directive/anchor/alias/tag/quote/flow marker). A title like
	// "%nobits/BSS …" or "@foo" is invalid unquoted, so quote on a leading one.
	if s != "" && strings.ContainsRune("%@`'\"|>&*!?#,[]{}", rune(s[0])) {
		needsQuote = true
	}
	if needsQuote || s == "" {
		escaped := strings.ReplaceAll(s, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		return `"` + escaped + `"`
	}
	return s
}

// joinQuoted joins ids/refs as a YAML flow sequence, quoting entries that
// contain spaces or special characters.
func joinQuoted(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		if strings.ContainsAny(s, " \t:#{}[]|>&*!,?\"'") {
			escaped := strings.ReplaceAll(s, `\`, `\\`)
			escaped = strings.ReplaceAll(escaped, `"`, `\"`)
			parts[i] = `"` + escaped + `"`
		} else {
			parts[i] = s
		}
	}
	return strings.Join(parts, ", ")
}

// ledgerPath returns the path to the append-only id ledger relative to the
// registry directory (spec invariant 1: "never reused").
func ledgerPath(registryDir string) string {
	return registryDir + "/.id-ledger.txt"
}

// loadLedger reads the append-only ledger file and returns the set of all ids
// that have ever been minted (including since-deleted ones).
func loadLedger(path string) (map[string]bool, error) {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return map[string]bool{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("load ledger %s: %w", path, err)
	}
	ledger := map[string]bool{}
	for _, line := range strings.Split(strings.TrimSpace(string(data)), "\n") {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "#") {
			ledger[line] = true
		}
	}
	return ledger, nil
}

// appendToLedger records a newly-minted id in the append-only ledger.
func appendToLedger(path, id string) error {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return fmt.Errorf("open ledger %s: %w", path, err)
	}
	defer f.Close()
	_, err = fmt.Fprintln(f, id)
	return err
}

// nextItemID returns the next free item id (i<N>) not present in either the
// source registry or the ledger (spec invariant 1: never reuse a deleted id).
func nextItemID(reg *Registry, ledger map[string]bool) string {
	maxN := 0
	for _, it := range reg.Items {
		if itemIDRe.MatchString(it.ID) {
			k := parseItemSortKey(it.ID)
			if k.letter == "" && k.brickN == -1 && k.n > maxN {
				maxN = k.n
			}
		}
	}
	for id := range ledger {
		if itemIDRe.MatchString(id) {
			k := parseItemSortKey(id)
			if k.letter == "" && k.brickN == -1 && k.n > maxN {
				maxN = k.n
			}
		}
	}
	return fmt.Sprintf("i%d", maxN+1)
}

// mintedIDs returns the set of every id that exists in the registry or has ever
// been minted (the append-only ledger) — the ids an allocator must avoid so a
// since-deleted id is never re-used (spec invariant 1).
func mintedIDs(reg *Registry, ledger map[string]bool) map[string]bool {
	taken := map[string]bool{}
	for id := range ledger {
		taken[id] = true
	}
	for _, it := range reg.Items {
		taken[it.ID] = true
	}
	for _, q := range reg.Questions {
		taken[q.ID] = true
	}
	return taken
}

// idDecompRe decomposes an item id into its grammar components:
// base (iN), optional letter, optional brick (-bM), optional brick-letter.
// Mirrors itemIDRe (which validates the same shape).
var idDecompRe = regexp.MustCompile(`^(i[0-9]+)([a-z])?(-b[0-9]+)?([a-z])?$`)

// nextSubID returns the next free sub-id under parentID, determined entirely by
// the parent's id shape (the caller never invents an id — spec: ids are
// tool-determined, never hand-picked). The splitting scheme, one level per call,
// staying within itemIDRe:
//
//	iN        → iNa, iNb, … iNz   (append a letter; max 26)
//	iNx       → iNx-b1, iNx-b2, … (append a numbered brick; unbounded)
//	iN[x]-bM  → iN[x]-bMa, …-bMz  (append a letter to the brick; max 26)
//	iN[x]-bMy → (error: maximum nesting depth — the grammar allows no further level)
//
// The letter levels are capped at 26 (a–z); when they are exhausted nextSubID
// returns a loud error rather than silently overflowing or mangling the id — a
// 26-child group is itself a "too big, restructure" signal (the numbered brick
// level is the unbounded escape hatch). taken is the set from mintedIDs.
func nextSubID(parentID string, taken map[string]bool) (string, error) {
	m := idDecompRe.FindStringSubmatch(parentID)
	if m == nil {
		return "", fmt.Errorf("parent id %q does not match the item id grammar", parentID)
	}
	letter, brick, brickLetter := m[2], m[3], m[4]

	var prefix string
	var numeric bool
	switch {
	case letter == "" && brick == "": // iN → iN{a..z}
		prefix, numeric = parentID, false
	case letter != "" && brick == "": // iNx → iNx-b{1..}
		prefix, numeric = parentID+"-b", true
	case brick != "" && brickLetter == "": // iN[x]-bM → +{a..z}
		prefix, numeric = parentID, false
	default: // iN[x]-bMy — already at the deepest grammar level
		return "", fmt.Errorf("cannot auto-allocate a sub-id under %q: maximum nesting depth reached (the id grammar allows no further level) — restructure instead", parentID)
	}

	if numeric {
		for n := 1; ; n++ {
			cand := fmt.Sprintf("%s%d", prefix, n)
			if !taken[cand] {
				return cand, nil
			}
		}
	}
	for c := byte('a'); c <= 'z'; c++ {
		cand := fmt.Sprintf("%s%c", prefix, c)
		if !taken[cand] {
			return cand, nil
		}
	}
	return "", fmt.Errorf("cannot auto-allocate a sub-id under %q: all 26 letter slots (a–z) are used — this group is full; restructure into smaller groups (the -bN brick level is unbounded if a large flat group is genuinely needed)", parentID)
}

// nextQuestionID returns the next free question id (q<N>).
func nextQuestionID(reg *Registry, ledger map[string]bool) string {
	maxN := 0
	for _, q := range reg.Questions {
		if questionIDRe.MatchString(q.ID) {
			k := parseQSortKey(q.ID)
			if k.letter == "" && k.n > maxN {
				maxN = k.n
			}
		}
	}
	for id := range ledger {
		if questionIDRe.MatchString(id) {
			k := parseQSortKey(id)
			if k.letter == "" && k.n > maxN {
				maxN = k.n
			}
		}
	}
	return fmt.Sprintf("q%d", maxN+1)
}
