// Code generated by enctab-gen. DO NOT EDIT.
// Exception: the 0-operand ret form below is manually added (see comment).

package aarch64enc

var generatedForms = []Form{
	{MnemonicID: 0, Pattern: 0xd503201f, Mask: 0xffffffff, Slots: []OperandSlot{}},
	{MnemonicID: 1, Pattern: 0x11000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 1, Pattern: 0x91000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	// 0-operand ret is an alias for ret x30 (ARM ARM C6-1160).
	// The MRA only encodes the 1-operand form; this bare form has x30 baked in.
	// Pattern 0xd65f03c0 = ret with Rn=30 (x30); mask=0xffffffff (fully fixed).
	// Manually added; regenerating from MRA will overwrite — re-add if so.
	{MnemonicID: 12, Pattern: 0xd65f03c0, Mask: 0xffffffff, Slots: []OperandSlot{}},
	{MnemonicID: 12, Pattern: 0xd65f0000, Mask: 0xfffffc1f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
	}},
}

func init() {
	FormsForMnemonic = func(id uint16) []Form {
		var out []Form
		for _, f := range generatedForms {
			if f.MnemonicID == id {
				out = append(out, f)
			}
		}
		return out
	}
}
