// Code generated by enctab-gen. DO NOT EDIT.
// Exception: many forms are manually added after each regeneration.
// See docs/notes/m2-status.md for the list of manual additions and why.
// The 0-operand ret form (Pattern=0xd65f03c0) must also be re-added.

package aarch64enc

var generatedForms = []Form{
	// nop (ID 0)
	{MnemonicID: 0, Pattern: 0xd503201f, Mask: 0xffffffff, Slots: []OperandSlot{}},

	// add (ID 1) — immediate forms
	{MnemonicID: 1, Pattern: 0x11000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 1, Pattern: 0x91000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	// add (ID 1) — 2-register alias forms (add Rd, Rn = add Rd, Rn, #0)
	{MnemonicID: 1, Pattern: 0x11000000, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
	}},
	{MnemonicID: 1, Pattern: 0x91000000, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
	}},

	// sub (ID 2) — immediate forms
	{MnemonicID: 2, Pattern: 0x51000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 2, Pattern: 0xd1000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},

	// mov (ID 3) — alias for add Rd, Rn, #0 (2-register)
	{MnemonicID: 3, Pattern: 0x11000000, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
	}},
	{MnemonicID: 3, Pattern: 0x91000000, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
	}},
	// mov Xd, SP / mov SP, Xn — ADD immediate #0 with SP operand (ARM ARM C6.2.128).
	// Pattern: 0x91000000 (64-bit ADD imm #0). XregOrSp in destination or source.
	{MnemonicID: 3, Pattern: 0x91000000, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 0, BitWidth: 5}, // Rd (SP)
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},    // Rn
	}},
	{MnemonicID: 3, Pattern: 0x91000000, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},     // Rd
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 5, BitWidth: 5}, // Rn (SP)
	}},
	{MnemonicID: 3, Pattern: 0x91000000, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 0, BitWidth: 5}, // Rd (SP)
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 5, BitWidth: 5}, // Rn (SP)
	}},
	// mov (ID 3) — movz alias (mov Rd, #imm16)
	{MnemonicID: 3, Pattern: 0x52800000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Imm16Shifted, ExpectedKind: 5, BitPosition: 5, BitWidth: 16},
	}},
	{MnemonicID: 3, Pattern: 0xd2800000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Imm16Shifted, ExpectedKind: 5, BitPosition: 5, BitWidth: 16},
	}},

	// mvn (ID 4) — ORN Rd, XZR, Rm (bitwise NOT). ARM ARM C6.2.143.
	// 32-bit: sf=0, op=0, S=0, 01010, shift=00, N=1, Rm, imm6=0, Rn=11111, Rd
	// 0x2a2003e0 has Rn=11111 at bits9:5 and N=1 at bit21 baked.
	{MnemonicID: 4, Pattern: 0x2a2003e0, Mask: 0xffe0ffe0, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},  // Rd
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5}, // Rm
	}},
	// 64-bit: 0xaa2003e0
	{MnemonicID: 4, Pattern: 0xaa2003e0, Mask: 0xffe0ffe0, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Rd
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5}, // Rm
	}},

	// ldr (ID 5) — handled by encodeMemInst
	{MnemonicID: 5, Pattern: 0xb9400000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 5, Pattern: 0xf9400000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},

	// str (ID 6) — handled by encodeMemInst
	{MnemonicID: 6, Pattern: 0xb9000000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 6, Pattern: 0xf9000000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},

	// b (ID 9) — unconditional branch
	{MnemonicID: 9, Pattern: 0x14000000, Mask: 0xfc000000, Slots: []OperandSlot{
		{SlotKind: BranchImm26, ExpectedKind: 5, BitPosition: 0, BitWidth: 26},
	}},
	// bl (ID 10)
	{MnemonicID: 10, Pattern: 0x94000000, Mask: 0xfc000000, Slots: []OperandSlot{
		{SlotKind: BranchImm26, ExpectedKind: 5, BitPosition: 0, BitWidth: 26},
	}},

	// Manually added: 0-operand ret = ret x30 (ARM ARM C6-1160). Re-add after each regen.
	{MnemonicID: 12, Pattern: 0xd65f03c0, Mask: 0xffffffff, Slots: []OperandSlot{}},
	// ret (ID 12) — 1-operand form
	{MnemonicID: 12, Pattern: 0xd65f0000, Mask: 0xfffffc1f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
	}},

	// adrp (ID 13)
	{MnemonicID: 13, Pattern: 0x90000000, Mask: 0x9f000000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: AdrpImm, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},

	// and (ID 14) — AND immediate. ARM ARM C6.2.11.
	// 32-bit: sf=0, opc=00, 100100: 0x12000000
	{MnemonicID: 14, Pattern: 0x12000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// 64-bit: 0x92000000
	{MnemonicID: 14, Pattern: 0x92000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// and (ID 14) — AND shifted-register (3 registers, no shift).
	// 32-bit: sf=0, shift=00, N=0, imm6=0: 0x0a000000, mask 0xffe0fc00
	{MnemonicID: 14, Pattern: 0x0a000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	// 64-bit: 0x8a000000
	{MnemonicID: 14, Pattern: 0x8a000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// orr (ID 15) — ORR immediate. ARM ARM C6.2.155.
	// 32-bit: sf=0, opc=01, 100100: 0x32000000
	{MnemonicID: 15, Pattern: 0x32000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// 64-bit: 0xb2000000
	{MnemonicID: 15, Pattern: 0xb2000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// orr (ID 15) — ORR shifted-register (3 registers).
	// 32-bit: 0x2a000000, 64-bit: 0xaa000000
	{MnemonicID: 15, Pattern: 0x2a000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 15, Pattern: 0xaa000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// eor (ID 16) — EOR immediate. ARM ARM C6.2.76.
	// 32-bit: 0x52000000, 64-bit: 0xd2000000
	{MnemonicID: 16, Pattern: 0x52000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	{MnemonicID: 16, Pattern: 0xd2000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// eor (ID 16) — EOR shifted-register.
	// 32-bit: 0x4a000000, 64-bit: 0xca000000
	{MnemonicID: 16, Pattern: 0x4a000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 16, Pattern: 0xca000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// lsl (ID 17) — alias of UBFM. Encoded specially in pass2 (encodeLSLSR).
	// 32-bit UBFM base: 0x53000000, 64-bit: 0xd3400000
	{MnemonicID: 17, Pattern: 0x53000000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
	}},
	{MnemonicID: 17, Pattern: 0xd3400000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
	}},

	// lsr (ID 18) — alias of UBFM. Same forms as lsl; encoder uses different logic.
	{MnemonicID: 18, Pattern: 0x53000000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
	}},
	{MnemonicID: 18, Pattern: 0xd3400000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
	}},

	// cmp (ID 19) — CMP immediate = SUBS Rd=xzr.
	{MnemonicID: 19, Pattern: 0x7100001f, Mask: 0xff80001f, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 19, Pattern: 0xf100001f, Mask: 0xff80001f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	// Manually added: CMP shifted-register 64-bit (SUBS xzr, Xn, Xm). ARM ARM C6.2.69.
	{MnemonicID: 19, Pattern: 0xeb00001f, Mask: 0xffe0fc1f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},  // Rn
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5}, // Rm
	}},

	// cbz (ID 20)
	{MnemonicID: 20, Pattern: 0x34000000, Mask: 0xff000000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 20, Pattern: 0xb4000000, Mask: 0xff000000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	// cbnz (ID 21)
	{MnemonicID: 21, Pattern: 0x35000000, Mask: 0xff000000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 21, Pattern: 0xb5000000, Mask: 0xff000000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},

	// Manually added: CSEL (64-bit). ARM ARM C6.2.52.
	{MnemonicID: 24, Pattern: 0x9a800000, Mask: 0xffe00c00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},
	// Manually added: CSINC (64-bit). ARM ARM C6.2.54.
	{MnemonicID: 25, Pattern: 0x9a800400, Mask: 0xffe00c00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},

	// b.eq .. b.nv (IDs 26..41) — expanded from b_cond.xml
	{MnemonicID: 26, Pattern: 0x54000000, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 27, Pattern: 0x54000001, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 28, Pattern: 0x54000002, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 29, Pattern: 0x54000003, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 30, Pattern: 0x54000004, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 31, Pattern: 0x54000005, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 32, Pattern: 0x54000006, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 33, Pattern: 0x54000007, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 34, Pattern: 0x54000008, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 35, Pattern: 0x54000009, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 36, Pattern: 0x5400000a, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 37, Pattern: 0x5400000b, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 38, Pattern: 0x5400000c, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 39, Pattern: 0x5400000d, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 40, Pattern: 0x5400000e, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 41, Pattern: 0x5400000f, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	// b.hs = b.cs (cond=2, CS=HS); b.lo = b.cc (cond=3, CC=LO)
	{MnemonicID: 42, Pattern: 0x54000002, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},
	{MnemonicID: 43, Pattern: 0x54000003, Mask: 0xff00001f, Slots: []OperandSlot{
		{SlotKind: BranchImm19, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},

	// blr (ID 44) — Branch with Link to Register. ARM ARM C6.2.31.
	{MnemonicID: 44, Pattern: 0xd63f0000, Mask: 0xfffffc1f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
	}},

	// subs (ID 45) — Subtract Setting Flags (full form). ARM ARM C6.2.251.
	// 32-bit: 0x71000000, 64-bit: 0xf1000000
	{MnemonicID: 45, Pattern: 0x71000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 45, Pattern: 0xf1000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},

	// tst (ID 46) — TST immediate = ANDS Rd=xzr. ARM ARM C6.2.286.
	// 32-bit: 0x7200001f, 64-bit: 0xf200001f
	{MnemonicID: 46, Pattern: 0x7200001f, Mask: 0xff80001f, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	{MnemonicID: 46, Pattern: 0xf200001f, Mask: 0xff80001f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// tst register (ANDS shifted-reg Rd=xzr, no shift, no imm6).
	// 32-bit: 0x6a00001f, 64-bit: 0xea00001f
	{MnemonicID: 46, Pattern: 0x6a00001f, Mask: 0xffe0fc1f, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 46, Pattern: 0xea00001f, Mask: 0xffe0fc1f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// bic (ID 47) — Bit Clear. ARM ARM C6.2.25.
	// BIC immediate = AND-imm with inverted mask. Pass2 handles the inversion.
	// 32-bit AND-imm base: 0x12000000, 64-bit: 0x92000000
	{MnemonicID: 47, Pattern: 0x12000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	{MnemonicID: 47, Pattern: 0x92000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// BIC shifted-register (N=1 bit distinguishes from AND).
	// 32-bit: 0x0a200000, 64-bit: 0x8a200000
	{MnemonicID: 47, Pattern: 0x0a200000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 47, Pattern: 0x8a200000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// adr (ID 48) — PC-relative address. ARM ARM C6.2.10.
	// Pattern: 0x10000000, Mask: 0x9f000000
	{MnemonicID: 48, Pattern: 0x10000000, Mask: 0x9f000000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: AdrImm, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},

	// bfi (ID 49) — Bit Field Insert = BFM alias. ARM ARM C6.2.22.
	// 64-bit BFM: 0xb3400000, 32-bit BFM: 0x33000000
	// immr slot is at bits 21:16, imms at bits 15:10. Pass2 encodes BFI semantics.
	{MnemonicID: 49, Pattern: 0xb3400000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6}, // immr
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6}, // imms
	}},
	{MnemonicID: 49, Pattern: 0x33000000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6}, // immr
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6}, // imms
	}},

	// bfxil (ID 50) — Bit Field Extract and Insert Low = BFM alias. ARM ARM C6.2.23.
	// Same forms as bfi; pass2 uses different immr/imms computation.
	{MnemonicID: 50, Pattern: 0xb3400000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},
	{MnemonicID: 50, Pattern: 0x33000000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},

	// ubfx (ID 51) — Unsigned Bit Field Extract = UBFM alias. ARM ARM C6.2.295.
	// 64-bit UBFM: 0xd3400000, 32-bit UBFM: 0x53000000
	{MnemonicID: 51, Pattern: 0xd3400000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},
	{MnemonicID: 51, Pattern: 0x53000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},

	// csetm (ID 52) — Conditional Set Mask = CSINV Rd, XZR, XZR, !cond. ARM ARM C6.2.58.
	// 32-bit CSINV: 0x5a9f03e0 (Rn=11111, Rm=11111 baked). Pass2 inverts condition.
	{MnemonicID: 52, Pattern: 0x5a9f03e0, Mask: 0xffff0fe0, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},
	// 64-bit CSINV: 0xda9f03e0
	{MnemonicID: 52, Pattern: 0xda9f03e0, Mask: 0xffff0fe0, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},

	// movk (ID 53) — Move Wide with Keep. ARM ARM C6.2.130.
	// 32-bit: 0x72800000, 64-bit: 0xf2800000
	// hw is encoded in bits [17:16] of the immediate by the parser (parseMovk).
	{MnemonicID: 53, Pattern: 0x72800000, Mask: 0xffe00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Imm16Shifted, ExpectedKind: 5, BitPosition: 5, BitWidth: 16},
	}},
	{MnemonicID: 53, Pattern: 0xf2800000, Mask: 0xffe00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Imm16Shifted, ExpectedKind: 5, BitPosition: 5, BitWidth: 16},
	}},

	// ldrb (ID 54), strb (ID 55), ldrh (ID 56), strh (ID 57):
	// Handled in encodeMemInst. No form-table entries needed (memory forms
	// short-circuit before ValidateOperandKinds in encodeInst).

	// madd (ID 58) — Multiply-Add. ARM ARM C6.2.103.
	// sf=1, 00, 11011, 000, Rm, Ra, Rn, Rd (bit15=0)
	// Pattern: 0x9b000000, Mask: 0xff008000
	{MnemonicID: 58, Pattern: 0x9b000000, Mask: 0xff008000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Rd
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},  // Rn
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5}, // Rm
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 10, BitWidth: 5}, // Ra
	}},

	// msub (ID 59) — Multiply-Subtract. ARM ARM C6.2.120.
	// Same as madd but bit15=1. Pattern: 0x9b008000, Mask: 0xff008000
	{MnemonicID: 59, Pattern: 0x9b008000, Mask: 0xff008000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Rd
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},  // Rn
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5}, // Rm
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 10, BitWidth: 5}, // Ra
	}},

	// umull (ID 60) — Unsigned Multiply Long = UMADDL Xd, Wn, Wm, XZR. ARM ARM C6.2.300.
	// sf=1, 00, 11011, 101, Rm, Ra=11111 baked, Rn, Rd
	// Pattern: 0x9ba07c00 (Ra=11111 at bits14:10 baked), Mask: 0xffe0fc00
	{MnemonicID: 60, Pattern: 0x9ba07c00, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Xd
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},  // Wn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5}, // Wm
	}},

	// umulh (ID 61) — Unsigned Multiply High. ARM ARM C6.2.301.
	// sf=1, 00, 11011, 110, Rm, Ra=00000, Rn, Rd
	// Pattern: 0x9bc00000, Mask: 0xffe0fc00
	{MnemonicID: 61, Pattern: 0x9bc00000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Xd
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},  // Xn
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5}, // Xm
	}},

	// umaddl (ID 62) — Unsigned Multiply-Add Long. ARM ARM C6.2.297.
	// sf=1, 00, 11011, 101, Rm, Ra, Rn, Rd (bit15=0)
	// Pattern: 0x9ba00000, Mask: 0xff008000
	{MnemonicID: 62, Pattern: 0x9ba00000, Mask: 0xff008000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Xd
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},  // Wn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5}, // Wm
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 10, BitWidth: 5}, // Xa
	}},

	// umsubl (ID 63) — Unsigned Multiply-Subtract Long. ARM ARM C6.2.298.
	// Same as umaddl but bit15=1. Pattern: 0x9ba08000, Mask: 0xff008000
	{MnemonicID: 63, Pattern: 0x9ba08000, Mask: 0xff008000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Xd
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},  // Wn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5}, // Wm
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 10, BitWidth: 5}, // Xa
	}},
}

func init() {
	FormsForMnemonic = func(id uint16) []Form {
		var out []Form
		for _, f := range generatedForms {
			if f.MnemonicID == id {
				out = append(out, f)
			}
		}
		return out
	}
}
