// Code generated by enctab-gen. DO NOT EDIT.

package aarch64enc

var generatedForms = []Form{
	{MnemonicID: 0, Pattern: 0xd503201f, Mask: 0xffffffff, Slots: []OperandSlot{}},
	{MnemonicID: 1, Pattern: 0x11000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
	}},
	{MnemonicID: 1, Pattern: 0x91000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
	}},
	{MnemonicID: 12, Pattern: 0xd65f0000, Mask: 0xfffffc1f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
	}},
}

func init() {
	FormsForMnemonic = func(id uint16) []Form {
		var out []Form
		for _, f := range generatedForms {
			if f.MnemonicID == id {
				out = append(out, f)
			}
		}
		return out
	}
}
