package aarch64enc

// Hand-curated Form definitions.  NOT regenerated by enctab-gen.
//
// The companion file data.go is the MRA-derived half of the encoder
// table — every entry there comes from the vendored ARM MRA snapshot
// and is rewritten verbatim by `make enctab-regen-source`.  This file
// holds everything that the MRA snapshot does NOT cover:
//
//   - mnemonics whose XML simply isn't in reference/arm-mra/ yet (mvn,
//     br, lsl/lsr, csel, csinc, csetm, bfi, bfxil, ubfx, sbfx, tst,
//     bic, adr, eor, orr (shifted-reg), and, ands, movk, movn, madd,
//     msub, umull, umulh, umaddl, umsubl, eret, wfi, ror, mul, udiv,
//     sxtw, bfc, ... and all the spectrum4 pseudo-mnemonics);
//
//   - encoder choices that differ from the MRA's preferred alias.  The
//     load-bearing example is `mov Xd, Xn`: the MRA emits the ADD-imm-#0
//     alias (ID 3, pattern 0x91000000), but GNU as prefers ORR Rd, XZR,
//     Rm (0xaa0003e0).  We list the ORR forms in manualForms; because
//     `Forms()` puts manual entries first, ORR wins the linear scan
//     in matchOperandKinds and the byte-match builds stay green.
//
//   - register-form variants of mnemonics whose MRA entry only carries
//     the alias form (e.g. CMP shifted-register surfaces as SUBS WZR/XZR
//     in MRA; we add the (Rn, Rm) shifted-register slots here);
//
//   - the bare 0-operand `ret` (= `ret x30`) — the MRA's `ret.xml`
//     defines only the 1-operand form, but assembly source routinely
//     writes plain `ret`.
//
// Adding new manual forms: append to manualForms below.  No regen step
// is required — `make enctab-regen-source` only touches data.go.
//
// Cited section/page references for each block are inline.  See
// https://github.com/petemoore/sam-aarch64/blob/c0f62fa/docs/notes/m2-status.md for the higher-level history of why this
// table is hand-curated rather than fully MRA-derived.

var manualForms = []Form{
	// -----------------------------------------------------------------
	// mov (ID 3) — register form: ORR Rd, XZR, Rm.  ARM ARM C6.2.130.
	//
	// The MRA's mov_add_addsub_imm.xml expresses `mov Rd, Rn` as the
	// ADD Rd, Rn, #0 alias (also in generatedForms with mask
	// 0xfffffc00).  GNU as instead emits ORR Rd, XZR, Rm (Rn=11111
	// baked).  manualForms is consulted first so the ORR form wins.
	//   32-bit: 0x2a0003e0 | (Rm<<16) | Rd  (Rn=11111 baked).
	//   64-bit: 0xaa0003e0 | (Rm<<16) | Rd.
	{MnemonicID: 3, Pattern: 0x2a0003e0, Mask: 0xffe0ffe0, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 3, Pattern: 0xaa0003e0, Mask: 0xffe0ffe0, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// mov Xd, SP / mov SP, Xn — ADD immediate #0 with SP operand.
	// ARM ARM C6.2.128.  Pattern: 0x91000000 (64-bit ADD imm #0).
	// XregOrSp in destination or source.
	{MnemonicID: 3, Pattern: 0x91000000, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 0, BitWidth: 5}, // Rd (SP)
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},    // Rn
	}},
	{MnemonicID: 3, Pattern: 0x91000000, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},     // Rd
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 5, BitWidth: 5}, // Rn (SP)
	}},
	{MnemonicID: 3, Pattern: 0x91000000, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 0, BitWidth: 5}, // Rd (SP)
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 5, BitWidth: 5}, // Rn (SP)
	}},

	// -----------------------------------------------------------------
	// add (ID 1) — SP-form: `add Xd, sp, #imm` and `add sp, Xn, #imm`
	// and `add sp, sp, #imm`.  Same encoding as 64-bit ADD-imm but
	// with XregOrSp in one or both register slots.
	{MnemonicID: 1, Pattern: 0x91000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 0, BitWidth: 5},
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 1, Pattern: 0x91000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 1, Pattern: 0x91000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},

	// sub (ID 2) — SP-form: `sub sp, sp, #imm` and friends.
	{MnemonicID: 2, Pattern: 0xd1000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 0, BitWidth: 5},
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 2, Pattern: 0xd1000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 2, Pattern: 0xd1000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},

	// -----------------------------------------------------------------
	// mvn (ID 4) — ORN Rd, XZR, Rm (bitwise NOT).  ARM ARM C6.2.143.
	// 32-bit: sf=0, op=0, S=0, 01010, shift=00, N=1, Rm, imm6=0,
	//         Rn=11111, Rd  → 0x2a2003e0 (Rn=11111 at bits 9:5,
	//         N=1 at bit 21 baked).
	// 64-bit: 0xaa2003e0.
	{MnemonicID: 4, Pattern: 0x2a2003e0, Mask: 0xffe0ffe0, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 4, Pattern: 0xaa2003e0, Mask: 0xffe0ffe0, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// -----------------------------------------------------------------
	// br (ID 11) — Branch to Register.  ARM ARM C6.2.36.
	// 1101_0110_0001_1111_0000_00 Rn 00000 = 0xd61f0000 | (Rn<<5).
	{MnemonicID: 11, Pattern: 0xd61f0000, Mask: 0xfffffc1f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
	}},

	// blr (ID 44) — Branch with Link to Register.  ARM ARM C6.2.31 / C6.2.37.
	// 1101_0110_0011_1111_0000_00 Rn 00000 = 0xd63f0000 | (Rn<<5).
	{MnemonicID: 44, Pattern: 0xd63f0000, Mask: 0xfffffc1f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
	}},

	// 0-operand ret (= `ret x30`).  ARM ARM C6-1160.  The MRA's
	// ret.xml only defines the 1-operand form (1<<5 | Rn).
	{MnemonicID: 12, Pattern: 0xd65f03c0, Mask: 0xffffffff, Slots: []OperandSlot{}},

	// -----------------------------------------------------------------
	// and (ID 14) — AND immediate, SP-form: `and sp, Xn, #imm`.
	// Allowed when SP is the destination (useful for stack-align masks).
	{MnemonicID: 14, Pattern: 0x92000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: XregOrSp, ExpectedKind: 3, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// and (ID 14) — AND immediate (3 registers — i.e. AND-imm with two
	// plain Wreg/Xreg operands; the MRA snapshot lacks an and.xml).
	// 32-bit: sf=0, opc=00, 100100 → 0x12000000.
	// 64-bit: 0x92000000.
	{MnemonicID: 14, Pattern: 0x12000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	{MnemonicID: 14, Pattern: 0x92000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// and (ID 14) — AND shifted-register (3 registers, no shift).
	// 32-bit: sf=0, shift=00, N=0, imm6=0 → 0x0a000000, mask 0xffe0fc00.
	// 64-bit: 0x8a000000.
	{MnemonicID: 14, Pattern: 0x0a000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 14, Pattern: 0x8a000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// orr (ID 15) — ORR immediate.  ARM ARM C6.2.155.
	// 32-bit: sf=0, opc=01, 100100 → 0x32000000.
	// 64-bit: 0xb2000000.
	{MnemonicID: 15, Pattern: 0x32000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	{MnemonicID: 15, Pattern: 0xb2000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// orr (ID 15) — ORR shifted-register (3 registers).
	// 32-bit: 0x2a000000, 64-bit: 0xaa000000.
	{MnemonicID: 15, Pattern: 0x2a000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 15, Pattern: 0xaa000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// eor (ID 16) — EOR immediate.  ARM ARM C6.2.76.
	// 32-bit: 0x52000000, 64-bit: 0xd2000000.
	{MnemonicID: 16, Pattern: 0x52000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	{MnemonicID: 16, Pattern: 0xd2000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// eor (ID 16) — EOR shifted-register.
	// 32-bit: 0x4a000000, 64-bit: 0xca000000.
	{MnemonicID: 16, Pattern: 0x4a000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 16, Pattern: 0xca000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// -----------------------------------------------------------------
	// lsl (ID 17) — alias of UBFM.  Encoded specially in pass2
	// (encodeLSLSR).  32-bit UBFM base: 0x53000000.  64-bit: 0xd3400000.
	{MnemonicID: 17, Pattern: 0x53000000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
	}},
	{MnemonicID: 17, Pattern: 0xd3400000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
	}},

	// lsr (ID 18) — alias of UBFM.  Same forms as lsl; encoder uses
	// different logic.
	{MnemonicID: 18, Pattern: 0x53000000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
	}},
	{MnemonicID: 18, Pattern: 0xd3400000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
	}},

	// -----------------------------------------------------------------
	// cmp (ID 19) — shifted-register: SUBS xzr/wzr, Rn, Rm.
	// ARM ARM C6.2.69.  The MRA's cmp_subs_addsub_imm.xml carries only
	// the immediate form.
	{MnemonicID: 19, Pattern: 0xeb00001f, Mask: 0xffe0fc1f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},  // Rn
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5}, // Rm
	}},
	{MnemonicID: 19, Pattern: 0x6b00001f, Mask: 0xffe0fc1f, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},  // Rn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5}, // Rm
	}},

	// -----------------------------------------------------------------
	// csel (ID 24) — Conditional Select.  ARM ARM C6.2.52.
	{MnemonicID: 24, Pattern: 0x9a800000, Mask: 0xffe00c00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},
	{MnemonicID: 24, Pattern: 0x1a800000, Mask: 0xffe00c00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},

	// csinc (ID 25) — Conditional Select Increment.  ARM ARM C6.2.54.
	{MnemonicID: 25, Pattern: 0x1a800400, Mask: 0xffe00c00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},
	{MnemonicID: 25, Pattern: 0x9a800400, Mask: 0xffe00c00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},

	// -----------------------------------------------------------------
	// subs (ID 45) — Subtract Setting Flags (full 3-operand form).
	// ARM ARM C6.2.251.  The MRA's cmp_subs_addsub_imm.xml emits only
	// the SUBS WZR/XZR alias (== cmp); add the full Rd form here.
	// 32-bit: 0x71000000, 64-bit: 0xf1000000.
	{MnemonicID: 45, Pattern: 0x71000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 45, Pattern: 0xf1000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},

	// -----------------------------------------------------------------
	// tst (ID 46) — TST immediate = ANDS Rd=xzr.  ARM ARM C6.2.286.
	// 32-bit: 0x7200001f, 64-bit: 0xf200001f.
	{MnemonicID: 46, Pattern: 0x7200001f, Mask: 0xff80001f, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	{MnemonicID: 46, Pattern: 0xf200001f, Mask: 0xff80001f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// tst register (ANDS shifted-reg Rd=xzr, no shift, no imm6).
	// 32-bit: 0x6a00001f, 64-bit: 0xea00001f.
	{MnemonicID: 46, Pattern: 0x6a00001f, Mask: 0xffe0fc1f, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 46, Pattern: 0xea00001f, Mask: 0xffe0fc1f, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// -----------------------------------------------------------------
	// bic (ID 47) — Bit Clear.  ARM ARM C6.2.25.  BIC-immediate is
	// AND-imm with inverted mask; pass2 inverts.  Shifted-register
	// distinguishes via N=1 bit.
	{MnemonicID: 47, Pattern: 0x12000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	{MnemonicID: 47, Pattern: 0x92000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	{MnemonicID: 47, Pattern: 0x0a200000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 47, Pattern: 0x8a200000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// -----------------------------------------------------------------
	// adr (ID 48) — PC-relative address.  ARM ARM C6.2.10.
	{MnemonicID: 48, Pattern: 0x10000000, Mask: 0x9f000000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: AdrImm, ExpectedKind: 5, BitPosition: 5, BitWidth: 19},
	}},

	// -----------------------------------------------------------------
	// bfi (ID 49) — Bit Field Insert = BFM alias.  ARM ARM C6.2.22.
	// immr at bits 21:16, imms at bits 15:10.  Pass2 encodes BFI
	// semantics from (lsb, width).
	{MnemonicID: 49, Pattern: 0xb3400000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},
	{MnemonicID: 49, Pattern: 0x33000000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},

	// bfxil (ID 50) — Bit Field Extract and Insert Low = BFM alias.
	// ARM ARM C6.2.23.  Same slot shape as bfi; pass2 uses different
	// immr/imms computation.
	{MnemonicID: 50, Pattern: 0xb3400000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},
	{MnemonicID: 50, Pattern: 0x33000000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},

	// ubfx (ID 51) — Unsigned Bit Field Extract = UBFM alias.
	// ARM ARM C6.2.295.
	{MnemonicID: 51, Pattern: 0xd3400000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},
	{MnemonicID: 51, Pattern: 0x53000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},

	// csetm (ID 52) — Conditional Set Mask = CSINV Rd, XZR, XZR, !cond.
	// ARM ARM C6.2.58.  Pass2 inverts the condition.
	{MnemonicID: 52, Pattern: 0x5a9f03e0, Mask: 0xffff0fe0, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},
	{MnemonicID: 52, Pattern: 0xda9f03e0, Mask: 0xffff0fe0, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},

	// movk (ID 53) — Move Wide with Keep.  ARM ARM C6.2.130.  hw is
	// encoded in bits [17:16] of the immediate by parseMovk.
	// 32-bit: 0x72800000, 64-bit: 0xf2800000.
	{MnemonicID: 53, Pattern: 0x72800000, Mask: 0xffe00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Imm16Shifted, ExpectedKind: 5, BitPosition: 5, BitWidth: 16},
	}},
	{MnemonicID: 53, Pattern: 0xf2800000, Mask: 0xffe00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Imm16Shifted, ExpectedKind: 5, BitPosition: 5, BitWidth: 16},
	}},

	// -----------------------------------------------------------------
	// madd (ID 58) — Multiply-Add.  ARM ARM C6.2.103.
	// 32-bit: sf=0 → 0x1b000000.  64-bit: sf=1 → 0x9b000000.
	{MnemonicID: 58, Pattern: 0x1b000000, Mask: 0xff008000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},  // Rd
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},  // Rn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5}, // Rm
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 10, BitWidth: 5}, // Ra
	}},
	{MnemonicID: 58, Pattern: 0x9b000000, Mask: 0xff008000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Rd
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},  // Rn
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5}, // Rm
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 10, BitWidth: 5}, // Ra
	}},

	// msub (ID 59) — Multiply-Subtract.  ARM ARM C6.2.120.  bit15=1.
	// 32-bit: sf=0 → 0x1b008000.  64-bit: sf=1 → 0x9b008000.
	{MnemonicID: 59, Pattern: 0x1b008000, Mask: 0xff008000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},  // Rd
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},  // Rn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5}, // Rm
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 10, BitWidth: 5}, // Ra
	}},
	{MnemonicID: 59, Pattern: 0x9b008000, Mask: 0xff008000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Rd
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},  // Rn
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5}, // Rm
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 10, BitWidth: 5}, // Ra
	}},

	// umull (ID 60) — Unsigned Multiply Long = UMADDL Xd, Wn, Wm, XZR.
	// ARM ARM C6.2.300.  Ra=11111 baked at bits 14:10.
	{MnemonicID: 60, Pattern: 0x9ba07c00, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Xd
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},  // Wn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5}, // Wm
	}},

	// umulh (ID 61) — Unsigned Multiply High.  ARM ARM C6.2.301.
	{MnemonicID: 61, Pattern: 0x9bc07c00, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Xd
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},  // Xn
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5}, // Xm
	}},

	// umaddl (ID 62) — Unsigned Multiply-Add Long.  ARM ARM C6.2.297.
	{MnemonicID: 62, Pattern: 0x9ba00000, Mask: 0xff008000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Xd
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},  // Wn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5}, // Wm
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 10, BitWidth: 5}, // Xa
	}},

	// umsubl (ID 63) — Unsigned Multiply-Subtract Long.  ARM ARM C6.2.298.
	{MnemonicID: 63, Pattern: 0x9ba08000, Mask: 0xff008000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Xd
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},  // Wn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5}, // Wm
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 10, BitWidth: 5}, // Xa
	}},

	// eret (ID 65) — Exception Return (no operand).  ARM ARM C6.2.84.
	{MnemonicID: 65, Pattern: 0xd69f03e0, Mask: 0xffffffff, Slots: []OperandSlot{}},

	// wfi (ID 69) — Wait For Interrupt (no operand).  ARM ARM C6.2.305.
	{MnemonicID: 69, Pattern: 0xd503207f, Mask: 0xffffffff, Slots: []OperandSlot{}},

	// isb (ID 66), dsb (ID 67), dmb (ID 68) take a single OpImmExpr
	// operand carrying the CRm field value (encoded by the parser from
	// a barrier-arg keyword).  pass2 (encodeBarrierInst) takes the
	// pattern and ORs the CRm into bits 11:8.
	//   isb base: 0xd50330df | (crm << 8)   (sy is default, crm=0xf)
	//   dsb base: 0xd503309f | (crm << 8)
	//   dmb base: 0xd50330bf | (crm << 8)

	// ror (ID 70) — register form RORV.  ARM ARM C6.2.197.  Immediate
	// form (ror Rd, Rn, #imm) is handled by encodeRorImm in pass2
	// because Rn appears in two slots of the underlying EXTR.
	{MnemonicID: 70, Pattern: 0x1ac02c00, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},  // Rd
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},  // Rn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5}, // Rm
	}},
	{MnemonicID: 70, Pattern: 0x9ac02c00, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},  // Rd
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},  // Rn
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5}, // Rm
	}},

	// mul (ID 71) — alias of MADD Rd,Rn,Rm,XZR.  ARM ARM C6.2.139.
	// Ra=11111 (XZR) baked at bits 14:10.
	{MnemonicID: 71, Pattern: 0x1b007c00, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 71, Pattern: 0x9b007c00, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// udiv (ID 72) — Unsigned Divide.  ARM ARM C6.2.222.
	{MnemonicID: 72, Pattern: 0x1ac00800, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 72, Pattern: 0x9ac00800, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// sdiv (ID 99) — Signed Divide.  ARM ARM C6.2.202.
	// Mirrors udiv (ID 72) exactly with opcode bit10 set:
	// udiv base 0x1ac00800 (opcode 000010), sdiv base 0x1ac00c00 (opcode 000011).
	{MnemonicID: 99, Pattern: 0x1ac00c00, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 99, Pattern: 0x9ac00c00, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// sxtw (ID 73) — Sign-extend Word; alias of SBFM Xd,Xn,0,31.
	// ARM ARM C6.2.214.  immr=0, imms=31 baked.
	{MnemonicID: 73, Pattern: 0x93407c00, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
	}},

	// ands (ID 81) — AND setting flags.  ARM ARM C6.2.13 / C6.2.14.
	// Immediate form:  32-bit 0x72000000, 64-bit 0xf2000000.
	{MnemonicID: 80, Pattern: 0x72000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	{MnemonicID: 80, Pattern: 0xf2000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: LogicalImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 13},
	}},
	// Shifted-register form, no shift (3 plain registers).
	// 32-bit: 0x6a000000, 64-bit: 0xea000000.
	{MnemonicID: 80, Pattern: 0x6a000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
	}},
	{MnemonicID: 80, Pattern: 0xea000000, Mask: 0xffe0fc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
	}},

	// movn (ID 83) — Move Wide with Not.  ARM ARM C6.2.129.
	// 32-bit: 0x12800000, 64-bit: 0x92800000.
	{MnemonicID: 82, Pattern: 0x12800000, Mask: 0xffe00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Imm16Shifted, ExpectedKind: 5, BitPosition: 5, BitWidth: 16},
	}},
	{MnemonicID: 82, Pattern: 0x92800000, Mask: 0xffe00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Imm16Shifted, ExpectedKind: 5, BitPosition: 5, BitWidth: 16},
	}},

	// bfc (ID 84) — Bit Field Clear.  ARM ARM C6.2.21.  Alias of
	// BFI Rd, XZR, #lsb, #width.  Encoded via encodeBfc in pass2.
	// Form table reserves the slot shape; pass2 routes by mnemonic ID.
	// Rn baked as 11111.
	{MnemonicID: 83, Pattern: 0xb34003e0, Mask: 0xffc003e0, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},
	{MnemonicID: 83, Pattern: 0x330003e0, Mask: 0xffc003e0, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},

	// sbfx (ID 85) — Signed Bit Field Extract = SBFM alias.
	// ARM ARM C6.2.205.
	{MnemonicID: 84, Pattern: 0x93400000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},
	{MnemonicID: 84, Pattern: 0x13000000, Mask: 0xffc00000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 16, BitWidth: 6},
		{SlotKind: BitfieldImm, ExpectedKind: 5, BitPosition: 10, BitWidth: 6},
	}},

	// -----------------------------------------------------------------
	// ccmp (ID 88) — Conditional Compare.  ARM ARM C6.2.43 (immediate)
	// and C6.2.44 (register).
	//
	// Encoding (per the ARMv8 ARM):
	//
	//   immediate: sf 1 1 1 1 0 1 0 0 1 0 imm5 cond 1 0 Rn 0 nzcv
	//   register:  sf 1 1 1 1 0 1 0 0 1 0  Rm  cond 0 0 Rn 0 nzcv
	//
	// Fixed bits: 31..21, 11..10, 4.  Bit 11 = 1 selects the immediate
	// form (imm5 in 20..16); bit 11 = 0 selects the register form
	// (Rm in 20..16).  Bit 10 = 0 for both.  Bit 4 = 0 for both.
	//
	// Mask: 0xFFE00C10 (top 11 bits + bits 11, 10, 4).
	//
	// Patterns: bits 31..21 give 0xFA400000 (sf=1) or 0x7A400000 (sf=0);
	// immediate forms additionally set bit 11 (|0x800).
	//
	// Both nzcv (bits 3..0) and imm5 (bits 20..16) are unsigned small
	// immediates: SlotKind=Imm5 with BitWidth=4 packs nzcv (4 bits, 0..15)
	// and BitWidth=5 packs imm5 (5 bits, 0..31).  The shared Imm5 / Imm6
	// slot encoder is BitWidth-driven (see slots_trivial.go::encodeImmN).
	//
	// ExpectedKind: OpImmExpr (5) for both nzcv and imm5; the parser
	// emits both as IMM_EXPR operands carrying a constant expression.

	// ccmp Wn, #imm5, #nzcv, cond — 32-bit immediate.
	{MnemonicID: 88, Pattern: 0x7a400800, Mask: 0xffe00c10, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},     // Rn
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 16, BitWidth: 5},    // imm5
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 0, BitWidth: 4},     // nzcv
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4}, // cond
	}},
	// ccmp Xn, #imm5, #nzcv, cond — 64-bit immediate.
	{MnemonicID: 88, Pattern: 0xfa400800, Mask: 0xffe00c10, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},     // Rn
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 16, BitWidth: 5},    // imm5
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 0, BitWidth: 4},     // nzcv
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4}, // cond
	}},
	// ccmp Wn, Wm, #nzcv, cond — 32-bit register.
	{MnemonicID: 88, Pattern: 0x7a400000, Mask: 0xffe00c10, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},     // Rn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},    // Rm
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 0, BitWidth: 4},     // nzcv
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4}, // cond
	}},
	// ccmp Xn, Xm, #nzcv, cond — 64-bit register.
	{MnemonicID: 88, Pattern: 0xfa400000, Mask: 0xffe00c10, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},     // Rn
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},    // Rm
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 0, BitWidth: 4},     // nzcv
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4}, // cond
	}},

	// -----------------------------------------------------------------
	// ccmn (ID 100) — Conditional Compare Negative.  ARM ARM C6.2.41
	// (register) and C6.2.42 (immediate).  Identical encoding to ccmp
	// (ID 88) but with op (bit 30) = 0:
	//
	//   immediate: sf 0 1 1 1 0 1 0 0 1 0 imm5 cond 1 0 Rn 0 nzcv
	//   register:  sf 0 1 1 1 0 1 0 0 1 0  Rm  cond 0 0 Rn 0 nzcv
	//
	// Patterns: 0xba400000 (sf=1) / 0x3a400000 (sf=0); imm forms |0x800.
	// Same mask (0xffe00c10) and same slot layout as ccmp.

	// ccmn Wn, #imm5, #nzcv, cond — 32-bit immediate.
	{MnemonicID: 100, Pattern: 0x3a400800, Mask: 0xffe00c10, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},     // Rn
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 16, BitWidth: 5},    // imm5
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 0, BitWidth: 4},     // nzcv
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4}, // cond
	}},
	// ccmn Xn, #imm5, #nzcv, cond — 64-bit immediate.
	{MnemonicID: 100, Pattern: 0xba400800, Mask: 0xffe00c10, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},     // Rn
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 16, BitWidth: 5},    // imm5
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 0, BitWidth: 4},     // nzcv
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4}, // cond
	}},
	// ccmn Wn, Wm, #nzcv, cond — 32-bit register.
	{MnemonicID: 100, Pattern: 0x3a400000, Mask: 0xffe00c10, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},     // Rn
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},    // Rm
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 0, BitWidth: 4},     // nzcv
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4}, // cond
	}},
	// ccmn Xn, Xm, #nzcv, cond — 64-bit register.
	{MnemonicID: 100, Pattern: 0xba400000, Mask: 0xffe00c10, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},     // Rn
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},    // Rm
		{SlotKind: Imm5, ExpectedKind: 5, BitPosition: 0, BitWidth: 4},     // nzcv
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4}, // cond
	}},

	// -----------------------------------------------------------------
	// csinv (ID 101) / csneg (ID 102) — base 4-operand conditional-select
	// forms.  ARM ARM C6.2.55 / C6.2.56.  Same encoding family as
	// csel (ID 24) / csinc (ID 25):
	//
	//   sf op S 11010100 Rm cond op2 Rn Rd
	//
	//   csinv: op=1 op2=0 → base 0x5a800000 (sf=0) / 0xda800000 (sf=1)
	//   csneg: op=1 op2=1 → base 0x5a800400 (sf=0) / 0xda800400 (sf=1)
	//
	// Mask 0xffe00c00 (matches csel/csinc).  These are the NON-alias base
	// forms; the Rn==Rm alias shapes (csetm/cinv for csinv, cneg for csneg)
	// are decoded by decodeCondSelAlias (aliases.go) ahead of the form
	// walk, so they shadow these for the alias operand patterns — exactly
	// as csel/csinc coexist with cset/cinc.  Adding them here makes the
	// base forms both encodable and decodable, matching binutils which
	// renders e.g. 0xda87b0c5 as `csinv x5, x6, x7, lt`.
	{MnemonicID: 101, Pattern: 0x5a800000, Mask: 0xffe00c00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},
	{MnemonicID: 101, Pattern: 0xda800000, Mask: 0xffe00c00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},
	{MnemonicID: 102, Pattern: 0x5a800400, Mask: 0xffe00c00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 16, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},
	{MnemonicID: 102, Pattern: 0xda800400, Mask: 0xffe00c00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 16, BitWidth: 5},
		{SlotKind: CondCode, ExpectedKind: 10, BitPosition: 12, BitWidth: 4},
	}},

	// -----------------------------------------------------------------
	// udf (ID 89) — Permanently Undefined instruction (ARM ARM C6.2.228).
	// Encoding: bits[31:16]=0 fixed, bits[15:0]=imm16 operand.
	{MnemonicID: 89, Pattern: 0x00000000, Mask: 0xffff0000, Slots: []OperandSlot{
		{SlotKind: Imm16, ExpectedKind: 5, BitPosition: 0, BitWidth: 16},
	}},

	// -----------------------------------------------------------------
	// sxth (ID 90) — Sign-extend Halfword (ARM ARM C6.2.213).
	// Alias of SBFM Rd, Wn, #0, #15; immr=0 imms=15 baked.
	// sxth (W) — SBFM w,w,#0,#15. sf=0 N=0 immr=0 imms=15.
	{MnemonicID: 90, Pattern: 0x13003c00, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
	}},
	// sxth (X) — SBFM x,w,#0,#15. sf=1 N=1 immr=0 imms=15.
	{MnemonicID: 90, Pattern: 0x93403c00, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
	}},

	// -----------------------------------------------------------------
	// sxtb (ID 91) — Sign-extend Byte (ARM ARM C6.2.212).
	// Alias of SBFM Rd, Wn, #0, #7; immr=0 imms=7 baked.
	// sxtb (W) — SBFM w,w,#0,#7. sf=0 N=0 immr=0 imms=7.
	{MnemonicID: 91, Pattern: 0x13001c00, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
	}},
	// sxtb (X) — SBFM x,w,#0,#7. sf=1 N=1 immr=0 imms=7.
	{MnemonicID: 91, Pattern: 0x93401c00, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
	}},

	// -----------------------------------------------------------------
	// uxtb (ID 92) — Unsigned-extend Byte (ARM ARM C6.2.226).
	// Alias of UBFM Wd, Wn, #0, #7; only W-form (sf=0). immr=0 imms=7 baked.
	{MnemonicID: 92, Pattern: 0x53001c00, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
	}},

	// -----------------------------------------------------------------
	// uxth (ID 93) — Unsigned-extend Halfword (ARM ARM C6.2.227).
	// Alias of UBFM Wd, Wn, #0, #15; only W-form (sf=0). immr=0 imms=15 baked.
	{MnemonicID: 93, Pattern: 0x53003c00, Mask: 0xfffffc00, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
	}},

	// -----------------------------------------------------------------
	// adds (ID 98) — Add and Set Flags (full 3-operand form).
	// ARM ARM C6.2.6.  The MRA emits only the ADDS WZR/XZR alias (== cmn);
	// add the full Rd form here, symmetric with subs (ID 45).
	// 32-bit: sf=0 op=0 S=1 10001 → base 0x31000000.
	// 64-bit: sf=1 op=0 S=1 10001 → base 0xb1000000.
	{MnemonicID: 98, Pattern: 0x31000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 0, BitWidth: 5},
		{SlotKind: Wreg, ExpectedKind: 2, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
	{MnemonicID: 98, Pattern: 0xb1000000, Mask: 0xff800000, Slots: []OperandSlot{
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 0, BitWidth: 5},
		{SlotKind: Xreg, ExpectedKind: 1, BitPosition: 5, BitWidth: 5},
		{SlotKind: Imm12Shifted, ExpectedKind: 5, BitPosition: 10, BitWidth: 12},
	}},
}

// ManualForms returns the hand-curated form table.  Exposed so that
// enctab-gen can include the manual forms in the binary enctab.enc
// alongside the MRA-derived `generatedForms`.
func ManualForms() []Form {
	return manualForms
}

// AllForms returns the union of `manualForms` and `generatedForms`,
// with manual entries first.  Order matters: matchOperandKinds picks
// the first form whose ExpectedKind tuple matches, so manual entries
// shadow any same-shape generated entries (e.g. ORR-based `mov Rd, Rm`
// shadowing the MRA's ADD-imm-#0 alias).
func AllForms() []Form {
	out := make([]Form, 0, len(manualForms)+len(generatedForms))
	out = append(out, manualForms...)
	out = append(out, generatedForms...)
	return out
}

func init() {
	FormsForMnemonic = func(id uint16) []Form {
		var out []Form
		for _, f := range manualForms {
			if f.MnemonicID == id {
				out = append(out, f)
			}
		}
		for _, f := range generatedForms {
			if f.MnemonicID == id {
				out = append(out, f)
			}
		}
		return out
	}
}
