#!/usr/bin/env bash
# asm-deps.sh — emit a GNU make fragment mapping every .asm/.inc under src/
# to its transitive pyz80 include closure:
#
#   asm_deps/src/netboot/sd_push.asm := src/netboot/encdrv.asm src/netboot/eeprom.asm ...
#
# The Makefile -includes the generated fragment (build/asm-deps.mk) and each
# pyz80 rule declares `src/top.asm $(asm_deps/src/top.asm)` as its
# prerequisites, so include-graph changes propagate to make automatically and
# hand-maintained (drift-prone) include lists are unnecessary.
#
# Resolution mirrors pyz80's op_INCLUDE: an include path is joined to the
# INCLUDING file's directory. Includes inside `if defined(...)` blocks are
# deliberately over-approximated (always counted): a too-large prerequisite
# set can only cause a spurious rebuild, never a stale artifact.
#
# Includes resolving under build/ (generated files, e.g. the zx0 self-test
# fixture) are emitted as-is — make has rules for them. A missing include
# target is a WARNING, not an error, and its edge is still emitted: a
# legitimately absent file exists (the gitignored private
# src/netboot/bootloader_chunk1_data.asm, q55), and make itself fails with
# "No rule to make target" exactly when a rule whose closure contains the
# missing file is built — the right failure locality.
#
# Usage: tools/asm-deps.sh [--check <Makefile>]
#   (no args)          print the fragment to stdout
#   --check <makefile> additionally verify every $(asm_deps/...) reference in
#                      the given makefile names a scanned file (typo guard: a
#                      misspelled reference expands empty = no prerequisites).
set -euo pipefail
cd "$(dirname "$0")/.."

check_makefile=""
if [ "${1:-}" = "--check" ]; then
    check_makefile="${2:?--check needs a makefile path}"
fi

fragment=$(find src -name '*.asm' -o -name '*.inc' | sort | xargs awk '
function normpath(p,    n, parts, out, i, depth) {
    n = split(p, parts, "/")
    depth = 0
    for (i = 1; i <= n; i++) {
        if (parts[i] == "." || parts[i] == "") continue
        if (parts[i] == "..") { if (depth > 0) depth--; continue }
        out[++depth] = parts[i]
    }
    p = ""
    for (i = 1; i <= depth; i++) p = p (i > 1 ? "/" : "") out[i]
    return p
}
BEGIN {
    # register every scanned file up front so include-free files still get an
    # (empty) closure entry
    for (i = 1; i < ARGC; i++) { scanned[ARGV[i]] = 1; seen[ARGV[i]] = 1 }
}
{
    line = $0
    sub(/;.*/, "", line)
    if (tolower(line) !~ /^[ \t]*include[ \t]/) next
    if (match(line, /"[^"]*"/) == 0) next
    inc = substr(line, RSTART + 1, RLENGTH - 2)
    dir = FILENAME
    sub(/\/[^\/]*$/, "", dir)
    resolved = normpath(dir "/" inc)
    edges[FILENAME] = edges[FILENAME] " " resolved
    scanned[FILENAME] = 1
    seen[FILENAME] = 1
    seen[resolved] = 1
    referenced[resolved] = FILENAME
}
END {
    # warn on referenced files that do not exist (checked once per unique
    # path); build/ paths are generated files with their own make rules
    for (r in referenced) {
        if (r in scanned || r ~ /^build\//) continue
        if (system("test -f " r) != 0)
            printf "asm-deps.sh: warning: %s includes missing file %s\n", referenced[r], r > "/dev/stderr"
    }
    # transitive closure per file (iterative worklist; graph is tiny)
    for (root in seen) {
        if (root !~ /^src\//) continue
        delete visited
        nq = 0
        q[++nq] = root
        visited[root] = 1
        closure = ""
        for (head = 1; head <= nq; head++) {
            n = split(edges[q[head]], deps, " ")
            for (i = 1; i <= n; i++) {
                d = deps[i]
                if (d == "" || d in visited) continue
                visited[d] = 1
                q[++nq] = d
                closure = closure " " d
            }
        }
        # sort the closure for deterministic output
        n = split(closure, cl, " ")
        m = 0
        for (i = 1; i <= n; i++) if (cl[i] != "") sorted[++m] = cl[i]
        for (i = 1; i < m; i++)
            for (j = i + 1; j <= m; j++)
                if (sorted[j] < sorted[i]) { t = sorted[i]; sorted[i] = sorted[j]; sorted[j] = t }
        line = "asm_deps/" root " :="
        for (i = 1; i <= m; i++) line = line " " sorted[i]
        print line
        delete sorted
    }
}
')

echo "# GENERATED by tools/asm-deps.sh — do not edit; do not commit."
echo "$fragment"

if [ -n "$check_makefile" ]; then
    bad=0
    while IFS= read -r ref; do
        if ! grep -q "^asm_deps/$ref :=" <<<"$fragment"; then
            echo "asm-deps.sh: $check_makefile references \$(asm_deps/$ref) but $ref is not a scanned src file" >&2
            bad=1
        fi
    done < <(grep -o '\$(asm_deps/[^)]*)' "$check_makefile" | sed 's/^\$(asm_deps\///; s/)$//' | sort -u)
    [ "$bad" -eq 0 ] || exit 1
fi
