#!/usr/bin/env python3
"""Generate the embedded bootloader DEFB data for the EEPROM bootblock flasher.

Reads a 1024-byte bootloader image (the sibling trinity-autoboot repo's
build/bootloader.bin) and writes a pyz80 source file defining BOOTLOADER_DATA as
1024 DEFB bytes, for eeprom_flash_chunk1.asm to embed and write into chunk 1.

The output is GITIGNORED: it holds the private bootloader (Colin Piggot's boot
block + our patches), kept out of the repo and CI (q55). Run via
`make gen-bootloader-data` after building the bootloader in the sibling repo.

    usage: gen-bootloader-data.py <bootloader.bin> <out.asm>
"""
import sys


def main(argv):
    if len(argv) != 3:
        sys.exit("usage: gen-bootloader-data.py <bootloader.bin> <out.asm>")
    src, dst = argv[1], argv[2]
    try:
        data = open(src, "rb").read()
    except OSError as e:
        sys.exit(f"cannot read bootloader image {src!r}: {e}\n"
                 f"build it first: cd ~/git/trinity-autoboot && make")
    if len(data) != 1024:
        sys.exit(f"{src} is {len(data)} bytes, want 1024 (one EEPROM chunk)")
    lines = [
        "; bootloader_chunk1_data.asm — GENERATED by tools/gen-bootloader-data.py.",
        "; The 1024-byte trinity-autoboot bootloader (chunk 1 = the EEPROM bootblock).",
        "; GITIGNORED: the bootloader is a private artifact (q55). Regenerate with",
        "; `make gen-bootloader-data` after rebuilding it in the sibling repo.",
        "BOOTLOADER_DATA:",
    ]
    for off in range(0, 1024, 16):
        row = data[off:off + 16]
        lines.append("                defb    " + ",".join("&%02X" % b for b in row))
    open(dst, "w").write("\n".join(lines) + "\n")
    print(f"wrote {dst} ({len(data)} bytes)")


if __name__ == "__main__":
    main(sys.argv)
