#!/usr/bin/env bash
# revendor-m6-release.sh — refresh the vendored M6 release fixture.
#
# The m6-release gate (tools/run-m6-release-gate.sh) proves a 3-way
# byte-match (GNU == our Go toolchain == our Z80 toolchain) on a FROZEN,
# vendored spectrum4 release:
#
#   tests/m6/release/release.s     the release flattened into ONE
#                                  self-contained source file (sam-aarch64 -E:
#                                  includes resolved, macros expanded, .if
#                                  evaluated, test suites dropped), comments
#                                  kept, cpp line-markers stripped.
#   tests/m6/release/release.img   the expected output — spectrum4's own
#                                  GNU as+ld+objcopy build of release.img.
#
# Run THIS to regenerate that pair from a spectrum4 checkout — e.g. after
# spectrum4's release.img changes / the kernel adds new instructions.  It:
#   1. ensures the spectrum4 sources are generated (runs spectrum4's
#      tup-under-docker build if targets/release.img is absent);
#   2. re-flattens release.target → release.s via `sam-aarch64 -E`;
#   3. copies release.img;
#   4. runs the gate to confirm all three toolchains still agree.
#
# If step 4 fails, the new release uses instruction forms a toolchain
# doesn't yet cover — extend it, re-run, and commit the refreshed fixture
# together with the toolchain change.
#
# Env:
#   SPECTRUM4_SRC   spectrum4 source tree (default ~/git/spectrum4/src/spectrum4)
#   SKIP_GATE       set to 1 to skip the confirming gate run (e.g. when the
#                   SAM toolchain isn't expected to match yet)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SPECTRUM4_SRC="${SPECTRUM4_SRC:-$HOME/git/spectrum4/src/spectrum4}"
if [ ! -d "$SPECTRUM4_SRC" ]; then
    echo "ERROR: spectrum4 source not found at $SPECTRUM4_SRC" >&2
    echo "       set SPECTRUM4_SRC to your spectrum4 checkout's src/spectrum4 dir." >&2
    exit 2
fi

FIXTURE_DIR="$ROOT/tests/m6/release"
mkdir -p "$FIXTURE_DIR"

RELEASE_IMG="$SPECTRUM4_SRC/targets/release.img"
RELEASE_RUNNER="$SPECTRUM4_SRC/tests/all_suites.runner"

# 1. Ensure spectrum4's generated sources + release.img exist.  spectrum4's
#    tracked tree isn't directly assemblable (.suite / .runner / .gen-s are
#    generated by its tup build); tup-under-docker.sh runs that build.
if [ ! -f "$RELEASE_IMG" ] || [ ! -f "$RELEASE_RUNNER" ]; then
    echo "=== spectrum4 sources not generated — running tup-under-docker ==="
    s4root="$SPECTRUM4_SRC"
    while [ "$s4root" != "/" ] && [ ! -x "$s4root/tup-under-docker.sh" ]; do
        s4root="$(dirname "$s4root")"
    done
    if [ ! -x "$s4root/tup-under-docker.sh" ]; then
        echo "ERROR: could not find tup-under-docker.sh above $SPECTRUM4_SRC" >&2
        echo "       build spectrum4's targets/release.img manually, then re-run." >&2
        exit 2
    fi
    ( cd "$s4root" && ./tup-under-docker.sh src/spectrum4/targets/release.img )
fi

# 2. Flatten release.target → one self-contained source via sam-aarch64 -E,
#    dropping the cpp `# line "<abs-path>"` markers (they'd leak local
#    paths and add noise; they don't affect the assembled bytes).
echo "=== flattening release.target → release.s (sam-aarch64 -E) ==="
make -s sam-aarch64
"$ROOT/build/sam-aarch64" -E \
    -I "$SPECTRUM4_SRC" \
    -I "$SPECTRUM4_SRC/kernel" \
    -I "$SPECTRUM4_SRC/roms" \
    -I "$SPECTRUM4_SRC/tests" \
    -I "$SPECTRUM4_SRC/demo" \
    -I "$SPECTRUM4_SRC/libextra" \
    "$SPECTRUM4_SRC/targets/release.target" \
  | grep -vE '^# [0-9]+ "' > "$FIXTURE_DIR/release.s"

# 3. Vendor the expected GNU image.
install -m 0644 "$RELEASE_IMG" "$FIXTURE_DIR/release.img"

src_sz=$(wc -c < "$FIXTURE_DIR/release.s" | tr -d ' ')
img_sz=$(wc -c < "$FIXTURE_DIR/release.img" | tr -d ' ')
echo
echo "Re-vendored:"
echo "    tests/m6/release/release.s    ($src_sz bytes)"
echo "    tests/m6/release/release.img  ($img_sz bytes)"

# 4. Confirm the 3-way gate still passes (unless explicitly skipped).
if [ "${SKIP_GATE:-0}" = "1" ]; then
    echo
    echo "SKIP_GATE=1 — not running the confirming gate."
    echo "Run it yourself in the dev container: tools/run-m6-release-gate.sh"
    exit 0
fi
echo
echo "=== confirming 3-way gate ==="
exec "$ROOT/tools/run-m6-release-gate.sh"
