package emit

import (
	"bytes"
	"strings"
	"testing"

	enc "github.com/petemoore/sam-aarch64/tools/aarch64enc"
)

func TestRenderGoPackage_Empty(t *testing.T) {
	var buf bytes.Buffer
	if err := RenderGoPackage(&buf, nil); err != nil {
		t.Fatal(err)
	}
	got := buf.String()
	if !strings.Contains(got, "// Code generated by tables-gen. DO NOT EDIT.") {
		t.Errorf("missing generated header")
	}
	if !strings.Contains(got, "package aarch64enc") {
		t.Errorf("missing package decl")
	}
}

func TestRenderGoPackage_NopForm(t *testing.T) {
	forms := []enc.Form{
		{
			MnemonicID: 0,
			Pattern:    0xD503201F,
			Mask:       0xFFFFFFFF,
			Slots:      nil,
		},
	}
	var buf bytes.Buffer
	if err := RenderGoPackage(&buf, forms); err != nil {
		t.Fatal(err)
	}
	got := strings.ToLower(buf.String())
	if !strings.Contains(got, "0xd503201f") {
		t.Errorf("missing NOP pattern in output\n%s", buf.String())
	}
}
