// Package emit writes the generated outputs of tables-gen: the binary
// .enc form table, the Go mirror data.go, and the Z80 sysreg/pstate/dc/tlbi
// tables (.inc).
package emit

import (
	"fmt"
	"io"
	"sort"

	enc "github.com/petemoore/sam-aarch64/tools/aarch64enc"
)

// RenderGoPackage writes a deterministic data.go to w containing just
// the MRA-derived `generatedForms` slice.  The hand-curated forms and
// the `FormsForMnemonic` registration live in
// tools/aarch64enc/manual_forms.go, which this generator never touches.
func RenderGoPackage(w io.Writer, forms []enc.Form) error {
	fmt.Fprintln(w, "// Code generated by tables-gen. DO NOT EDIT.")
	fmt.Fprintln(w, "//")
	fmt.Fprintln(w, "// Regenerate with `make enctab-regen-source`.  This file holds only")
	fmt.Fprintln(w, "// the MRA-derived form table; hand-curated forms (mvn, lsl/lsr, csel,")
	fmt.Fprintln(w, "// shifted-register cmp/tst, spectrum4 mnemonics, etc.) live in the")
	fmt.Fprintln(w, "// sibling file manual_forms.go and are appended at init time.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "package aarch64enc")
	fmt.Fprintln(w)

	sorted := make([]enc.Form, len(forms))
	copy(sorted, forms)
	sort.SliceStable(sorted, func(i, j int) bool {
		return sorted[i].MnemonicID < sorted[j].MnemonicID
	})

	fmt.Fprintln(w, "var generatedForms = []Form{")
	for _, f := range sorted {
		fmt.Fprintf(w, "\t{MnemonicID: %d, Pattern: 0x%08x, Mask: 0x%08x, Slots: []OperandSlot{",
			f.MnemonicID, f.Pattern, f.Mask)
		if len(f.Slots) == 0 {
			fmt.Fprintln(w, "}},")
			continue
		}
		fmt.Fprintln(w)
		for _, s := range f.Slots {
			fmt.Fprintf(w, "\t\t{SlotKind: %s, ExpectedKind: %d, BitPosition: %d, BitWidth: %d},\n",
				s.SlotKind.Name(), uint8(s.ExpectedKind), s.BitPosition, s.BitWidth)
		}
		fmt.Fprintln(w, "\t}},")
	}
	fmt.Fprintln(w, "}")
	return nil
}
