package emit

import (
	"fmt"
	"io"
	"strings"

	format "github.com/petemoore/sam-aarch64/tools/sam-aarch64-format"
)

// RenderMnemonicNamesInc writes the generated src/mnemonic_names.inc: a
// Z80-searchable name→id table for the i48c parser's mnemonic_lookup
// (src/asmparse.asm). It is the runtime-data twin of mnemonic_ids.inc's
// assemble-time MNEM_<NAME> equates — where the equates name an ID the Z80
// already holds, this table lets the Z80 turn a lexed identifier's bytes back
// INTO that ID (the text→overlay editor input path).
//
// Layout: one record per MnemonicTable entry, in table order, so the record's
// position IS its on-disk mnemonic ID (matching format.MnemonicID, which
// returns the slice index). Each record is
//
//	defb <len>          ; name length, 1..255
//	defm "<name>"       ; the <len> raw name bytes (verbatim, '.' included)
//
// followed by a single `defb 0` sentinel (length 0 = end of table). The
// conditional-branch names keep their '.' verbatim here (b.eq is matched as a
// whole identifier, since the lexer treats '.' as an ident-continuation char) —
// unlike the equate suffixes in mnemonic_ids.inc, no sanitisation applies.
//
// The freshness guard `make tables-sync-check` fails if this file drifts from
// `make tables`; the host harness (tools/netboot-oracle/z80/asmparse_test.go)
// additionally drives mnemonic_lookup over every name and asserts the returned
// ID matches format.MnemonicID — a full semantic check against the authority.
func RenderMnemonicNamesInc(w io.Writer) error {
	writeMnemonicNamesHeader(w)
	fmt.Fprintln(w, "MNEM_NAMES:")
	for id, name := range format.MnemonicTable {
		if len(name) == 0 || len(name) > 255 {
			return fmt.Errorf("mnemonic-names emitter: name %q (id %d) has out-of-range length %d", name, id, len(name))
		}
		if strings.ContainsAny(name, "\"\\\n") {
			return fmt.Errorf("mnemonic-names emitter: name %q (id %d) is not a bare defm string", name, id)
		}
		fmt.Fprintf(w, "                defb    %d\n", len(name))
		fmt.Fprintf(w, "                defm    %q          ; id %d\n", name, id)
	}
	fmt.Fprintln(w, "                defb    0          ; sentinel: length 0 ends the table")
	return nil
}

func writeMnemonicNamesHeader(w io.Writer) {
	fmt.Fprintln(w, "; GENERATED by tools/tables-gen — do not edit; regen with make tables")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; mnemonic_names.inc — a length-prefixed name→id lookup table for the i48c")
	fmt.Fprintln(w, "; parser's mnemonic_lookup (src/asmparse.asm). One record per entry in the")
	fmt.Fprintln(w, "; Go authority tools/sam-aarch64-format/mnemonics.go MnemonicTable, in table")
	fmt.Fprintln(w, "; order, so a record's position is its on-disk mnemonic ID (matching")
	fmt.Fprintln(w, "; format.MnemonicID, which returns the slice index).")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; Record:  defb <len> / defm \"<name>\"   (name bytes verbatim, '.' included).")
	fmt.Fprintln(w, "; A trailing `defb 0` (length 0) ends the table.")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; This is the runtime-data twin of mnemonic_ids.inc (assemble-time equates);")
	fmt.Fprintln(w, "; `make tables-sync-check` fails if it drifts from `make tables`.")
	fmt.Fprintln(w)
}
