package emit

import (
	"fmt"
	"io"
	"strings"

	format "github.com/petemoore/sam-aarch64/tools/sam-aarch64-format"
)

// RenderMnemonicIDsInc writes the generated src/mnemonic_ids.inc: a
// `MNEM_<NAME> equ <id>` equate for every entry in the Go authority
// tools/sam-aarch64-format/mnemonics.go MnemonicTable (the index in the slice
// is the on-disk / dispatch mnemonic ID).
//
// The Z80 intercepts (src/intercepts.asm) dispatch on these IDs with bare
// `cp <n>` comparisons; this file lets those sites name the mnemonic instead,
// so a Go-side renumber regenerates the equates and the Z80 follows
// automatically (the lockstep hazard called out in mnemonics.go's policy
// comment). Equates are assembly-time only — zero runtime bytes — so the
// switchover keeps assembler{,-prod}.bin byte-identical.
//
// Name sanitisation: the only non-identifier character in a mnemonic name is
// the '.' in the conditional branches (b.eq, b.hs, …); it becomes '_', and the
// whole name is upper-cased: b.eq → MNEM_B_EQ. The generated names are unique
// because MnemonicTable names are unique and the only collapsed character is
// '.' → '_' (no two distinct names differ only by '.' vs '_').
func RenderMnemonicIDsInc(w io.Writer) error {
	writeMnemonicIDsHeader(w)
	seen := map[string]string{}
	for id, name := range format.MnemonicTable {
		sym := "MNEM_" + mnemSuffix(name)
		if prev, dup := seen[sym]; dup {
			return fmt.Errorf("mnemonic-id emitter: %q and %q both sanitise to %s", prev, name, sym)
		}
		seen[sym] = name
		emitEqu(w, sym, fmt.Sprintf("%d", id), name)
	}
	return nil
}

// mnemSuffix maps a mnemonic name to its equate suffix: '.' → '_', upper-cased.
// Mnemonic names are ASCII [a-z0-9.] only.
func mnemSuffix(name string) string {
	return strings.ToUpper(strings.ReplaceAll(name, ".", "_"))
}

func writeMnemonicIDsHeader(w io.Writer) {
	fmt.Fprintln(w, "; GENERATED by tools/tables-gen — do not edit; regen with make tables")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; mnemonic_ids.inc — MNEM_<NAME> equ <id> for every entry in the Go")
	fmt.Fprintln(w, "; authority tools/sam-aarch64-format/mnemonics.go MnemonicTable (the slice")
	fmt.Fprintln(w, "; index is the on-disk / dispatch mnemonic ID).  The Z80 intercepts")
	fmt.Fprintln(w, "; (src/intercepts.asm) dispatch on these IDs by name instead of a bare")
	fmt.Fprintln(w, "; numeric literal, so a Go-side renumber regenerates the equates and the")
	fmt.Fprintln(w, "; Z80 follows automatically.")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; Conditional-branch names lose their '.' to '_': b.eq → MNEM_B_EQ.")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; Equates only — zero runtime bytes — so the assembler binary is")
	fmt.Fprintln(w, "; byte-identical across the switchover.  The freshness guard")
	fmt.Fprintln(w, "; `make tables-sync-check` fails if this file drifts from `make tables`.")
	fmt.Fprintln(w)
}
