package emit

import (
	"fmt"
	"io"
	"sort"

	format "github.com/petemoore/sam-aarch64/tools/sam-aarch64-format"
)

// RenderSysoptsInc writes the generated src/disasm_sysopts.inc: the Z80
// disassembler's AT / IC / barrier System-group operand tables, projected
// from the Go authority tools/sam-aarch64-format/sysregs.go (ATOps / ICOps /
// BarrierOptions).
//
// It emits three tables that src/disasm.asm consumes:
//
//   - the barrier-option name strings + disasm_sys_baropt_tbl, a 16-entry
//     CRm-indexed table of 16-bit string pointers (0 = no shared name).
//     disasm_sys_emit_baropt handles CRm 0/4 (dsb-only ssbb/pssbb) and the
//     #imm fallback separately, so the dsb-only options are NOT projected
//     into this table.
//   - disasm_sys_at_tbl and disasm_sys_ic_tbl, linear-walk record tables of
//     the form [op1][CRm][op2][NeedsXt][len][name...] terminated by a 0xFF
//     sentinel, walked by disasm_sys_find_atic.
//
// Output is byte-for-byte deterministic and reproduces the previous
// hand-written tables exactly: barrier strings in CRm order, AT/IC records
// sorted by (op1, CRm, op2).
func RenderSysoptsInc(w io.Writer) error {
	bar := format.BarrierOptions()
	at := format.ATOps()
	ic := format.ICOps()

	writeSysoptsHeader(w)

	// Barrier-option name strings, in CRm order, for the shared (non
	// dsb-only) options.  CRm 0/4 (ssbb/pssbb) are dsb-only and emitted by
	// disasm_sys_emit_baropt, not here.
	fmt.Fprintln(w, "; Barrier-option name strings (shared dmb/dsb options, CRm order).")
	for crm := 0; crm < 16; crm++ {
		opt, ok := bar[byte(crm)]
		if !ok || opt.DsbOnly {
			continue
		}
		fmt.Fprintf(w, "disasm_sys_bo_%s:\n", opt.Name)
		fmt.Fprintf(w, "                defm    %q\n", opt.Name)
		fmt.Fprintln(w, "                defb    0")
	}

	// Barrier-option table indexed by CRm (0..15): a 16-bit pointer to the
	// name string, or 0 where there is no shared name.
	fmt.Fprintln(w)
	fmt.Fprintln(w, "; Barrier-option table indexed by CRm (0..15).  0 = no shared name")
	fmt.Fprintln(w, "; (CRm 0/4 ssbb/pssbb and the #imm fallback are handled by")
	fmt.Fprintln(w, "; disasm_sys_emit_baropt).")
	fmt.Fprintln(w, "disasm_sys_baropt_tbl:")
	for crm := 0; crm < 16; crm++ {
		opt, ok := bar[byte(crm)]
		if !ok || opt.DsbOnly {
			fmt.Fprintf(w, "                defw    0                   ; %d\n", crm)
			continue
		}
		fmt.Fprintf(w, "                defw    disasm_sys_bo_%-7s ; %d\n", opt.Name, crm)
	}

	// AT op table.
	fmt.Fprintln(w)
	fmt.Fprintln(w, "; AT op table — [op1][CRm][op2][NeedsXt][len][name...], 0xFF sentinel.")
	fmt.Fprintln(w, "; ARM ARM C5.3.1.  All AT ops take Xt.")
	fmt.Fprintln(w, "disasm_sys_at_tbl:")
	for _, n := range sortedATIC(atKeys(at)) {
		op := at[n]
		writeATICRecord(w, op.Op1, op.CRm, op.Op2, op.NeedsXt, n)
	}
	fmt.Fprintln(w, "                defb    &ff")

	// IC op table.
	fmt.Fprintln(w)
	fmt.Fprintln(w, "; IC op table — [op1][CRm][op2][NeedsXt][len][name...], 0xFF sentinel.")
	fmt.Fprintln(w, "; ARM ARM C5.3.10.  ialluis/iallu no Xt; ivau Xt.")
	fmt.Fprintln(w, "disasm_sys_ic_tbl:")
	for _, n := range sortedATIC(icKeys(ic)) {
		op := ic[n]
		writeATICRecord(w, op.Op1, op.CRm, op.Op2, op.NeedsXt, n)
	}
	fmt.Fprintln(w, "                defb    &ff")
	return nil
}

// writeATICRecord emits one AT/IC record:
// `defb op1, CRm, op2, NeedsXt` / `defb len` / `defm "name"`.
func writeATICRecord(w io.Writer, op1, crm, op2 byte, needsXt bool, name string) {
	xt := byte(0)
	if needsXt {
		xt = 1
	}
	fmt.Fprintf(w, "                defb    %d, %d, %d, %d\n", op1, crm, op2, xt)
	fmt.Fprintf(w, "                defb    %d\n", len(name))
	fmt.Fprintf(w, "                defm    %q\n", name)
}

// aticEnc carries an op name and its (op1, CRm, op2) sort key.
type aticEnc struct {
	name          string
	op1, crm, op2 byte
}

func atKeys(m map[string]format.ATOp) []aticEnc {
	out := make([]aticEnc, 0, len(m))
	for n, op := range m {
		out = append(out, aticEnc{n, op.Op1, op.CRm, op.Op2})
	}
	return out
}

func icKeys(m map[string]format.ICOp) []aticEnc {
	out := make([]aticEnc, 0, len(m))
	for n, op := range m {
		out = append(out, aticEnc{n, op.Op1, op.CRm, op.Op2})
	}
	return out
}

// sortedATIC returns the op names ordered by (op1, CRm, op2) — the
// deterministic order that reproduces the previous hand-written tables.
func sortedATIC(es []aticEnc) []string {
	sort.Slice(es, func(i, j int) bool {
		a, b := es[i], es[j]
		if a.op1 != b.op1 {
			return a.op1 < b.op1
		}
		if a.crm != b.crm {
			return a.crm < b.crm
		}
		return a.op2 < b.op2
	})
	out := make([]string, len(es))
	for i, e := range es {
		out[i] = e.name
	}
	return out
}

func writeSysoptsHeader(w io.Writer) {
	fmt.Fprintln(w, "; GENERATED by tools/tables-gen — do not edit; regen with make tables")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; disasm_sysopts.inc — the AArch64 System-group AT / IC / barrier-option")
	fmt.Fprintln(w, "; tables for the Z80 disassembler (src/disasm.asm).")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; The bytes are projected from the Go authority")
	fmt.Fprintln(w, "; tools/sam-aarch64-format/sysregs.go (ATOps / ICOps / BarrierOptions) —")
	fmt.Fprintln(w, "; the single source of truth shared with the Go decoder (aarch64dec/sys.go),")
	fmt.Fprintln(w, "; so the two disassemblers cannot drift.")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; Consumed by disasm_sys_emit_baropt (disasm_sys_baropt_tbl) and")
	fmt.Fprintln(w, "; disasm_sys_find_atic (disasm_sys_at_tbl / disasm_sys_ic_tbl).  The")
	fmt.Fprintln(w, "; dsb-only options ssbb (CRm 0) and pssbb (CRm 4) are NOT projected here;")
	fmt.Fprintln(w, "; disasm_sys_emit_baropt emits them (and the #imm fallback) directly.")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; The sync guard tools/sam-aarch64-format/sysopts_z80sync_test.go (CI job")
	fmt.Fprintln(w, "; `sysreg-sync`) decodes these bytes and compares them field-by-field")
	fmt.Fprintln(w, "; against the Go maps (at/ic are NOT in the release corpus, so the disasm")
	fmt.Fprintln(w, "; oracle does not cover them — this guard does).  The freshness guard")
	fmt.Fprintln(w, "; `make tables-sync-check` fails if this file drifts from `make tables`")
	fmt.Fprintln(w, "; output (a Go-side edit that forgot to regenerate, or a hand edit here).")
	fmt.Fprintln(w)
}
