package emit

import (
	"bufio"
	"bytes"
	"sort"
	"strconv"
	"strings"
	"testing"

	format "github.com/petemoore/sam-aarch64/tools/sam-aarch64-format"
)

// decodeTables parses a generated sysreg_tables.inc back into per-table
// record streams. It mirrors the page-13 matcher's view: it flattens each
// `<label>:` section's defb/defm bytes, then walks
// `[name_len][name][nFields]` records terminated by name_len == 0. This is
// the same shape sysregs_z80sync_test.go decodes, so a round-trip here proves
// the emitter writes exactly what the runtime walker consumes.
func decodeTables(t *testing.T, src string) map[string][]tblEntry {
	t.Helper()
	nFields := map[string]int{
		"sysreg_table": 5,
		"pstate_table": 2,
		"dc_table":     4,
		"tlbi_table":   5,
	}
	out := map[string][]tblEntry{}
	for label, nf := range nFields {
		out[label] = decodeOneTable(t, src, label, nf)
	}
	return out
}

type tblEntry struct {
	name   string
	fields []byte
}

func decodeOneTable(t *testing.T, src, label string, nFields int) []tblEntry {
	t.Helper()
	var raw []byte
	sc := bufio.NewScanner(strings.NewReader(src))
	in := false
	for sc.Scan() {
		line := sc.Text()
		if idx := strings.IndexByte(line, ';'); idx >= 0 {
			line = line[:idx]
		}
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		// A column-0 token ending in ':' starts/ends a section.
		if line[0] != ' ' && line[0] != '\t' {
			tok := strings.Fields(trimmed)[0]
			if strings.HasSuffix(tok, ":") {
				in = tok == label+":"
				continue
			}
		}
		if !in {
			continue
		}
		fields := strings.Fields(trimmed)
		op := strings.ToLower(fields[0])
		rest := strings.TrimSpace(trimmed[len(fields[0]):])
		switch op {
		case "defb":
			for _, tok := range strings.Split(rest, ",") {
				v, err := strconv.ParseUint(strings.TrimSpace(tok), 10, 8)
				if err != nil {
					t.Fatalf("%s: bad defb byte %q: %v", label, tok, err)
				}
				raw = append(raw, byte(v))
			}
		case "defm":
			first := strings.IndexByte(rest, '"')
			last := strings.LastIndexByte(rest, '"')
			if first < 0 || last <= first {
				t.Fatalf("%s: defm not a quoted string: %q", label, rest)
			}
			raw = append(raw, []byte(rest[first+1:last])...)
		default:
			t.Fatalf("%s: unexpected directive %q", label, op)
		}
	}
	// Walk records.
	var out []tblEntry
	i := 0
	for {
		if i >= len(raw) {
			t.Fatalf("%s: ran off end without a 0 terminator", label)
		}
		n := int(raw[i])
		i++
		if n == 0 {
			break
		}
		if i+n+nFields > len(raw) {
			t.Fatalf("%s: truncated record", label)
		}
		out = append(out, tblEntry{
			name:   string(raw[i : i+n]),
			fields: append([]byte(nil), raw[i+n:i+n+nFields]...),
		})
		i += n + nFields
	}
	return out
}

func render(t *testing.T) string {
	t.Helper()
	var buf bytes.Buffer
	if err := RenderSysregInc(&buf); err != nil {
		t.Fatalf("RenderSysregInc: %v", err)
	}
	return buf.String()
}

// TestSysregEmitDeterministic asserts the emitter output is byte-for-byte
// stable across runs — the freshness guard (make tables-sync-check) relies
// on this.
func TestSysregEmitDeterministic(t *testing.T) {
	if render(t) != render(t) {
		t.Fatal("RenderSysregInc is not deterministic across runs")
	}
}

// TestSysregEmitHeader asserts the GENERATED marker is present so a reader
// (and a grep) can tell the file is machine-written.
func TestSysregEmitHeader(t *testing.T) {
	if !strings.HasPrefix(render(t), "; GENERATED by tools/tables-gen") {
		t.Fatal("generated sysreg_tables.inc is missing its GENERATED header")
	}
}

// TestSysregEmitNameSorted asserts each table's entries are in ascending
// name order (the deterministic order the freshness guard expects).
func TestSysregEmitNameSorted(t *testing.T) {
	tables := decodeTables(t, render(t))
	for label, entries := range tables {
		names := make([]string, len(entries))
		for i, e := range entries {
			names[i] = e.name
		}
		if !sort.StringsAreSorted(names) {
			t.Errorf("%s entries are not name-sorted: %v", label, names)
		}
	}
}

// TestSysregEmitMatchesGo decodes the generated tables and checks them
// against the Go authority maps: the sysreg_table is the SUBSET listed in
// SysregSubset (every entry byte-identical to Go); pstate/dc/tlbi are FULL
// parity with the Go maps (every Go entry present, byte-identical). This is
// the emitter-faithfulness guard at the package level (the CI sysreg-sync
// job additionally guards it against the committed src/sysreg_tables.inc).
func TestSysregEmitMatchesGo(t *testing.T) {
	tables := decodeTables(t, render(t))

	// sysreg_table — subset.
	named := format.NamedSysRegs()
	gotSys := map[string][]byte{}
	for _, e := range tables["sysreg_table"] {
		gotSys[e.name] = e.fields
	}
	wantSubset := append([]string(nil), SysregSubset...)
	sort.Strings(wantSubset)
	if len(gotSys) != len(wantSubset) {
		t.Errorf("sysreg_table: got %d entries, want %d (the subset)", len(gotSys), len(wantSubset))
	}
	for _, n := range wantSubset {
		sr, ok := named[n]
		if !ok {
			t.Errorf("sysreg subset name %q absent from Go namedSysRegs", n)
			continue
		}
		want := []byte{sr.Op0, sr.Op1, sr.CRn, sr.CRm, sr.Op2}
		if !bytes.Equal(gotSys[n], want) {
			t.Errorf("sysreg %q: got %v want %v", n, gotSys[n], want)
		}
	}

	// pstate_table — full parity.
	pstate := format.PStateFields()
	checkFullParity(t, "pstate_table", tables["pstate_table"], len(pstate), func(name string) ([]byte, bool) {
		pf, ok := pstate[name]
		if !ok {
			return nil, false
		}
		return []byte{pf.Op1, pf.Op2}, true
	})

	// dc_table — full parity.
	dc := format.DCOps()
	checkFullParity(t, "dc_table", tables["dc_table"], len(dc), func(name string) ([]byte, bool) {
		op, ok := dc[name]
		if !ok {
			return nil, false
		}
		return []byte{op.Op1, op.CRn, op.CRm, op.Op2}, true
	})

	// tlbi_table — full parity.
	tlbi := format.TLBIOps()
	checkFullParity(t, "tlbi_table", tables["tlbi_table"], len(tlbi), func(name string) ([]byte, bool) {
		op, ok := tlbi[name]
		if !ok {
			return nil, false
		}
		needsXt := byte(0)
		if op.NeedsXt {
			needsXt = 1
		}
		return []byte{op.Op1, op.CRn, op.CRm, op.Op2, needsXt}, true
	})
}

func checkFullParity(t *testing.T, label string, entries []tblEntry, goCount int, goFields func(string) ([]byte, bool)) {
	t.Helper()
	if len(entries) != goCount {
		t.Errorf("%s: got %d entries, want %d (full parity with Go)", label, len(entries), goCount)
	}
	for _, e := range entries {
		want, ok := goFields(e.name)
		if !ok {
			t.Errorf("%s: %q present in generated table but absent from Go", label, e.name)
			continue
		}
		if !bytes.Equal(e.fields, want) {
			t.Errorf("%s %q: got %v want %v", label, e.name, e.fields, want)
		}
	}
}
