package emit

import (
	"fmt"
	"io"
	"sort"

	format "github.com/petemoore/sam-aarch64/tools/sam-aarch64-format"
)

// SysregSubset is the ordered list of architectural system-register names
// the Z80 src/sysreg_tables.inc carries in its sysreg_table. It is a SUBSET
// of the Go authority namedSysRegs: an unnamed system register is reachable
// on both sides via the generic Sn_op1_Cm_Cn_op2 form (ParseSysReg /
// SysRegName), so a missing named entry here is not a correctness gap — only
// a missing convenience name. The pstate / dc / tlbi families carry NO such
// generic fallback in Go, so those three tables are emitted at FULL parity
// from the Go maps (see RenderSysregInc).
//
// The emitter sorts these names, so list order here is irrelevant; the names
// just enumerate which sysregs the Z80 side spells. Every name MUST exist in
// the Go namedSysRegs map, or RenderSysregInc errors (catching a typo / a
// Go-side rename at generation time).
var SysregSubset = []string{
	"sctlr_el1", "nzcv", "currentel", "midr_el1", "mpidr_el1",
	"esr_el1", "elr_el1", "far_el1",
	"cntpct_el0", "cntp_ctl_el0", "cntp_cval_el0",
	"elr_el3", "hcr_el2", "mair_el1", "scr_el3", "spsr_el3",
	"tcr_el1", "ttbr0_el1", "ttbr1_el1", "vbar_el1",
}

// RenderSysregInc writes the generated src/sysreg_tables.inc: the four
// AArch64 System-group name↔encoding tables (sysreg / pstate / dc / tlbi),
// projected from the Go authority tools/sam-aarch64-format/sysregs.go.
//
// Output is byte-for-byte deterministic: entries are sorted by name within
// each table, the per-record layout is the fixed
// `[name_len u8][name bytes][field bytes…]` (terminated by name_len == 0)
// that both the page-13 matcher (src/sysreg_data.asm) and the page-15
// disassembler (src/disasm.asm via src/sysreg_names.inc) walk at runtime.
//
// Field counts and order per table (matching the Z80 record decoders):
//
//	sysreg_table — 5 bytes: op0, op1, CRn, CRm, op2
//	pstate_table — 2 bytes: op1, op2
//	dc_table     — 4 bytes: op1, CRn, CRm, op2
//	tlbi_table   — 5 bytes: op1, CRn, CRm, op2, NeedsXt
func RenderSysregInc(w io.Writer) error {
	named := format.NamedSysRegs()
	pstate := format.PStateFields()
	dc := format.DCOps()
	tlbi := format.TLBIOps()

	writeHeader(w)

	// sysreg_table — the SUBSET listed in SysregSubset.
	fmt.Fprintf(w, "; sysreg_table — %d entries (a subset of the Go authority; unnamed\n", len(SysregSubset))
	fmt.Fprintln(w, "; system registers reach both sides via the generic Sn_op1_Cm_Cn_op2 form).")
	fmt.Fprintln(w, "; Format per entry: [name_len u8][name_bytes][op0][op1][CRn][CRm][op2].")
	fmt.Fprintln(w, "sysreg_table:")
	sysNames := append([]string(nil), SysregSubset...)
	sort.Strings(sysNames)
	for _, n := range sysNames {
		sr, ok := named[n]
		if !ok {
			return fmt.Errorf("sysreg subset name %q is absent from the Go namedSysRegs authority", n)
		}
		writeRecord(w, n, []byte{sr.Op0, sr.Op1, sr.CRn, sr.CRm, sr.Op2})
	}
	writeTerminator(w)

	// pstate_table — FULL parity with the Go pstateFields map.
	fmt.Fprintln(w)
	fmt.Fprintln(w)
	fmt.Fprintf(w, "; pstate_table — full parity with the Go authority pstateFields.  %d entries.\n", len(pstate))
	fmt.Fprintln(w, "; Format per entry: [name_len u8][name_bytes][op1 u8][op2 u8].")
	fmt.Fprintln(w, "pstate_table:")
	for _, n := range sortedKeys(pstate) {
		pf := pstate[n]
		writeRecord(w, n, []byte{pf.Op1, pf.Op2})
	}
	writeTerminator(w)

	// dc_table — FULL parity with the Go dcOps map.
	fmt.Fprintln(w)
	fmt.Fprintln(w)
	fmt.Fprintf(w, "; dc_table — full parity with the Go authority dcOps.  %d entries.\n", len(dc))
	fmt.Fprintln(w, "; Format per entry: [name_len u8][name_bytes][op1 u8][CRn u8][CRm u8][op2 u8].")
	fmt.Fprintln(w, "dc_table:")
	for _, n := range sortedKeys(dc) {
		op := dc[n]
		writeRecord(w, n, []byte{op.Op1, op.CRn, op.CRm, op.Op2})
	}
	writeTerminator(w)

	// tlbi_table — FULL parity with the Go tlbiOps map.
	fmt.Fprintln(w)
	fmt.Fprintln(w)
	fmt.Fprintf(w, "; tlbi_table — full parity with the Go authority tlbiOps.  %d entries.\n", len(tlbi))
	fmt.Fprintln(w, "; Format per entry:")
	fmt.Fprintln(w, ";   [name_len u8][name_bytes][op1 u8][CRn u8][CRm u8][op2 u8][NeedsXt u8].")
	fmt.Fprintln(w, "tlbi_table:")
	for _, n := range sortedKeys(tlbi) {
		op := tlbi[n]
		needsXt := byte(0)
		if op.NeedsXt {
			needsXt = 1
		}
		writeRecord(w, n, []byte{op.Op1, op.CRn, op.CRm, op.Op2, needsXt})
	}
	writeTerminator(w)
	return nil
}

func writeHeader(w io.Writer) {
	fmt.Fprintln(w, "; GENERATED by tools/tables-gen — do not edit; regen with make tables")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; sysreg_tables.inc — the four AArch64 System-group name↔encoding tables")
	fmt.Fprintln(w, "; (sysreg / pstate / dc / tlbi), shared by BOTH page-13 and page-15.")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; The bytes are projected from the Go authority")
	fmt.Fprintln(w, "; tools/sam-aarch64-format/sysregs.go (namedSysRegs / pstateFields / dcOps /")
	fmt.Fprintln(w, "; tlbiOps).  `include`d by:")
	fmt.Fprintln(w, ";   - src/sysreg_data.asm (page 13, name→encoding matcher, do_match)")
	fmt.Fprintln(w, ";   - src/disasm.asm via src/sysreg_names.inc (page 15, encoding→name)")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; Layout per record: `[name_len u8][name bytes][N field bytes...]`,")
	fmt.Fprintln(w, "; terminated by name_len == 0.  Entries are sorted by name within each")
	fmt.Fprintln(w, "; table (the matcher and disassembler do order-insensitive linear walks).")
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w, "; The sync guard tools/sam-aarch64-format/sysregs_z80sync_test.go (CI job")
	fmt.Fprintln(w, "; `sysreg-sync`) decodes these bytes and compares them field-by-field")
	fmt.Fprintln(w, "; against the Go maps, so a generator-emitter bug (wrong field order,")
	fmt.Fprintln(w, "; missing terminator) becomes red CI.  The freshness guard")
	fmt.Fprintln(w, "; `make tables-sync-check` fails if this file drifts from `make tables`")
	fmt.Fprintln(w, "; output (a Go-side edit that forgot to regenerate, or a hand edit here).")
	fmt.Fprintln(w, "; All names are lower case (the page-13 matcher lowercases before compare).")
	fmt.Fprintln(w)
}

// writeRecord emits one `[name_len][name][fields]` record as the pyz80
// `defb <len>` / `defm "<name>"` / `defb <field, field, ...>` triple.
func writeRecord(w io.Writer, name string, fields []byte) {
	fmt.Fprintf(w, "                defb    %d\n", len(name))
	fmt.Fprintf(w, "                defm    %q\n", name)
	parts := make([]string, len(fields))
	for i, b := range fields {
		parts[i] = fmt.Sprintf("%d", b)
	}
	fmt.Fprintf(w, "                defb    %s\n", joinComma(parts))
}

func writeTerminator(w io.Writer) {
	fmt.Fprintln(w, "                defb    0")
}

func joinComma(parts []string) string {
	out := ""
	for i, p := range parts {
		if i > 0 {
			out += ", "
		}
		out += p
	}
	return out
}

// sortedKeys returns the keys of a map[string]T sorted ascending.
func sortedKeys[T any](m map[string]T) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
